// Auto-converted from data/trainers/names.asm + pic_pointers_money.asm

export const TRAINER_META = {
  Youngster: { name: "YOUNGSTER", baseMoney: 1500 },
  BugCatcher: { name: "BUG CATCHER", baseMoney: 1000 },
  Lass: { name: "LASS", baseMoney: 1500 },
  Sailor: { name: "SAILOR", baseMoney: 3000 },
  JrTrainerM: { name: "JR.TRAINER M", baseMoney: 2000 },
  JrTrainerF: { name: "JR.TRAINER F", baseMoney: 2000 },
  Pokemaniac: { name: "POKEMANIAC", baseMoney: 5000 },
  SuperNerd: { name: "SUPER NERD", baseMoney: 2500 },
  Hiker: { name: "HIKER", baseMoney: 3500 },
  Biker: { name: "BIKER", baseMoney: 2000 },
  Burglar: { name: "BURGLAR", baseMoney: 9000 },
  Engineer: { name: "ENGINEER", baseMoney: 5000 },
  UnusedJuggler: { name: "JUGGLER", baseMoney: 3500 },
  Fisher: { name: "FISHERMAN", baseMoney: 3500 },
  Swimmer: { name: "SWIMMER", baseMoney: 500 },
  CueBall: { name: "CUE BALL", baseMoney: 2500 },
  Gambler: { name: "GAMBLER", baseMoney: 7000 },
  Beauty: { name: "BEAUTY", baseMoney: 7000 },
  Psychic: { name: "PSYCHIC", baseMoney: 1000 },
  Rocker: { name: "ROCKER", baseMoney: 2500 },
  Juggler: { name: "JUGGLER", baseMoney: 3500 },
  Tamer: { name: "TAMER", baseMoney: 4000 },
  BirdKeeper: { name: "BIRD KEEPER", baseMoney: 2500 },
  Blackbelt: { name: "BLACKBELT", baseMoney: 2500 },
  Rival1: { name: "RIVAL1", baseMoney: 3500 },
  ProfOak: { name: "PROF.OAK", baseMoney: 9900 },
  Chief: { name: "CHIEF", baseMoney: 3000 },
  Scientist: { name: "SCIENTIST", baseMoney: 5000 },
  Giovanni: { name: "GIOVANNI", baseMoney: 9900 },
  Rocket: { name: "ROCKET", baseMoney: 3000 },
  CooltrainerM: { name: "COOLTRAINER M", baseMoney: 3500 },
  CooltrainerF: { name: "COOLTRAINER F", baseMoney: 3500 },
  Bruno: { name: "BRUNO", baseMoney: 9900 },
  Brock: { name: "BROCK", baseMoney: 9900 },
  Misty: { name: "MISTY", baseMoney: 9900 },
  LtSurge: { name: "LT.SURGE", baseMoney: 9900 },
  Erika: { name: "ERIKA", baseMoney: 9900 },
  Koga: { name: "KOGA", baseMoney: 9900 },
  Blaine: { name: "BLAINE", baseMoney: 9900 },
  Sabrina: { name: "SABRINA", baseMoney: 9900 },
  Gentleman: { name: "GENTLEMAN", baseMoney: 7000 },
  Rival2: { name: "RIVAL2", baseMoney: 6500 },
  Rival3: { name: "RIVAL3", baseMoney: 9900 },
  Lorelei: { name: "LORELEI", baseMoney: 9900 },
  Channeler: { name: "CHANNELER", baseMoney: 3000 },
  Agatha: { name: "AGATHA", baseMoney: 9900 },
  Lance: { name: "LANCE", baseMoney: 9900 },
};
