// Word pool, batch 03 - 32 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// Not a curriculum chapter and not a lesson: these rows exist to widen the drill pool. See
// pool-zz-register.js, which turns whatever the pool files registered into templates.
//
// Source tier: `data/wordCandidates.csv` at hardListHits >= 2, the high-confidence core left
// after the >= 3 tier was fully authored. Alphabetical run "disperse" through "figurative".
//
// Banding is judged per word, not by rarity of spelling. Six rows here are ORDINARY words
// carrying a less ordinary sense - `divine` as a verb of inference, `eclipse` as "surpass",
// `dormant`, `exhaustive`, `explicit`, `figurative` - so they sit at band 3 while their
// neighbours sit at 4-5. What makes them AFOQT-worthy is the second sense, not the word.
//
// Two deliberate near-pairs, each given its own slate rather than shared distractors:
// efficacious (adj, "it worked") / efficacy (noun, "the power to work"), kept to different parts
// of speech so no option string is shared; and fallible / feasible, which sound alike and mean
// nothing alike, so their confusables (`fallow`, `feeble`) pull in opposite directions.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-disperse', chapter: CH, concepts: POOL, band: 3,
    word: 'disperse', pos: 'verb', charge: 'neutral',
    gloss: 'to break up and scatter in different directions',
    answer: 'scatter',
    antonym: 'gather',
    related: 'dilute',
    decoy: 'engrave',
    confusable: { word: 'disburse', meaning: 'pay out' },
    sentence: 'The wind began to disperse the smoke across the valley.',
  },
  {
    id: 'wk-dissent', chapter: CH, concepts: POOL, band: 3,
    word: 'dissent', pos: 'noun', charge: 'neutral',
    gloss: 'disagreement with an official or majority opinion',
    answer: 'disagreement',
    antonym: 'agreement',
    related: 'protest',
    decoy: 'inventory',
    confusable: { word: 'descent', meaning: 'downward slope' },
    sentence: 'A single voice of dissent was enough to delay the vote.',
  },
  {
    id: 'wk-distaff', chapter: CH, concepts: POOL, band: 5,
    word: 'distaff', pos: 'adj', charge: 'neutral',
    gloss: 'relating to women, or to the female side of a family',
    answer: 'female',
    antonym: 'male',
    related: 'maternal',
    decoy: 'nautical',
    confusable: { word: 'distant', meaning: 'far off' },
    sentence: 'Property on the distaff side of the family passed to her aunt.',
  },
  {
    id: 'wk-dither', chapter: CH, concepts: POOL, band: 4,
    word: 'dither', pos: 'verb', charge: 'neg',
    gloss: 'to be indecisive; to waver nervously instead of acting',
    answer: 'hesitate',
    antonym: 'decide',
    related: 'fret',
    decoy: 'sprint',
    confusable: { word: 'wither', meaning: 'shrivel' },
    sentence: 'He dithered for an hour over which of the two offers to accept.',
  },
  {
    id: 'wk-diurnal', chapter: CH, concepts: POOL, band: 5,
    word: 'diurnal', pos: 'adj', charge: 'neutral',
    gloss: 'active or occurring during the day rather than at night',
    answer: 'daytime',
    antonym: 'nocturnal',
    related: 'solar',
    decoy: 'aquatic',
    confusable: { word: 'diuretic', meaning: 'urine-inducing' },
    sentence: 'Most songbirds are diurnal, going quiet as soon as the sun sets.',
  },
  {
    id: 'wk-divine', chapter: CH, concepts: POOL, band: 4,
    word: 'divine', pos: 'verb', charge: 'neutral',
    gloss: 'to work out or discover something by intuition rather than by evidence',
    answer: 'infer',
    antonym: 'overlook',
    related: 'worship',
    decoy: 'measure',
    confusable: { word: 'divide', meaning: 'split' },
    sentence: 'She could divine his mood from the way he set down his keys.',
  },
  {
    id: 'wk-dormant', chapter: CH, concepts: POOL, band: 3,
    word: 'dormant', pos: 'adj', charge: 'neutral',
    gloss: 'temporarily inactive, as though asleep, but able to become active again',
    answer: 'latent',
    antonym: 'active',
    related: 'wintry',
    decoy: 'fragrant',
    confusable: { word: 'dormitory', meaning: 'sleeping quarters' },
    sentence: 'The volcano had been dormant for nearly three centuries.',
  },
  {
    id: 'wk-dovetail', chapter: CH, concepts: POOL, band: 4,
    word: 'dovetail', pos: 'verb', charge: 'pos',
    gloss: 'to fit together neatly and work well in combination',
    answer: 'interlock',
    antonym: 'clash',
    related: 'chisel',
    decoy: 'evaporate',
    confusable: { word: 'detail', meaning: 'itemize' },
    sentence: "Her research dovetails neatly with the team's current project.",
  },
  {
    id: 'wk-duplicity', chapter: CH, concepts: POOL, band: 4,
    word: 'duplicity', pos: 'noun', charge: 'neg',
    gloss: 'deceitfulness; saying one thing while intending another',
    answer: 'deceit',
    antonym: 'candor',
    related: 'secrecy',
    decoy: 'stamina',
    confusable: { word: 'duplication', meaning: 'copying' },
    sentence: 'The contract exposed a level of duplicity no one had suspected.',
  },
  {
    id: 'wk-eclipse', chapter: CH, concepts: POOL, band: 3,
    word: 'eclipse', pos: 'verb', charge: 'neutral',
    gloss: 'to surpass or overshadow, making the other thing seem lesser',
    answer: 'surpass',
    antonym: 'trail',
    related: 'shadow',
    decoy: 'purchase',
    confusable: { word: 'ellipse', meaning: 'oval' },
    sentence: 'Her later novels eclipsed everything she had written before.',
  },
  {
    id: 'wk-efficacious', chapter: CH, concepts: POOL, band: 4,
    word: 'efficacious', pos: 'adj', charge: 'pos',
    gloss: 'producing the intended result; effective for its purpose',
    answer: 'potent',
    antonym: 'useless',
    related: 'medicinal',
    decoy: 'ornate',
    confusable: { word: 'efficient', meaning: 'economical' },
    sentence: 'The treatment proved efficacious in nearly every trial.',
  },
  {
    id: 'wk-efficacy', chapter: CH, concepts: POOL, band: 4,
    word: 'efficacy', pos: 'noun', charge: 'pos',
    gloss: 'the power to produce a desired result',
    answer: 'potency',
    antonym: 'futility',
    related: 'dosage',
    decoy: 'symmetry',
    confusable: { word: 'efficiency', meaning: 'thrift' },
    sentence: 'Researchers questioned the efficacy of the older vaccine.',
  },
  {
    id: 'wk-effigy', chapter: CH, concepts: POOL, band: 4,
    word: 'effigy', pos: 'noun', charge: 'neg',
    gloss: 'a crude model of a person, made to be mocked or burned',
    answer: 'likeness',
    antonym: 'original',
    related: 'bonfire',
    decoy: 'treaty',
    confusable: { word: 'elegy', meaning: 'lament' },
    sentence: 'Protesters burned an effigy of the finance minister.',
  },
  {
    id: 'wk-elated', chapter: CH, concepts: POOL, band: 3,
    word: 'elated', pos: 'adj', charge: 'pos',
    gloss: 'extremely happy and in high spirits',
    answer: 'overjoyed',
    antonym: 'dejected',
    related: 'relieved',
    decoy: 'sunburned',
    confusable: { word: 'elevated', meaning: 'raised' },
    sentence: 'She was elated to hear that the grant had been approved.',
  },
  {
    id: 'wk-eminent', chapter: CH, concepts: POOL, band: 3,
    word: 'eminent', pos: 'adj', charge: 'pos',
    gloss: 'standing high in rank or reputation; well known and respected',
    answer: 'distinguished',
    antonym: 'obscure',
    related: 'wealthy',
    decoy: 'circular',
    confusable: { word: 'imminent', meaning: 'impending' },
    sentence: 'The lecture was delivered by an eminent historian of the period.',
  },
  {
    id: 'wk-encomium', chapter: CH, concepts: POOL, band: 5,
    word: 'encomium', pos: 'noun', charge: 'pos',
    gloss: 'a formal expression of warm, high praise',
    answer: 'tribute',
    antonym: 'censure',
    related: 'ovation',
    decoy: 'inventory',
    confusable: { word: 'compendium', meaning: 'summary' },
    sentence: 'His retirement dinner turned into a long encomium from every department head.',
  },
  {
    id: 'wk-ennui', chapter: CH, concepts: POOL, band: 5,
    word: 'ennui', pos: 'noun', charge: 'neg',
    gloss: 'listless weariness that comes from having nothing that interests you',
    answer: 'boredom',
    antonym: 'zest',
    related: 'apathy',
    decoy: 'draft',
    confusable: { word: 'envy', meaning: 'jealousy' },
    sentence: 'A deep ennui settled over the crew during the long crossing.',
  },
  {
    id: 'wk-enthrall', chapter: CH, concepts: POOL, band: 4,
    word: 'enthrall', pos: 'verb', charge: 'pos',
    gloss: 'to hold someone spellbound; to capture their attention completely',
    answer: 'captivate',
    antonym: 'bore',
    related: 'entertain',
    decoy: 'refund',
    confusable: { word: 'enroll', meaning: 'register' },
    sentence: 'The storyteller enthralled the entire room for two hours.',
  },
  {
    id: 'wk-epicure', chapter: CH, concepts: POOL, band: 5,
    word: 'epicure', pos: 'noun', charge: 'neutral',
    gloss: 'a person with refined and discriminating taste in food and drink',
    answer: 'gourmet',
    antonym: 'ascetic',
    related: 'chef',
    decoy: 'sentry',
    confusable: { word: 'epicenter', meaning: 'focal point' },
    sentence: 'Only an epicure would notice the difference between the two vintages.',
  },
  {
    id: 'wk-ethos', chapter: CH, concepts: POOL, band: 4,
    word: 'ethos', pos: 'noun', charge: 'neutral',
    gloss: 'the characteristic spirit or guiding beliefs of a group or culture',
    answer: 'spirit',
    antonym: 'anarchy',
    related: 'custom',
    decoy: 'ledger',
    confusable: { word: 'pathos', meaning: 'pity' },
    sentence: "The company's ethos of quiet competence showed in every product.",
  },
  {
    id: 'wk-exacting', chapter: CH, concepts: POOL, band: 4,
    word: 'exacting', pos: 'adj', charge: 'neutral',
    gloss: 'making severe demands; requiring great care, effort and accuracy',
    answer: 'demanding',
    antonym: 'lenient',
    related: 'precise',
    decoy: 'portable',
    confusable: { word: 'exciting', meaning: 'thrilling' },
    sentence: 'The conductor was exacting about every entrance and every rest.',
  },
  {
    id: 'wk-exhaustive', chapter: CH, concepts: POOL, band: 3,
    word: 'exhaustive', pos: 'adj', charge: 'neutral',
    gloss: 'complete and thorough, leaving no part of the subject untouched',
    answer: 'thorough',
    antonym: 'cursory',
    related: 'lengthy',
    decoy: 'edible',
    confusable: { word: 'exhausting', meaning: 'tiring' },
    sentence: 'The report offered an exhaustive account of every transaction.',
  },
  {
    id: 'wk-expedient', chapter: CH, concepts: POOL, band: 4,
    word: 'expedient', pos: 'adj', charge: 'neutral',
    gloss: 'useful for getting the immediate result, whether or not it is principled',
    answer: 'convenient',
    antonym: 'principled',
    related: 'temporary',
    decoy: 'aromatic',
    confusable: { word: 'expeditious', meaning: 'speedy' },
    sentence: 'Delaying the announcement was the expedient choice, if not the honest one.',
  },
  {
    id: 'wk-explicit', chapter: CH, concepts: POOL, band: 3,
    word: 'explicit', pos: 'adj', charge: 'neutral',
    gloss: 'stated openly and exactly, leaving no room for doubt',
    answer: 'definite',
    antonym: 'vague',
    related: 'graphic',
    decoy: 'elastic',
    confusable: { word: 'implicit', meaning: 'implied' },
    sentence: 'The instructions were explicit about which form to use.',
  },
  {
    id: 'wk-exponent', chapter: CH, concepts: POOL, band: 4,
    word: 'exponent', pos: 'noun', charge: 'pos',
    gloss: 'a person who argues for and promotes an idea or method',
    answer: 'advocate',
    antonym: 'critic',
    related: 'follower',
    decoy: 'surveyor',
    confusable: { word: 'opponent', meaning: 'adversary' },
    sentence: 'She became the leading exponent of the new teaching method.',
  },
  {
    id: 'wk-fallible', chapter: CH, concepts: POOL, band: 3,
    word: 'fallible', pos: 'adj', charge: 'neutral',
    gloss: 'capable of making mistakes or being wrong',
    answer: 'imperfect',
    antonym: 'flawless',
    related: 'human',
    decoy: 'crimson',
    confusable: { word: 'fallow', meaning: 'uncultivated' },
    sentence: 'Even the best instruments are fallible under extreme cold.',
  },
  {
    id: 'wk-fanciful', chapter: CH, concepts: POOL, band: 3,
    word: 'fanciful', pos: 'adj', charge: 'neutral',
    gloss: 'existing only in the imagination; not grounded in fact',
    answer: 'imaginary',
    antonym: 'realistic',
    related: 'childish',
    decoy: 'metallic',
    confusable: { word: 'fancy', meaning: 'elaborate' },
    sentence: 'His fanciful account of the voyage bore little resemblance to the log.',
  },
  {
    id: 'wk-feasible', chapter: CH, concepts: POOL, band: 3,
    word: 'feasible', pos: 'adj', charge: 'neutral',
    gloss: 'able to be done; possible in practice',
    answer: 'workable',
    antonym: 'impossible',
    related: 'affordable',
    decoy: 'audible',
    confusable: { word: 'feeble', meaning: 'frail' },
    sentence: 'Only one of the three routes turned out to be feasible in winter.',
  },
  {
    id: 'wk-feckless', chapter: CH, concepts: POOL, band: 4,
    word: 'feckless', pos: 'adj', charge: 'neg',
    gloss: 'weak and irresponsible; unable to get anything useful done',
    answer: 'ineffective',
    antonym: 'capable',
    related: 'lazy',
    decoy: 'waterproof',
    confusable: { word: 'reckless', meaning: 'rash' },
    sentence: 'A feckless manager let three deadlines pass without a word.',
  },
  {
    id: 'wk-fervor', chapter: CH, concepts: POOL, band: 4,
    word: 'fervor', pos: 'noun', charge: 'pos',
    gloss: 'intense and passionate feeling',
    answer: 'passion',
    antonym: 'apathy',
    related: 'crusade',
    decoy: 'lattice',
    confusable: { word: 'favor', meaning: 'kindness' },
    sentence: 'She argued her case with a fervor that surprised the committee.',
  },
  {
    id: 'wk-fetid', chapter: CH, concepts: POOL, band: 4,
    word: 'fetid', pos: 'adj', charge: 'neg',
    gloss: 'having a strong, foul smell',
    answer: 'putrid',
    antonym: 'fragrant',
    related: 'stagnant',
    decoy: 'luminous',
    confusable: { word: 'fetal', meaning: 'unborn' },
    sentence: 'A fetid smell rose from the drainage ditch behind the mill.',
  },
  {
    id: 'wk-figurative', chapter: CH, concepts: POOL, band: 3,
    word: 'figurative', pos: 'adj', charge: 'neutral',
    gloss: 'using words in a non-literal, metaphorical sense',
    answer: 'metaphorical',
    antonym: 'literal',
    related: 'poetic',
    decoy: 'granular',
    confusable: { word: 'imaginative', meaning: 'inventive' },
    sentence: 'He meant it in a figurative sense, though his audience took him at his word.',
  },
]);
