// Word pool, batch 06 - 32 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// Source tier: `data/wordCandidates.csv` at hardListHits >= 2. Alphabetical run "missive"
// through "pliant". Conventions: see pool-03.js.
//
// `overt` is the row worth reading before you copy this pattern. Its obvious confusable is
// `covert`, and that is exactly why it is NOT used here: "secret" is also a perfectly good
// ANTONYM of overt, so the opposite frame (wk-opposite-b3) would have shipped with two correct
// answers - one of them labelled as the trap. Nothing structural catches that; the collision is
// semantic. `inert` / "motionless" rhymes just as usefully and collides with nothing.
//
// Same care on `noxious` / `obnoxious` and `negligent` / `negligible`, which ARE safe: the
// confusable's meaning there is unrelated to the headword's opposite, so both frames stay
// single-answered.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-missive', chapter: CH, concepts: POOL, band: 4,
    word: 'missive', pos: 'noun', charge: 'neutral',
    gloss: 'a letter, especially a long or official one',
    answer: 'letter',
    antonym: 'silence',
    related: 'envelope',
    decoy: 'turbine',
    confusable: { word: 'missile', meaning: 'projectile' },
    sentence: 'A long missive from the head office arrived on Friday.',
  },
  {
    id: 'wk-modish', chapter: CH, concepts: POOL, band: 5,
    word: 'modish', pos: 'adj', charge: 'neutral',
    gloss: 'fashionable in a way that will date quickly',
    answer: 'fashionable',
    antonym: 'dated',
    related: 'urban',
    decoy: 'brackish',
    confusable: { word: 'modest', meaning: 'unassuming' },
    sentence: 'Her modish coat looked out of place in the muddy yard.',
  },
  {
    id: 'wk-molt', chapter: CH, concepts: POOL, band: 3,
    word: 'molt', pos: 'verb', charge: 'neutral',
    gloss: 'to shed feathers, skin or hair so that new growth can replace them',
    answer: 'shed',
    antonym: 'retain',
    related: 'preen',
    decoy: 'navigate',
    confusable: { word: 'melt', meaning: 'liquefy' },
    sentence: 'The birds molt in late summer and look ragged for a month.',
  },
  {
    id: 'wk-monastic', chapter: CH, concepts: POOL, band: 4,
    word: 'monastic', pos: 'adj', charge: 'neutral',
    gloss: 'severely plain and shut away from the world, as monks live',
    answer: 'secluded',
    antonym: 'worldly',
    related: 'devout',
    decoy: 'ceramic',
    confusable: { word: 'monolithic', meaning: 'uniform' },
    sentence: 'He kept a monastic routine: up at five, in bed by nine.',
  },
  {
    id: 'wk-mores', chapter: CH, concepts: POOL, band: 5,
    word: 'mores', pos: 'noun', charge: 'neutral',
    gloss: 'the accepted customs and moral rules of a community',
    answer: 'customs',
    antonym: 'lawlessness',
    related: 'folklore',
    decoy: 'plumage',
    confusable: { word: 'morass', meaning: 'swamp' },
    sentence: 'The mores of the village had not changed in fifty years.',
  },
  {
    id: 'wk-multifarious', chapter: CH, concepts: POOL, band: 5,
    word: 'multifarious', pos: 'adj', charge: 'neutral',
    gloss: 'having great variety; of many different kinds at once',
    answer: 'diverse',
    antonym: 'uniform',
    related: 'scattered',
    decoy: 'lunar',
    confusable: { word: 'nefarious', meaning: 'wicked' },
    sentence: 'His multifarious interests ran from beekeeping to medieval law.',
  },
  {
    id: 'wk-naive', chapter: CH, concepts: POOL, band: 3,
    word: 'naive', pos: 'adj', charge: 'neg',
    gloss: 'lacking experience or judgement; too ready to believe what you are told',
    answer: 'gullible',
    antonym: 'worldly',
    related: 'innocent',
    decoy: 'padded',
    confusable: { word: 'native', meaning: 'indigenous' },
    sentence: 'It was naive to expect the contract to be honoured without a deposit.',
  },
  {
    id: 'wk-negate', chapter: CH, concepts: POOL, band: 3,
    word: 'negate', pos: 'verb', charge: 'neutral',
    gloss: 'to cancel something out or make it ineffective',
    answer: 'nullify',
    antonym: 'confirm',
    related: 'subtract',
    decoy: 'assemble',
    confusable: { word: 'negotiate', meaning: 'bargain' },
    sentence: 'One clerical error negated three weeks of work.',
  },
  {
    id: 'wk-negligent', chapter: CH, concepts: POOL, band: 3,
    word: 'negligent', pos: 'adj', charge: 'neg',
    gloss: 'failing to take the care that a duty requires',
    answer: 'careless',
    antonym: 'diligent',
    related: 'forgetful',
    decoy: 'hollow',
    confusable: { word: 'negligible', meaning: 'trivial' },
    sentence: 'The inquiry found the contractor negligent on three separate counts.',
  },
  {
    id: 'wk-neologism', chapter: CH, concepts: POOL, band: 5,
    word: 'neologism', pos: 'noun', charge: 'neutral',
    gloss: 'a newly coined word or expression',
    answer: 'coinage',
    antonym: 'archaism',
    related: 'slang',
    decoy: 'quarry',
    confusable: { word: 'neurosis', meaning: 'anxiety' },
    sentence: 'Half the report was written in neologisms nobody outside the firm understood.',
  },
  {
    id: 'wk-nonchalant', chapter: CH, concepts: POOL, band: 4,
    word: 'nonchalant', pos: 'adj', charge: 'neutral',
    gloss: 'calmly unbothered; showing no concern at all',
    answer: 'unconcerned',
    antonym: 'anxious',
    related: 'confident',
    decoy: 'woven',
    confusable: { word: 'noncommittal', meaning: 'evasive' },
    sentence: 'He gave a nonchalant shrug and went back to his book.',
  },
  {
    id: 'wk-noxious', chapter: CH, concepts: POOL, band: 4,
    word: 'noxious', pos: 'adj', charge: 'neg',
    gloss: 'harmful or poisonous to living things',
    answer: 'harmful',
    antonym: 'wholesome',
    related: 'pungent',
    decoy: 'concave',
    confusable: { word: 'obnoxious', meaning: 'offensive' },
    sentence: 'Noxious fumes forced the crew off the lower deck.',
  },
  {
    id: 'wk-obfuscate', chapter: CH, concepts: POOL, band: 4,
    word: 'obfuscate', pos: 'verb', charge: 'neg',
    gloss: 'to make something deliberately unclear so it cannot be examined',
    answer: 'muddle',
    antonym: 'clarify',
    related: 'stall',
    decoy: 'irrigate',
    confusable: { word: 'obviate', meaning: 'prevent' },
    sentence: 'The answer was written to obfuscate rather than to explain.',
  },
  {
    id: 'wk-obscure', chapter: CH, concepts: POOL, band: 3,
    word: 'obscure', pos: 'verb', charge: 'neutral',
    gloss: 'to hide something from view or make it hard to make out',
    answer: 'conceal',
    antonym: 'reveal',
    related: 'shade',
    decoy: 'inflate',
    confusable: { word: 'observe', meaning: 'watch' },
    sentence: 'Fog obscured the far bank of the river until noon.',
  },
  {
    id: 'wk-obsolete', chapter: CH, concepts: POOL, band: 3,
    word: 'obsolete', pos: 'adj', charge: 'neutral',
    gloss: 'no longer in use because something better has replaced it',
    answer: 'outdated',
    antonym: 'current',
    related: 'antique',
    decoy: 'fibrous',
    confusable: { word: 'absolute', meaning: 'total' },
    sentence: 'The parts became obsolete two years after the line was launched.',
  },
  {
    id: 'wk-opine', chapter: CH, concepts: POOL, band: 4,
    word: 'opine', pos: 'verb', charge: 'neutral',
    gloss: 'to state an opinion, often more confidently than the knowledge warrants',
    answer: 'declare',
    antonym: 'withhold',
    related: 'suggest',
    decoy: 'chisel',
    confusable: { word: 'pine', meaning: 'yearn' },
    sentence: 'He opined at length on matters he knew nothing about.',
  },
  {
    id: 'wk-orotund', chapter: CH, concepts: POOL, band: 5,
    word: 'orotund', pos: 'adj', charge: 'neg',
    gloss: 'full and rounded in sound, and usually pompous with it',
    answer: 'pompous',
    antonym: 'plain',
    related: 'oratorical',
    decoy: 'frosted',
    confusable: { word: 'rotund', meaning: 'plump' },
    sentence: 'His orotund delivery made a short notice sound like a sermon.',
  },
  {
    id: 'wk-orthodox', chapter: CH, concepts: POOL, band: 3,
    word: 'orthodox', pos: 'adj', charge: 'neutral',
    gloss: 'following the accepted or traditional view',
    answer: 'conventional',
    antonym: 'heretical',
    related: 'religious',
    decoy: 'humid',
    confusable: { word: 'orthopedic', meaning: 'skeletal' },
    sentence: 'The orthodox view held for a century before anyone tested it.',
  },
  {
    id: 'wk-outstrip', chapter: CH, concepts: POOL, band: 3,
    word: 'outstrip', pos: 'verb', charge: 'neutral',
    gloss: 'to move ahead of or do better than something else',
    answer: 'exceed',
    antonym: 'trail',
    related: 'accelerate',
    decoy: 'marinate',
    confusable: { word: 'outstretch', meaning: 'extend' },
    sentence: 'Demand outstripped supply within a fortnight of the launch.',
  },
  {
    id: 'wk-overt', chapter: CH, concepts: POOL, band: 3,
    word: 'overt', pos: 'adj', charge: 'neutral',
    gloss: 'done openly, with no attempt to hide it',
    answer: 'open',
    antonym: 'hidden',
    related: 'exposed',
    decoy: 'salty',
    confusable: { word: 'inert', meaning: 'motionless' },
    sentence: 'There was no overt objection, but the room went quiet.',
  },
  {
    id: 'wk-overwrought', chapter: CH, concepts: POOL, band: 4,
    word: 'overwrought', pos: 'adj', charge: 'neg',
    gloss: 'in a state of nervous strain; worked up past the point of usefulness',
    answer: 'agitated',
    antonym: 'composed',
    related: 'exhausted',
    decoy: 'polished',
    confusable: { word: 'overworked', meaning: 'overburdened' },
    sentence: 'By the third day she was overwrought and sleeping badly.',
  },
  {
    id: 'wk-panoply', chapter: CH, concepts: POOL, band: 5,
    word: 'panoply', pos: 'noun', charge: 'neutral',
    gloss: 'a complete and impressive collection of things on display',
    answer: 'array',
    antonym: 'handful',
    related: 'armor',
    decoy: 'furnace',
    confusable: { word: 'panorama', meaning: 'vista' },
    sentence: 'The museum showed a full panoply of medieval weaponry and dress.',
  },
  {
    id: 'wk-parley', chapter: CH, concepts: POOL, band: 5,
    word: 'parley', pos: 'noun', charge: 'neutral',
    gloss: 'a discussion between opposing sides about terms',
    answer: 'negotiation',
    antonym: 'ultimatum',
    related: 'truce',
    decoy: 'embankment',
    confusable: { word: 'parlay', meaning: 'wager' },
    sentence: 'The two commanders met under a white flag for a parley.',
  },
  {
    id: 'wk-pedestrian', chapter: CH, concepts: POOL, band: 4,
    word: 'pedestrian', pos: 'adj', charge: 'neg',
    gloss: 'dull and lacking imagination',
    answer: 'unimaginative',
    antonym: 'inspired',
    related: 'walking',
    decoy: 'coastal',
    confusable: { word: 'pedantic', meaning: 'nitpicking' },
    sentence: 'The review called the score competent but pedestrian.',
  },
  {
    id: 'wk-pejorative', chapter: CH, concepts: POOL, band: 4,
    word: 'pejorative', pos: 'adj', charge: 'neg',
    gloss: 'expressing disapproval or contempt; belittling',
    answer: 'disparaging',
    antonym: 'complimentary',
    related: 'blunt',
    decoy: 'reversible',
    confusable: { word: 'perfunctory', meaning: 'halfhearted' },
    sentence: 'He used the word in a pejorative sense and everyone heard it.',
  },
  {
    id: 'wk-penitent', chapter: CH, concepts: POOL, band: 4,
    word: 'penitent', pos: 'adj', charge: 'pos',
    gloss: 'feeling and showing real regret for having done wrong',
    answer: 'remorseful',
    antonym: 'unrepentant',
    related: 'humble',
    decoy: 'angular',
    confusable: { word: 'pertinent', meaning: 'relevant' },
    sentence: 'He looked penitent enough, but the apology never came.',
  },
  {
    id: 'wk-peregrinate', chapter: CH, concepts: POOL, band: 5,
    word: 'peregrinate', pos: 'verb', charge: 'neutral',
    gloss: 'to travel from place to place, especially on foot and at length',
    answer: 'wander',
    antonym: 'settle',
    related: 'hike',
    decoy: 'laminate',
    confusable: { word: 'perpetuate', meaning: 'prolong' },
    sentence: 'They peregrinated across three continents over the course of a decade.',
  },
  {
    id: 'wk-phalanx', chapter: CH, concepts: POOL, band: 5,
    word: 'phalanx', pos: 'noun', charge: 'neutral',
    gloss: 'a compact body of people or things massed close together',
    answer: 'formation',
    antonym: 'scattering',
    related: 'shield',
    decoy: 'orchard',
    confusable: { word: 'phalanges', meaning: 'finger bones' },
    sentence: 'A phalanx of reporters blocked the entrance to the courthouse.',
  },
  {
    id: 'wk-picayune', chapter: CH, concepts: POOL, band: 5,
    word: 'picayune', pos: 'adj', charge: 'neg',
    gloss: 'petty and trivial; too small to be worth the fuss',
    answer: 'petty',
    antonym: 'weighty',
    related: 'fussy',
    decoy: 'auburn',
    confusable: { word: 'piquant', meaning: 'spicy' },
    sentence: 'The meeting bogged down in picayune objections about formatting.',
  },
  {
    id: 'wk-pith', chapter: CH, concepts: POOL, band: 4,
    word: 'pith', pos: 'noun', charge: 'neutral',
    gloss: 'the essential part of something; the heart of the matter',
    answer: 'essence',
    antonym: 'padding',
    related: 'rind',
    decoy: 'rafter',
    confusable: { word: 'pit', meaning: 'hollow' },
    sentence: 'Skip the introduction and give me the pith of the argument.',
  },
  {
    id: 'wk-plastic', chapter: CH, concepts: POOL, band: 3,
    word: 'plastic', pos: 'adj', charge: 'neutral',
    gloss: 'able to be shaped or moulded',
    answer: 'moldable',
    antonym: 'rigid',
    related: 'synthetic',
    decoy: 'nasal',
    confusable: { word: 'plastered', meaning: 'coated' },
    sentence: 'Clay stays plastic only while it holds enough water.',
  },
  {
    id: 'wk-pliant', chapter: CH, concepts: POOL, band: 4,
    word: 'pliant', pos: 'adj', charge: 'neutral',
    gloss: 'bending easily, whether the thing bending is a branch or a person',
    answer: 'yielding',
    antonym: 'stubborn',
    related: 'willowy',
    decoy: 'jagged',
    confusable: { word: 'reliant', meaning: 'dependent' },
    sentence: 'A pliant deputy signed whatever was put in front of him.',
  },
]);
