// Word pool, batch 04 - 32 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// Source tier: `data/wordCandidates.csv` at hardListHits >= 2. Alphabetical run "flippant"
// through "ineffable". See pool-03.js for the batch conventions and pool-zz-register.js for
// how these rows become templates.
//
// `heterogeneous` and `homogeneous` are deliberately both here and are each other's antonym
// option. That is the point rather than an oversight: they are a matched pair the test likes,
// and drilling one reinforces the other. Their remaining options share no strings, so no run
// can put two of the same slate on screen.
//
// Two rows carry a sense-shift rather than a rare spelling and are banded 3 accordingly:
// `fringe` (the margin, not the hair) and `hedge` (to avoid committing, not the shrub).
// `husband` and `graft` are the same trick at band 4 - both are everyday nouns whose tested
// senses are a verb of thrift and a noun of public corruption.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-flippant', chapter: CH, concepts: POOL, band: 4,
    word: 'flippant', pos: 'adj', charge: 'neg',
    gloss: 'treating a serious matter with inappropriate lightness',
    answer: 'glib',
    antonym: 'earnest',
    related: 'witty',
    decoy: 'brittle',
    confusable: { word: 'flagrant', meaning: 'blatant' },
    sentence: 'A flippant answer in the interview cost him the job.',
  },
  {
    id: 'wk-florid', chapter: CH, concepts: POOL, band: 4,
    word: 'florid', pos: 'adj', charge: 'neg',
    gloss: 'excessively decorated or elaborate in style',
    answer: 'ornate',
    antonym: 'plain',
    related: 'flushed',
    decoy: 'punctual',
    confusable: { word: 'torrid', meaning: 'scorching' },
    sentence: 'His florid prose buried the argument under decoration.',
  },
  {
    id: 'wk-fringe', chapter: CH, concepts: POOL, band: 3,
    word: 'fringe', pos: 'noun', charge: 'neutral',
    gloss: 'the outer edge or margin of an area, group or activity',
    answer: 'margin',
    antonym: 'center',
    related: 'tassel',
    decoy: 'anthem',
    confusable: { word: 'infringe', meaning: 'trespass' },
    sentence: 'The camp sat on the fringe of the forest, well away from the road.',
  },
  {
    id: 'wk-frivolous', chapter: CH, concepts: POOL, band: 3,
    word: 'frivolous', pos: 'adj', charge: 'neg',
    gloss: 'having no serious purpose or value; not worth taking seriously',
    answer: 'trivial',
    antonym: 'serious',
    related: 'playful',
    decoy: 'magnetic',
    confusable: { word: 'frugal', meaning: 'thrifty' },
    sentence: 'The judge dismissed the frivolous claim within minutes.',
  },
  {
    id: 'wk-gaffe', chapter: CH, concepts: POOL, band: 4,
    word: 'gaffe', pos: 'noun', charge: 'neg',
    gloss: 'an embarrassing blunder, especially a social one',
    answer: 'blunder',
    antonym: 'triumph',
    related: 'apology',
    decoy: 'harvest',
    confusable: { word: 'gaff', meaning: 'hook' },
    sentence: 'One gaffe at the press conference dominated the week of coverage.',
  },
  {
    id: 'wk-gambol', chapter: CH, concepts: POOL, band: 5,
    word: 'gambol', pos: 'verb', charge: 'pos',
    gloss: 'to run and skip about playfully',
    answer: 'frolic',
    antonym: 'trudge',
    related: 'graze',
    decoy: 'weld',
    confusable: { word: 'gamble', meaning: 'wager' },
    sentence: 'Lambs gamboled across the field the moment the gate opened.',
  },
  {
    id: 'wk-gauche', chapter: CH, concepts: POOL, band: 4,
    word: 'gauche', pos: 'adj', charge: 'neg',
    gloss: 'socially awkward; lacking grace or tact',
    answer: 'tactless',
    antonym: 'suave',
    related: 'shy',
    decoy: 'porous',
    confusable: { word: 'gaunt', meaning: 'haggard' },
    sentence: 'His gauche remark about her salary silenced the table.',
  },
  {
    id: 'wk-gawky', chapter: CH, concepts: POOL, band: 4,
    word: 'gawky', pos: 'adj', charge: 'neg',
    gloss: 'awkward and ungainly in movement, often from being tall and thin',
    answer: 'clumsy',
    antonym: 'graceful',
    related: 'lanky',
    decoy: 'fireproof',
    confusable: { word: 'gaudy', meaning: 'garish' },
    sentence: 'A gawky teenager knocked over two chairs getting to his seat.',
  },
  {
    id: 'wk-germane', chapter: CH, concepts: POOL, band: 4,
    word: 'germane', pos: 'adj', charge: 'neutral',
    gloss: 'genuinely relevant to the matter under discussion',
    answer: 'relevant',
    antonym: 'extraneous',
    related: 'timely',
    decoy: 'molten',
    confusable: { word: 'German', meaning: 'Teutonic' },
    sentence: 'Only two of his objections were germane to the actual proposal.',
  },
  {
    id: 'wk-gradation', chapter: CH, concepts: POOL, band: 4,
    word: 'gradation', pos: 'noun', charge: 'neutral',
    gloss: 'a gradual change through a scale, or one step within it',
    answer: 'progression',
    antonym: 'uniformity',
    related: 'spectrum',
    decoy: 'quarantine',
    confusable: { word: 'graduation', meaning: 'commencement' },
    sentence: 'The painting moves through a fine gradation from blue to grey.',
  },
  {
    id: 'wk-graft', chapter: CH, concepts: POOL, band: 4,
    word: 'graft', pos: 'noun', charge: 'neg',
    gloss: 'corrupt personal gain taken through a position of public trust',
    answer: 'corruption',
    antonym: 'integrity',
    related: 'patronage',
    decoy: 'migration',
    confusable: { word: 'draft', meaning: 'conscription' },
    sentence: 'An inquiry into graft brought down two city commissioners.',
  },
  {
    id: 'wk-gratuitous', chapter: CH, concepts: POOL, band: 4,
    word: 'gratuitous', pos: 'adj', charge: 'neg',
    gloss: 'uncalled for; done without good reason or justification',
    answer: 'unwarranted',
    antonym: 'necessary',
    related: 'free',
    decoy: 'crystalline',
    confusable: { word: 'gratifying', meaning: 'pleasing' },
    sentence: 'The film was criticised for gratuitous violence that added nothing.',
  },
  {
    id: 'wk-grievous', chapter: CH, concepts: POOL, band: 4,
    word: 'grievous', pos: 'adj', charge: 'neg',
    gloss: 'very severe; causing great harm or suffering',
    answer: 'severe',
    antonym: 'trivial',
    related: 'painful',
    decoy: 'adhesive',
    confusable: { word: 'grieving', meaning: 'sorrowful' },
    sentence: 'The report described a grievous failure of supervision.',
  },
  {
    id: 'wk-guile', chapter: CH, concepts: POOL, band: 4,
    word: 'guile', pos: 'noun', charge: 'neg',
    gloss: 'sly cleverness used to deceive people',
    answer: 'cunning',
    antonym: 'honesty',
    related: 'stealth',
    decoy: 'altitude',
    confusable: { word: 'guilt', meaning: 'culpability' },
    sentence: 'He won the contract through guile rather than merit.',
  },
  {
    id: 'wk-hedge', chapter: CH, concepts: POOL, band: 3,
    word: 'hedge', pos: 'verb', charge: 'neutral',
    gloss: 'to avoid committing yourself, so as to limit your risk',
    answer: 'equivocate',
    antonym: 'commit',
    related: 'insure',
    decoy: 'illuminate',
    confusable: { word: 'hinge', meaning: 'depend' },
    sentence: 'Asked directly, the minister hedged and changed the subject.',
  },
  {
    id: 'wk-hedonist', chapter: CH, concepts: POOL, band: 4,
    word: 'hedonist', pos: 'noun', charge: 'neutral',
    gloss: 'a person who treats pleasure as the highest good',
    answer: 'pleasure-seeker',
    antonym: 'ascetic',
    related: 'glutton',
    decoy: 'cartographer',
    confusable: { word: 'humanist', meaning: 'freethinker' },
    sentence: 'He lived like a hedonist for a decade and then took vows.',
  },
  {
    id: 'wk-hermetic', chapter: CH, concepts: POOL, band: 5,
    word: 'hermetic', pos: 'adj', charge: 'neutral',
    gloss: 'completely sealed against air, or sealed off from outside influence',
    answer: 'airtight',
    antonym: 'porous',
    related: 'mystical',
    decoy: 'melodic',
    confusable: { word: 'hermitic', meaning: 'reclusive' },
    sentence: 'The samples are stored in hermetic containers to keep out moisture.',
  },
  {
    id: 'wk-heterogeneous', chapter: CH, concepts: POOL, band: 4,
    word: 'heterogeneous', pos: 'adj', charge: 'neutral',
    gloss: 'made up of parts that are unlike one another',
    answer: 'varied',
    antonym: 'uniform',
    related: 'layered',
    decoy: 'buoyant',
    confusable: { word: 'heterodox', meaning: 'unorthodox' },
    sentence: 'The class was heterogeneous, drawn from six different countries.',
  },
  {
    id: 'wk-homogeneous', chapter: CH, concepts: POOL, band: 4,
    word: 'homogeneous', pos: 'adj', charge: 'neutral',
    gloss: 'the same in composition all the way through',
    answer: 'uniform',
    antonym: 'varied',
    related: 'pasteurized',
    decoy: 'strident',
    confusable: { word: 'homologous', meaning: 'corresponding' },
    sentence: 'Stir until the mixture is completely homogeneous.',
  },
  {
    id: 'wk-husband', chapter: CH, concepts: POOL, band: 4,
    word: 'husband', pos: 'verb', charge: 'pos',
    gloss: 'to use a resource sparingly so that it lasts',
    answer: 'conserve',
    antonym: 'squander',
    related: 'cultivate',
    decoy: 'polish',
    confusable: { word: 'husbandry', meaning: 'farm' },
    sentence: 'They husbanded their fuel carefully through the long winter.',
  },
  {
    id: 'wk-idolatry', chapter: CH, concepts: POOL, band: 4,
    word: 'idolatry', pos: 'noun', charge: 'neg',
    gloss: 'blind or excessive admiration of someone or something',
    answer: 'worship',
    antonym: 'contempt',
    related: 'ritual',
    decoy: 'plumbing',
    confusable: { word: 'adultery', meaning: 'infidelity' },
    sentence: "The crowd's idolatry of the coach survived three losing seasons.",
  },
  {
    id: 'wk-imbroglio', chapter: CH, concepts: POOL, band: 5,
    word: 'imbroglio', pos: 'noun', charge: 'neg',
    gloss: 'a confused and embarrassing tangle of a situation',
    answer: 'entanglement',
    antonym: 'settlement',
    related: 'scandal',
    decoy: 'appliance',
    confusable: { word: 'embargo', meaning: 'ban' },
    sentence: 'The leaked memo turned a small disagreement into a full imbroglio.',
  },
  {
    id: 'wk-imbue', chapter: CH, concepts: POOL, band: 5,
    word: 'imbue', pos: 'verb', charge: 'neutral',
    gloss: 'to fill something thoroughly with a quality or feeling',
    answer: 'permeate',
    antonym: 'drain',
    related: 'dye',
    decoy: 'tabulate',
    confusable: { word: 'imbibe', meaning: 'drink' },
    sentence: 'Her teaching imbued the whole department with a new seriousness.',
  },
  {
    id: 'wk-impasse', chapter: CH, concepts: POOL, band: 4,
    word: 'impasse', pos: 'noun', charge: 'neg',
    gloss: 'a position from which no further progress is possible',
    answer: 'deadlock',
    antonym: 'breakthrough',
    related: 'negotiation',
    decoy: 'overture',
    confusable: { word: 'impact', meaning: 'collision' },
    sentence: 'Talks reached an impasse over the question of pensions.',
  },
  {
    id: 'wk-impious', chapter: CH, concepts: POOL, band: 5,
    word: 'impious', pos: 'adj', charge: 'neg',
    gloss: 'showing no reverence for what others hold sacred',
    answer: 'irreverent',
    antonym: 'devout',
    related: 'rebellious',
    decoy: 'seaworthy',
    confusable: { word: 'impish', meaning: 'mischievous' },
    sentence: 'The bishop called the pamphlet impious and demanded it be withdrawn.',
  },
  {
    id: 'wk-implode', chapter: CH, concepts: POOL, band: 3,
    word: 'implode', pos: 'verb', charge: 'neutral',
    gloss: 'to collapse violently inward',
    answer: 'collapse',
    antonym: 'expand',
    related: 'shatter',
    decoy: 'germinate',
    confusable: { word: 'explode', meaning: 'burst' },
    sentence: 'The old cooling tower was made to implode in under ten seconds.',
  },
  {
    id: 'wk-imprecation', chapter: CH, concepts: POOL, band: 5,
    word: 'imprecation', pos: 'noun', charge: 'neg',
    gloss: 'a spoken curse calling down harm on someone',
    answer: 'curse',
    antonym: 'blessing',
    related: 'insult',
    decoy: 'canopy',
    confusable: { word: 'imprecision', meaning: 'vagueness' },
    sentence: 'He muttered an imprecation and slammed the door behind him.',
  },
  {
    id: 'wk-incarnadine', chapter: CH, concepts: POOL, band: 5,
    word: 'incarnadine', pos: 'adj', charge: 'neutral',
    gloss: 'blood-red in colour',
    answer: 'crimson',
    antonym: 'colorless',
    related: 'fleshy',
    decoy: 'gaseous',
    confusable: { word: 'incarnate', meaning: 'embodied' },
    sentence: 'The incarnadine glow of the sunset filled the whole window.',
  },
  {
    id: 'wk-incendiary', chapter: CH, concepts: POOL, band: 4,
    word: 'incendiary', pos: 'adj', charge: 'neg',
    gloss: 'designed to start a fire, or to stir up conflict',
    answer: 'inflammatory',
    antonym: 'soothing',
    related: 'explosive',
    decoy: 'hereditary',
    confusable: { word: 'incidental', meaning: 'minor' },
    sentence: 'His incendiary speech turned an orderly protest into a riot.',
  },
  {
    id: 'wk-incongruous', chapter: CH, concepts: POOL, band: 4,
    word: 'incongruous', pos: 'adj', charge: 'neg',
    gloss: 'out of place; not in keeping with its surroundings',
    answer: 'mismatched',
    antonym: 'fitting',
    related: 'peculiar',
    decoy: 'cylindrical',
    confusable: { word: 'incongruent', meaning: 'unequal' },
    sentence: 'A neon sign looked incongruous on the front of the old chapel.',
  },
  {
    id: 'wk-indigence', chapter: CH, concepts: POOL, band: 5,
    word: 'indigence', pos: 'noun', charge: 'neg',
    gloss: 'extreme poverty',
    answer: 'poverty',
    antonym: 'affluence',
    related: 'hardship',
    decoy: 'foliage',
    confusable: { word: 'indulgence', meaning: 'leniency' },
    sentence: 'He died in indigence despite having once owned three mills.',
  },
  {
    id: 'wk-ineffable', chapter: CH, concepts: POOL, band: 5,
    word: 'ineffable', pos: 'adj', charge: 'neutral',
    gloss: 'too great or extreme to be put into words',
    answer: 'indescribable',
    antonym: 'commonplace',
    related: 'sacred',
    decoy: 'collapsible',
    confusable: { word: 'ineffectual', meaning: 'useless' },
    sentence: 'She described the view as ineffable and then said nothing more.',
  },
]);
