// Word pool, batch 01 - 50 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// This is NOT a curriculum chapter. There is no lesson here and none of these words teach a
// concept - they exist purely to make WK drills stop repeating (see the CLAUDE.md pool note and
// pool-zz-register.js, which is the file that actually turns this registry into templates).
//
// Band is judged honestly per word, not mechanically: `appropriate`, `base`, `betray`, `wary`,
// `abound`, `lavish`, `profound` and `bogus` are ordinary words being tested in a less ordinary
// sense, so they sit at band 3 even though several of their neighbours in this batch are band 5.
//
// A handful of confusable pairs lean on genuine near-spellings the way the taught chapters do
// (bridle/bridal, callow/callous, boor/boar, auspicious/suspicious, bifurcate/obfuscate,
// circumscribe/circumvent) rather than inventing a pairing - these are the mix-ups a real
// candidate actually makes.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-elicit', chapter: CH, concepts: POOL, band: 4,
    word: 'elicit', pos: 'verb', charge: 'neutral',
    gloss: 'to draw out a response, answer, or reaction from someone',
    answer: 'extract',
    antonym: 'suppress',
    related: 'interview',
    decoy: 'alarm',
    confusable: { word: 'elide', meaning: 'omit' },
    sentence: "The detective's clever questioning managed to elicit a confession from the suspect.",
  },
  {
    id: 'wk-impervious', chapter: CH, concepts: POOL, band: 4,
    word: 'impervious', pos: 'adj', charge: 'neutral',
    gloss: 'not able to be affected or damaged by something; incapable of being penetrated',
    answer: 'resistant',
    antonym: 'vulnerable',
    related: 'sturdy',
    decoy: 'cheerful',
    confusable: { word: 'imperious', meaning: 'domineering' },
    sentence: 'The old fortress walls were impervious to cannon fire.',
  },
  {
    id: 'wk-nadir', chapter: CH, concepts: POOL, band: 4,
    word: 'nadir', pos: 'noun', charge: 'neg',
    gloss: 'the lowest or most unsuccessful point of something',
    answer: 'bottom',
    antonym: 'peak',
    related: 'decline',
    decoy: 'trumpet',
    confusable: { word: 'cadre', meaning: 'group' },
    sentence: 'Losing the championship game was the nadir of his athletic career.',
  },
  {
    id: 'wk-anachronistic', chapter: CH, concepts: POOL, band: 5,
    word: 'anachronistic', pos: 'adj', charge: 'neutral',
    gloss: 'belonging to a period other than the one being portrayed or referred to; out of its proper time',
    answer: 'outdated',
    antonym: 'timely',
    related: 'historic',
    decoy: 'melodic',
    confusable: { word: 'anarchistic', meaning: 'rebellious' },
    sentence: "The knight's use of a wristwatch felt jarringly anachronistic in the film.",
  },
  {
    id: 'wk-appropriate', chapter: CH, concepts: POOL, band: 3,
    word: 'appropriate', pos: 'verb', charge: 'neg',
    gloss: "to take something for one's own use, typically without permission",
    answer: 'seize',
    antonym: 'surrender',
    related: 'borrow',
    decoy: 'illuminate',
    confusable: { word: 'appreciate', meaning: 'value' },
    sentence: "The general appropriated the villagers' grain stores without compensation.",
  },
  {
    id: 'wk-base', chapter: CH, concepts: POOL, band: 3,
    word: 'base', pos: 'adj', charge: 'neg',
    gloss: 'lacking moral principles; dishonorable or contemptible',
    answer: 'sordid',
    antonym: 'noble',
    related: 'crude',
    decoy: 'tropical',
    confusable: { word: 'bass', meaning: 'low-pitched' },
    sentence: 'His base attempt to bribe the officer disgusted everyone present.',
  },
  {
    id: 'wk-confound', chapter: CH, concepts: POOL, band: 4,
    word: 'confound', pos: 'verb', charge: 'neg',
    gloss: 'to cause someone to feel confused or perplexed; to fail to distinguish from another',
    answer: 'perplex',
    antonym: 'clarify',
    related: 'contradict',
    decoy: 'polish',
    confusable: { word: 'confront', meaning: 'face' },
    sentence: "The tax form's contradictory instructions would confound even an accountant.",
  },
  {
    id: 'wk-demur', chapter: CH, concepts: POOL, band: 5,
    word: 'demur', pos: 'verb', charge: 'neg',
    gloss: 'to raise doubts or objections; to show reluctance',
    answer: 'object',
    antonym: 'agree',
    related: 'refuse',
    decoy: 'sparkle',
    confusable: { word: 'demote', meaning: 'downgrade' },
    sentence: 'She would demur whenever asked to take credit for the project.',
  },
  {
    id: 'wk-dubious', chapter: CH, concepts: POOL, band: 4,
    word: 'dubious', pos: 'adj', charge: 'neg',
    gloss: 'not to be relied upon; open to doubt or suspicion',
    answer: 'doubtful',
    antonym: 'certain',
    related: 'ambiguous',
    decoy: 'rectangular',
    confusable: { word: 'dubbed', meaning: 'named' },
    sentence: "The company's claims about the product's safety seemed dubious at best.",
  },
  {
    id: 'wk-equitable', chapter: CH, concepts: POOL, band: 4,
    word: 'equitable', pos: 'adj', charge: 'pos',
    gloss: 'fair and impartial; dealing equally with all concerned',
    answer: 'fair',
    antonym: 'unjust',
    related: 'legal',
    decoy: 'musical',
    confusable: { word: 'equestrian', meaning: 'riding' },
    sentence: 'The judge sought an equitable division of the estate between both children.',
  },
  {
    id: 'wk-ersatz', chapter: CH, concepts: POOL, band: 5,
    word: 'ersatz', pos: 'adj', charge: 'neg',
    gloss: 'made or used as a substitute, typically an inferior one; artificial',
    answer: 'fake',
    antonym: 'genuine',
    related: 'cheap',
    decoy: 'nautical',
    confusable: { word: 'quartz', meaning: 'crystalline' },
    sentence: 'Wartime rationing meant most families drank an ersatz coffee made from roasted grain.',
  },
  {
    id: 'wk-lavish', chapter: CH, concepts: POOL, band: 3,
    word: 'lavish', pos: 'adj', charge: 'neutral',
    gloss: 'sumptuously rich, elaborate, or luxurious',
    answer: 'extravagant',
    antonym: 'meager',
    related: 'formal',
    decoy: 'silent',
    confusable: { word: 'ravish', meaning: 'enchanting' },
    sentence: 'The hotel offered a lavish breakfast spread every morning of the conference.',
  },
  {
    id: 'wk-profound', chapter: CH, concepts: POOL, band: 3,
    word: 'profound', pos: 'adj', charge: 'pos',
    gloss: 'having great depth of knowledge, understanding, or feeling; not superficial',
    answer: 'deep',
    antonym: 'superficial',
    related: 'complex',
    decoy: 'colorful',
    confusable: { word: 'profuse', meaning: 'abundant' },
    sentence: "The professor's remark had a profound effect on how she viewed her career.",
  },
  {
    id: 'wk-transgression', chapter: CH, concepts: POOL, band: 4,
    word: 'transgression', pos: 'noun', charge: 'neg',
    gloss: 'an act that violates a law, rule, or code of conduct; a sin or offense',
    answer: 'violation',
    antonym: 'compliance',
    related: 'punishment',
    decoy: 'harmony',
    confusable: { word: 'transition', meaning: 'change' },
    sentence: 'Lying to his commanding officer was the transgression that ended his career.',
  },
  {
    id: 'wk-truculence', chapter: CH, concepts: POOL, band: 5,
    word: 'truculence', pos: 'noun', charge: 'neg',
    gloss: 'eagerness or readiness to argue, fight, or be aggressively defiant',
    answer: 'belligerence',
    antonym: 'meekness',
    related: 'stubbornness',
    decoy: 'astronomy',
    confusable: { word: 'opulence', meaning: 'wealth' },
    sentence: "The prisoner's truculence made every interrogation session tense.",
  },
  {
    id: 'wk-wary', chapter: CH, concepts: POOL, band: 3,
    word: 'wary', pos: 'adj', charge: 'neutral',
    gloss: 'feeling or showing caution about possible dangers, problems, or risks',
    answer: 'cautious',
    antonym: 'careless',
    related: 'nervous',
    decoy: 'musical',
    confusable: { word: 'weary', meaning: 'tired' },
    sentence: 'He was wary of strangers offering unsolicited investment advice.',
  },
  {
    id: 'wk-abhor', chapter: CH, concepts: POOL, band: 4,
    word: 'abhor', pos: 'verb', charge: 'neg',
    gloss: 'to regard with disgust and hatred; to detest',
    answer: 'detest',
    antonym: 'adore',
    related: 'avoid',
    decoy: 'polish',
    confusable: { word: 'abort', meaning: 'cancel' },
    sentence: 'Most soldiers abhor unnecessary cruelty, even toward an enemy.',
  },
  {
    id: 'wk-abound', chapter: CH, concepts: POOL, band: 3,
    word: 'abound', pos: 'verb', charge: 'neutral',
    gloss: 'to exist in large numbers or amounts; to be rich in something',
    answer: 'teem',
    antonym: 'lack',
    related: 'grow',
    decoy: 'whisper',
    confusable: { word: 'astound', meaning: 'amaze' },
    sentence: 'Rumors abound about who will be selected for the assignment.',
  },
  {
    id: 'wk-abreast', chapter: CH, concepts: POOL, band: 4,
    word: 'abreast', pos: 'adv', charge: 'neutral',
    gloss: 'side by side and facing the same way; level with something',
    answer: 'alongside',
    antonym: 'behind',
    related: 'together',
    decoy: 'loudly',
    confusable: { word: 'abreact', meaning: 'release' },
    sentence: 'The two pilots walked abreast down the flight line, discussing the mission brief.',
  },
  {
    id: 'wk-abstruse', chapter: CH, concepts: POOL, band: 5,
    word: 'abstruse', pos: 'adj', charge: 'neutral',
    gloss: 'difficult to understand; deliberately obscure',
    answer: 'obscure',
    antonym: 'clear',
    related: 'complicated',
    decoy: 'aquatic',
    confusable: { word: 'abstract', meaning: 'theoretical' },
    sentence: "The professor's abstruse lecture on measure theory lost most of the class within minutes.",
  },
  {
    id: 'wk-accretion', chapter: CH, concepts: POOL, band: 5,
    word: 'accretion', pos: 'noun', charge: 'neutral',
    gloss: 'gradual growth or increase by the accumulation of matter or layers over time',
    answer: 'buildup',
    antonym: 'erosion',
    related: 'expansion',
    decoy: 'symphony',
    confusable: { word: 'excretion', meaning: 'waste' },
    sentence: "Over centuries, an accretion of silt slowly formed the delta at the river's mouth.",
  },
  {
    id: 'wk-acidulous', chapter: CH, concepts: POOL, band: 5,
    word: 'acidulous', pos: 'adj', charge: 'neg',
    gloss: 'sharply critical or sour in manner or speech',
    answer: 'caustic',
    antonym: 'sweet',
    related: 'witty',
    decoy: 'melodic',
    confusable: { word: 'assiduous', meaning: 'diligent' },
    sentence: 'Her acidulous remarks about the new policy left no doubt about her opinion.',
  },
  {
    id: 'wk-adroit', chapter: CH, concepts: POOL, band: 4,
    word: 'adroit', pos: 'adj', charge: 'pos',
    gloss: 'clever or skillful, especially in physical or mental activity',
    answer: 'skillful',
    antonym: 'clumsy',
    related: 'intelligent',
    decoy: 'humid',
    confusable: { word: 'adrift', meaning: 'drifting' },
    sentence: "The negotiator's adroit handling of the hostile question defused the whole room.",
  },
  {
    id: 'wk-aerie', chapter: CH, concepts: POOL, band: 5,
    word: 'aerie', pos: 'noun', charge: 'neutral',
    gloss: 'a nest of a bird of prey built high up, or a dwelling built high on a cliff or ridge',
    answer: 'nest',
    antonym: 'burrow',
    related: 'perch',
    decoy: 'engine',
    confusable: { word: 'aerial', meaning: 'antenna' },
    sentence: "The eagle's aerie clung to a ledge halfway up the cliff face.",
  },
  {
    id: 'wk-alienate', chapter: CH, concepts: POOL, band: 4,
    word: 'alienate', pos: 'verb', charge: 'neg',
    gloss: 'to cause someone to feel isolated or estranged; to make unfriendly or hostile',
    answer: 'estrange',
    antonym: 'unite',
    related: 'offend',
    decoy: 'whistle',
    confusable: { word: 'alleviate', meaning: 'relieve' },
    sentence: 'His harsh criticism only served to alienate the very allies he needed.',
  },
  {
    id: 'wk-aloof', chapter: CH, concepts: POOL, band: 4,
    word: 'aloof', pos: 'adj', charge: 'neg',
    gloss: 'not friendly or forthcoming; cool and distant in manner',
    answer: 'distant',
    antonym: 'friendly',
    related: 'shy',
    decoy: 'spicy',
    confusable: { word: 'aloft', meaning: 'airborne' },
    sentence: 'The new captain remained aloof from the enlisted crew for the entire deployment.',
  },
  {
    id: 'wk-ambivalent', chapter: CH, concepts: POOL, band: 4,
    word: 'ambivalent', pos: 'adj', charge: 'neutral',
    gloss: 'having mixed or contradictory feelings about someone or something',
    answer: 'conflicted',
    antonym: 'decisive',
    related: 'indifferent',
    decoy: 'granular',
    confusable: { word: 'ambient', meaning: 'surrounding' },
    sentence: 'She felt ambivalent about the promotion, excited yet reluctant to leave her old squadron.',
  },
  {
    id: 'wk-anoint', chapter: CH, concepts: POOL, band: 4,
    word: 'anoint', pos: 'verb', charge: 'neutral',
    gloss: 'to formally consecrate someone with oil, or to designate someone as chosen',
    answer: 'consecrate',
    antonym: 'reject',
    related: 'crown',
    decoy: 'wander',
    confusable: { word: 'anneal', meaning: 'harden' },
    sentence: 'The high priest would anoint each new king with sacred oil during the coronation.',
  },
  {
    id: 'wk-antagonize', chapter: CH, concepts: POOL, band: 4,
    word: 'antagonize', pos: 'verb', charge: 'neg',
    gloss: 'to cause someone to become hostile or angry, especially through provocative behavior',
    answer: 'provoke',
    antonym: 'appease',
    related: 'criticize',
    decoy: 'illustrate',
    confusable: { word: 'antiquate', meaning: 'outdate' },
    sentence: 'His sarcastic remarks in the meeting only served to antagonize the whole engineering team.',
  },
  {
    id: 'wk-apogee', chapter: CH, concepts: POOL, band: 5,
    word: 'apogee', pos: 'noun', charge: 'pos',
    gloss: 'the highest point of achievement or development',
    answer: 'peak',
    antonym: 'nadir',
    related: 'orbit',
    decoy: 'furnace',
    confusable: { word: 'apostle', meaning: 'messenger' },
    sentence: 'Winning the championship was the apogee of her long coaching career.',
  },
  {
    id: 'wk-auspicious', chapter: CH, concepts: POOL, band: 4,
    word: 'auspicious', pos: 'adj', charge: 'pos',
    gloss: 'conducive to success; showing signs of a favorable future',
    answer: 'favorable',
    antonym: 'ominous',
    related: 'timely',
    decoy: 'metallic',
    confusable: { word: 'suspicious', meaning: 'distrustful' },
    sentence: 'The clear skies on launch morning seemed auspicious for the mission.',
  },
  {
    id: 'wk-bereft', chapter: CH, concepts: POOL, band: 4,
    word: 'bereft', pos: 'adj', charge: 'neg',
    gloss: 'deprived of or lacking something, especially through loss',
    answer: 'deprived',
    antonym: 'abundant',
    related: 'grieving',
    decoy: 'circular',
    confusable: { word: 'berserk', meaning: 'frenzied' },
    sentence: 'She felt utterly bereft after the loss of her closest friend.',
  },
  {
    id: 'wk-betray', chapter: CH, concepts: POOL, band: 3,
    word: 'betray', pos: 'verb', charge: 'neg',
    gloss: 'to be disloyal to someone who trusts you, especially by aiding an opponent',
    answer: 'double-cross',
    antonym: 'protect',
    related: 'abandon',
    decoy: 'juggle',
    confusable: { word: 'betroth', meaning: 'engage' },
    sentence: "He would never betray a friend's confidence, no matter the pressure.",
  },
  {
    id: 'wk-bevy', chapter: CH, concepts: POOL, band: 4,
    word: 'bevy', pos: 'noun', charge: 'neutral',
    gloss: 'a large group of people or things',
    answer: 'group',
    antonym: 'individual',
    related: 'litter',
    decoy: 'volcano',
    confusable: { word: 'levy', meaning: 'tax' },
    sentence: 'A bevy of reporters gathered outside the courthouse before the verdict.',
  },
  {
    id: 'wk-bifurcate', chapter: CH, concepts: POOL, band: 5,
    word: 'bifurcate', pos: 'verb', charge: 'neutral',
    gloss: 'to divide into two branches or parts',
    answer: 'split',
    antonym: 'merge',
    related: 'diverge',
    decoy: 'garnish',
    confusable: { word: 'obfuscate', meaning: 'confuse' },
    sentence: 'The trail begins to bifurcate about two miles past the ranger station.',
  },
  {
    id: 'wk-bilk', chapter: CH, concepts: POOL, band: 5,
    word: 'bilk', pos: 'verb', charge: 'neg',
    gloss: 'to obtain money from someone by fraud or deceit; to cheat',
    answer: 'swindle',
    antonym: 'reimburse',
    related: 'gamble',
    decoy: 'garden',
    confusable: { word: 'balk', meaning: 'refuse' },
    sentence: 'The con artist managed to bilk dozens of retirees out of their savings.',
  },
  {
    id: 'wk-blight', chapter: CH, concepts: POOL, band: 4,
    word: 'blight', pos: 'noun', charge: 'neg',
    gloss: 'something that damages, harms, or spoils, especially across a wide area',
    answer: 'scourge',
    antonym: 'boon',
    // NOT 'disease'. Blight genuinely IS a plant disease, so it sat beside `scourge` as a second
    // defensible answer. Rewriting the gloss to drop the disease sense did not fix it: the gloss
    // is never shown during the question (see the note in CONTRIBUTING-QUESTIONS.md rule 7).
    related: 'weed',
    decoy: 'ballet',
    confusable: { word: 'flight', meaning: 'journey' },
    sentence: 'Corruption had become a blight on the entire local government.',
  },
  {
    id: 'wk-bogus', chapter: CH, concepts: POOL, band: 3,
    word: 'bogus', pos: 'adj', charge: 'neg',
    gloss: 'not genuine or real; fake, fraudulent',
    answer: 'phony',
    antonym: 'authentic',
    related: 'illegal',
    decoy: 'operatic',
    confusable: { word: 'bogged', meaning: 'stuck' },
    sentence: "The salesman's claims about a guaranteed return turned out to be entirely bogus.",
  },
  {
    id: 'wk-bonhomie', chapter: CH, concepts: POOL, band: 5,
    word: 'bonhomie', pos: 'noun', charge: 'pos',
    gloss: 'cheerful friendliness; a genial, good-natured manner',
    answer: 'geniality',
    antonym: 'hostility',
    related: 'humor',
    decoy: 'telescope',
    confusable: { word: 'bonanza', meaning: 'windfall' },
    sentence: 'The reunion was full of bonhomie, old rivalries forgotten over drinks.',
  },
  {
    id: 'wk-boor', chapter: CH, concepts: POOL, band: 4,
    word: 'boor', pos: 'noun', charge: 'neg',
    gloss: 'a rude, ill-mannered, or insensitive person',
    answer: 'lout',
    antonym: 'gentleman',
    related: 'tyrant',
    decoy: 'pancake',
    confusable: { word: 'boar', meaning: 'pig' },
    sentence: 'He acted like a boor at the dinner, interrupting every toast.',
  },
  {
    id: 'wk-brazen', chapter: CH, concepts: POOL, band: 4,
    word: 'brazen', pos: 'adj', charge: 'neg',
    gloss: 'bold and without shame or embarrassment; shamelessly defiant',
    answer: 'shameless',
    antonym: 'timid',
    related: 'confident',
    decoy: 'lunar',
    confusable: { word: 'frozen', meaning: 'chilled' },
    sentence: 'It was a brazen attempt to cheat, done right in front of the proctor.',
  },
  {
    id: 'wk-bridle', chapter: CH, concepts: POOL, band: 5,
    word: 'bridle', pos: 'verb', charge: 'neg',
    gloss: 'to react with anger or indignation, often by drawing back sharply',
    answer: 'bristle',
    antonym: 'relax',
    related: 'protest',
    decoy: 'sprinkle',
    confusable: { word: 'bridal', meaning: 'wed' },
    sentence: 'She would bridle at any suggestion that her report contained errors.',
  },
  {
    id: 'wk-bromide', chapter: CH, concepts: POOL, band: 5,
    word: 'bromide', pos: 'noun', charge: 'neg',
    gloss: 'a trite, unoriginal remark offered as if it were wise or novel',
    answer: 'platitude',
    antonym: 'insight',
    related: 'proverb',
    decoy: 'compass',
    confusable: { word: 'bromine', meaning: 'element' },
    sentence: 'His speech was full of the usual bromides about teamwork and dedication.',
  },
  {
    id: 'wk-cacophonous', chapter: CH, concepts: POOL, band: 4,
    word: 'cacophonous', pos: 'adj', charge: 'neg',
    gloss: 'harsh-sounding; full of discordant, unpleasant noise',
    answer: 'discordant',
    antonym: 'melodious',
    related: 'loud',
    decoy: 'edible',
    confusable: { word: 'carnivorous', meaning: 'meat-eating' },
    sentence: 'The engine room was a cacophonous mess of grinding gears and alarms.',
  },
  {
    id: 'wk-callow', chapter: CH, concepts: POOL, band: 4,
    word: 'callow', pos: 'adj', charge: 'neg',
    gloss: 'inexperienced and immature, especially due to youth',
    answer: 'immature',
    antonym: 'seasoned',
    related: 'young',
    decoy: 'porous',
    confusable: { word: 'callous', meaning: 'unfeeling' },
    sentence: 'The callow recruit had no idea how unprepared he was for combat.',
  },
  {
    id: 'wk-canonize', chapter: CH, concepts: POOL, band: 5,
    word: 'canonize', pos: 'verb', charge: 'neutral',
    gloss: 'to officially declare someone a saint, or to treat something as beyond criticism',
    answer: 'sanctify',
    antonym: 'condemn',
    related: 'honor',
    decoy: 'yodel',
    confusable: { word: 'cannonade', meaning: 'bombard' },
    sentence: 'Decades later, historians still debate whether to canonize his economic reforms as visionary.',
  },
  {
    id: 'wk-cataclysm', chapter: CH, concepts: POOL, band: 4,
    word: 'cataclysm', pos: 'noun', charge: 'neg',
    gloss: 'a large-scale, violent event causing great damage or upheaval; a disaster',
    answer: 'disaster',
    antonym: 'triumph',
    related: 'setback',
    decoy: 'crayon',
    confusable: { word: 'catalyst', meaning: 'trigger' },
    sentence: 'The market crash proved to be a financial cataclysm for thousands of retirees.',
  },
  {
    id: 'wk-cathartic', chapter: CH, concepts: POOL, band: 4,
    word: 'cathartic', pos: 'adj', charge: 'pos',
    gloss: 'providing psychological relief through the release of strong or repressed emotion',
    answer: 'therapeutic',
    antonym: 'stifling',
    related: 'emotional',
    decoy: 'tubular',
    confusable: { word: 'cataleptic', meaning: 'rigid' },
    sentence: 'Writing the letter, even if she never sent it, felt cathartic.',
  },
  {
    id: 'wk-charlatan', chapter: CH, concepts: POOL, band: 4,
    word: 'charlatan', pos: 'noun', charge: 'neg',
    gloss: 'a person who falsely claims to have expert knowledge or skill; a fraud',
    answer: 'fraud',
    antonym: 'expert',
    related: 'amateur',
    decoy: 'lantern',
    confusable: { word: 'charade', meaning: 'pretense' },
    sentence: 'The self-proclaimed healer was exposed as a charlatan after his tonics made people sicker.',
  },
  {
    id: 'wk-circumscribe', chapter: CH, concepts: POOL, band: 5,
    word: 'circumscribe', pos: 'verb', charge: 'neutral',
    gloss: 'to restrict or confine within limits',
    answer: 'restrict',
    antonym: 'expand',
    related: 'define',
    decoy: 'paint',
    confusable: { word: 'circumvent', meaning: 'evade' },
    sentence: 'New regulations sharply circumscribe what the agency is allowed to investigate.',
  },
]);
