// Word pool, batch 07 - 32 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// Source tier: `data/wordCandidates.csv` at hardListHits >= 2. Alphabetical run "politic"
// through "sophistry". Conventions: see pool-03.js.
//
// `recrudesce` shows the same semantic-collision trap `overt` did in batch 06. Its natural
// confusable is `recede`, but "retreat" is also a fair ANTONYM of a thing breaking out again -
// the opposite frame would have shipped two right answers. `rescind` / "cancel" keeps the shape
// slip and drops the collision.
//
// Several rows are ordinary words carrying the tested sense: `politic` (shrewd, not
// party-political), `plastic`'s neighbour `pliant` back in batch 06, `skirt` (to evade),
// `sage`, `repose` and `resolution` (firmness of purpose, not the end of a plot). Their
// confusables are chosen to name the exact slip: politic/political, sage/sag, skirt/skirmish.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-politic', chapter: CH, concepts: POOL, band: 4,
    word: 'politic', pos: 'adj', charge: 'pos',
    gloss: 'shrewd and prudent in the way it handles people',
    answer: 'prudent',
    antonym: 'rash',
    related: 'courteous',
    decoy: 'ferrous',
    confusable: { word: 'political', meaning: 'partisan' },
    sentence: 'It would not be politic to raise that at the board meeting.',
  },
  {
    id: 'wk-polyglot', chapter: CH, concepts: POOL, band: 5,
    word: 'polyglot', pos: 'noun', charge: 'neutral',
    gloss: 'a person who knows and uses several languages',
    answer: 'linguist',
    antonym: 'monoglot',
    related: 'translator',
    decoy: 'sculptor',
    confusable: { word: 'polygon', meaning: 'shape' },
    sentence: 'A natural polyglot, she handled four of the delegations herself.',
  },
  {
    id: 'wk-posit', chapter: CH, concepts: POOL, band: 4,
    word: 'posit', pos: 'verb', charge: 'neutral',
    gloss: 'to put something forward as true, as the basis for an argument',
    answer: 'assume',
    antonym: 'disprove',
    related: 'argue',
    decoy: 'unpack',
    confusable: { word: 'deposit', meaning: 'store' },
    sentence: 'The paper posits a single cause for all three failures.',
  },
  {
    id: 'wk-preamble', chapter: CH, concepts: POOL, band: 4,
    word: 'preamble', pos: 'noun', charge: 'neutral',
    gloss: 'an opening statement that sets out what follows and why',
    answer: 'introduction',
    antonym: 'conclusion',
    related: 'constitution',
    decoy: 'ornament',
    confusable: { word: 'precedent', meaning: 'prior example' },
    sentence: 'She skipped the preamble and went straight to the numbers.',
  },
  {
    id: 'wk-precocious', chapter: CH, concepts: POOL, band: 3,
    word: 'precocious', pos: 'adj', charge: 'neutral',
    gloss: 'showing an ability much earlier than is usual',
    answer: 'advanced',
    antonym: 'backward',
    related: 'youthful',
    decoy: 'woolen',
    confusable: { word: 'precarious', meaning: 'unstable' },
    sentence: 'A precocious reader, he finished the whole series before he was seven.',
  },
  {
    id: 'wk-prescient', chapter: CH, concepts: POOL, band: 4,
    word: 'prescient', pos: 'adj', charge: 'pos',
    gloss: 'knowing what is going to happen before it does',
    answer: 'foresighted',
    antonym: 'oblivious',
    related: 'cautious',
    decoy: 'gilded',
    confusable: { word: 'prescriptive', meaning: 'dictating' },
    sentence: 'His prescient warning about the supply chain was ignored.',
  },
  {
    id: 'wk-pretentious', chapter: CH, concepts: POOL, band: 3,
    word: 'pretentious', pos: 'adj', charge: 'neg',
    gloss: 'trying to seem more important or cultured than is warranted',
    answer: 'affected',
    antonym: 'unassuming',
    related: 'wealthy',
    decoy: 'tepid',
    confusable: { word: 'portentous', meaning: 'ominous' },
    sentence: 'The menu descriptions were pretentious and the food was ordinary.',
  },
  {
    id: 'wk-prolix', chapter: CH, concepts: POOL, band: 5,
    word: 'prolix', pos: 'adj', charge: 'neg',
    gloss: 'using far more words than the point needs',
    answer: 'wordy',
    antonym: 'terse',
    related: 'tedious',
    decoy: 'amber',
    confusable: { word: 'prolific', meaning: 'productive' },
    sentence: 'The prolix introduction ran to forty pages before the argument began.',
  },
  {
    id: 'wk-prophetic', chapter: CH, concepts: POOL, band: 3,
    word: 'prophetic', pos: 'adj', charge: 'neutral',
    gloss: 'correctly saying in advance what was going to happen',
    answer: 'predictive',
    antonym: 'mistaken',
    related: 'religious',
    decoy: 'elliptic',
    confusable: { word: 'pathetic', meaning: 'pitiful' },
    sentence: 'His remark about the weather turned out to be prophetic.',
  },
  {
    id: 'wk-proselytize', chapter: CH, concepts: POOL, band: 5,
    word: 'proselytize', pos: 'verb', charge: 'neutral',
    gloss: 'to try to bring other people round to your own beliefs',
    answer: 'convert',
    antonym: 'renounce',
    related: 'baptize',
    decoy: 'pasteurize',
    confusable: { word: 'prosecute', meaning: 'charge' },
    sentence: 'He came to the meeting to proselytize, not to listen.',
  },
  {
    id: 'wk-providential', chapter: CH, concepts: POOL, band: 5,
    word: 'providential', pos: 'adj', charge: 'pos',
    gloss: 'lucky in a way that looks almost arranged',
    answer: 'fortunate',
    antonym: 'unlucky',
    related: 'divine',
    decoy: 'seaborne',
    confusable: { word: 'provincial', meaning: 'parochial' },
    sentence: 'The delay turned out to be providential; the earlier flight never left.',
  },
  {
    id: 'wk-pulchritude', chapter: CH, concepts: POOL, band: 5,
    word: 'pulchritude', pos: 'noun', charge: 'pos',
    gloss: 'physical beauty',
    answer: 'beauty',
    antonym: 'ugliness',
    related: 'vanity',
    decoy: 'latitude',
    confusable: { word: 'plenitude', meaning: 'abundance' },
    sentence: 'The poem spends four stanzas on her pulchritude and none on her mind.',
  },
  {
    id: 'wk-quotidian', chapter: CH, concepts: POOL, band: 5,
    word: 'quotidian', pos: 'adj', charge: 'neutral',
    gloss: 'daily, and so ordinary as to go unnoticed',
    answer: 'everyday',
    antonym: 'exceptional',
    related: 'punctual',
    decoy: 'sylvan',
    confusable: { word: 'quotable', meaning: 'memorable' },
    sentence: 'She found a strange comfort in the quotidian business of the office.',
  },
  {
    id: 'wk-recrudesce', chapter: CH, concepts: POOL, band: 5,
    word: 'recrudesce', pos: 'verb', charge: 'neg',
    gloss: 'to break out again after a period of quiet',
    answer: 'reappear',
    antonym: 'subside',
    related: 'worsen',
    decoy: 'stencil',
    confusable: { word: 'rescind', meaning: 'cancel' },
    sentence: 'The infection recrudesced two months after treatment stopped.',
  },
  {
    id: 'wk-refulgent', chapter: CH, concepts: POOL, band: 5,
    word: 'refulgent', pos: 'adj', charge: 'pos',
    gloss: 'shining brilliantly',
    answer: 'radiant',
    antonym: 'dim',
    related: 'polished',
    decoy: 'granite',
    confusable: { word: 'reluctant', meaning: 'unwilling' },
    sentence: 'The refulgent dome could be seen from the far side of the harbour.',
  },
  {
    id: 'wk-repertoire', chapter: CH, concepts: POOL, band: 3,
    word: 'repertoire', pos: 'noun', charge: 'neutral',
    gloss: 'the whole stock of pieces or skills a performer can call on',
    answer: 'collection',
    antonym: 'emptiness',
    related: 'rehearsal',
    decoy: 'pavement',
    confusable: { word: 'reservoir', meaning: 'storage tank' },
    sentence: 'Her repertoire ran to about thirty pieces she could play from memory.',
  },
  {
    id: 'wk-repose', chapter: CH, concepts: POOL, band: 4,
    word: 'repose', pos: 'noun', charge: 'pos',
    gloss: 'a state of rest and calm',
    answer: 'rest',
    antonym: 'agitation',
    related: 'posture',
    decoy: 'saddle',
    confusable: { word: 'repulse', meaning: 'rejection' },
    sentence: 'The garden was built for repose, not for entertaining.',
  },
  {
    id: 'wk-repugnant', chapter: CH, concepts: POOL, band: 4,
    word: 'repugnant', pos: 'adj', charge: 'neg',
    gloss: 'so distasteful that it causes disgust',
    answer: 'revolting',
    antonym: 'appealing',
    related: 'immoral',
    decoy: 'ovate',
    confusable: { word: 'repentant', meaning: 'sorry' },
    sentence: 'She found the whole arrangement repugnant and said so in writing.',
  },
  {
    id: 'wk-requite', chapter: CH, concepts: POOL, band: 5,
    word: 'requite', pos: 'verb', charge: 'neutral',
    gloss: 'to make a return for something; to pay back in kind',
    answer: 'repay',
    antonym: 'ignore',
    related: 'thank',
    decoy: 'whittle',
    confusable: { word: 'require', meaning: 'demand' },
    sentence: 'He never found a way to requite the kindness he had been shown.',
  },
  {
    id: 'wk-resolution', chapter: CH, concepts: POOL, band: 3,
    word: 'resolution', pos: 'noun', charge: 'pos',
    gloss: 'firmness of purpose; the quality of sticking to a decision',
    answer: 'determination',
    antonym: 'hesitation',
    related: 'clarity',
    decoy: 'renovation',
    confusable: { word: 'revolution', meaning: 'uprising' },
    sentence: 'It took real resolution to keep going after the third rejection.',
  },
  {
    id: 'wk-rudimentary', chapter: CH, concepts: POOL, band: 3,
    word: 'rudimentary', pos: 'adj', charge: 'neutral',
    gloss: 'basic and undeveloped; only the first stage of the thing',
    answer: 'basic',
    antonym: 'advanced',
    related: 'infantile',
    decoy: 'momentary',
    confusable: { word: 'sedimentary', meaning: 'layered' },
    sentence: 'He had only a rudimentary grasp of the language when he arrived.',
  },
  {
    id: 'wk-ruminate', chapter: CH, concepts: POOL, band: 4,
    word: 'ruminate', pos: 'verb', charge: 'neutral',
    gloss: 'to turn something over in your mind at length',
    answer: 'ponder',
    antonym: 'ignore',
    related: 'graze',
    decoy: 'varnish',
    confusable: { word: 'rummage', meaning: 'search' },
    sentence: 'He ruminated on the offer for a week before answering.',
  },
  {
    id: 'wk-sacrosanct', chapter: CH, concepts: POOL, band: 5,
    word: 'sacrosanct', pos: 'adj', charge: 'pos',
    gloss: 'so important or sacred that it must not be touched or criticised',
    answer: 'inviolable',
    antonym: 'expendable',
    related: 'ceremonial',
    decoy: 'wireless',
    confusable: { word: 'sacrificial', meaning: 'offered up' },
    sentence: 'The Friday deadline was treated as sacrosanct by everyone in the building.',
  },
  {
    id: 'wk-sage', chapter: CH, concepts: POOL, band: 3,
    word: 'sage', pos: 'adj', charge: 'pos',
    gloss: 'wise, especially with the wisdom that comes from long experience',
    answer: 'wise',
    antonym: 'foolish',
    related: 'elderly',
    decoy: 'brisk',
    confusable: { word: 'sag', meaning: 'drooping' },
    sentence: 'She gave one piece of sage advice and left us to it.',
  },
  {
    id: 'wk-scathing', chapter: CH, concepts: POOL, band: 3,
    word: 'scathing', pos: 'adj', charge: 'neg',
    gloss: 'severely and openly critical',
    answer: 'withering',
    antonym: 'flattering',
    related: 'sarcastic',
    decoy: 'seamless',
    confusable: { word: 'scalding', meaning: 'boiling' },
    sentence: 'The review was scathing about everything except the lighting.',
  },
  {
    id: 'wk-seraphic', chapter: CH, concepts: POOL, band: 5,
    word: 'seraphic', pos: 'adj', charge: 'pos',
    gloss: 'angelic; serenely and innocently beautiful',
    answer: 'angelic',
    antonym: 'demonic',
    related: 'radiant',
    decoy: 'oblong',
    confusable: { word: 'soporific', meaning: 'sleepy' },
    sentence: 'The child wore a seraphic expression that fooled nobody.',
  },
  {
    id: 'wk-skeptic', chapter: CH, concepts: POOL, band: 3,
    word: 'skeptic', pos: 'noun', charge: 'neutral',
    gloss: 'a person who withholds belief until the evidence is in',
    answer: 'doubter',
    antonym: 'believer',
    related: 'scientist',
    decoy: 'tenant',
    confusable: { word: 'septic', meaning: 'infection' },
    sentence: 'He remained a skeptic until he saw the data himself.',
  },
  {
    id: 'wk-skirt', chapter: CH, concepts: POOL, band: 3,
    word: 'skirt', pos: 'verb', charge: 'neutral',
    gloss: 'to go around the edge of something, or to avoid dealing with it',
    answer: 'evade',
    antonym: 'confront',
    related: 'trim',
    decoy: 'bandage',
    confusable: { word: 'skirmish', meaning: 'clash' },
    sentence: 'The report skirts the question of who authorised the payment.',
  },
  {
    id: 'wk-slake', chapter: CH, concepts: POOL, band: 5,
    word: 'slake', pos: 'verb', charge: 'neutral',
    gloss: 'to satisfy a thirst or a craving',
    answer: 'quench',
    antonym: 'intensify',
    related: 'drink',
    decoy: 'hoist',
    confusable: { word: 'slacken', meaning: 'loosen' },
    sentence: 'They stopped at the spring to slake their thirst.',
  },
  {
    id: 'wk-sobriquet', chapter: CH, concepts: POOL, band: 5,
    word: 'sobriquet', pos: 'noun', charge: 'neutral',
    gloss: 'a nickname, especially one that sticks',
    answer: 'nickname',
    antonym: 'surname',
    related: 'signature',
    decoy: 'gazette',
    confusable: { word: 'sobriety', meaning: 'seriousness' },
    sentence: 'The sobriquet stuck to him for the rest of his career.',
  },
  {
    id: 'wk-somnolent', chapter: CH, concepts: POOL, band: 5,
    word: 'somnolent', pos: 'adj', charge: 'neutral',
    gloss: 'drowsy, or making everyone around it drowsy',
    answer: 'drowsy',
    antonym: 'alert',
    related: 'peaceful',
    decoy: 'wiry',
    confusable: { word: 'somber', meaning: 'gloomy' },
    sentence: 'The somnolent afternoon lecture emptied half the hall.',
  },
  {
    id: 'wk-sophistry', chapter: CH, concepts: POOL, band: 5,
    word: 'sophistry', pos: 'noun', charge: 'neg',
    gloss: 'reasoning that sounds clever but is deliberately false',
    answer: 'fallacy',
    antonym: 'logic',
    related: 'rhetoric',
    decoy: 'masonry',
    confusable: { word: 'sophistication', meaning: 'refinement' },
    sentence: 'The whole defence rested on sophistry the jury saw through.',
  },
]);
