// Word pool, batch 02 - 25 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// This is NOT a curriculum chapter. There is no lesson here and none of these words teach a
// concept - they exist purely to make WK drills stop repeating (see the CLAUDE.md pool note and
// pool-zz-register.js, which is the file that actually turns this registry into templates).
//
// Band is judged honestly per word, not mechanically: `coda`, `countenance`, `deflect`,
// `compelling`, `deft` and `diminutive` are ordinary words being tested in a less ordinary sense
// (coda's figurative "rounding-off", countenance and deflect as verbs, not their common noun
// uses), so they sit at band 3 even though several neighbours in this batch are band 5.
//
// Three near-neighbour trios got extra scrutiny per row rather than shared distractors:
// decry/disdain/discredit (denunciation vs contempt vs damaged credibility - kept to distinct
// parts of speech, verb/noun/verb, so no option string is ever shared across the three);
// compelling/daunting (persuasive-attention vs intimidating-difficulty); conciliate/congenial
// (a verb of active peacemaking vs an adjective of pleasant temperament); deft/discerning
// (physical skill vs judgment); diminutive/diaphanous (size vs transparency).

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-cloying', chapter: CH, concepts: POOL, band: 4,
    word: 'cloying', pos: 'adj', charge: 'neg',
    gloss: 'excessively sweet, rich, or sentimental to the point of being distasteful',
    answer: 'saccharine',
    antonym: 'refreshing',
    related: 'decadent',
    decoy: 'brittle',
    confusable: { word: 'clotted', meaning: 'thickened' },
    sentence: "The dessert's cloying sweetness made it hard to finish more than a few bites.",
  },
  {
    id: 'wk-coagulate', chapter: CH, concepts: POOL, band: 4,
    word: 'coagulate', pos: 'verb', charge: 'neutral',
    gloss: 'to change from a liquid into a thickened mass; to clot',
    answer: 'clot',
    antonym: 'liquefy',
    related: 'freeze',
    decoy: 'illuminate',
    confusable: { word: 'coalesce', meaning: 'unite' },
    sentence: 'As the wound closed, the blood began to coagulate almost immediately.',
  },
  {
    id: 'wk-coda', chapter: CH, concepts: POOL, band: 3,
    word: 'coda', pos: 'noun', charge: 'neutral',
    gloss: 'a concluding passage or event that rounds something off',
    answer: 'finale',
    antonym: 'prelude',
    related: 'reprise',
    decoy: 'anchor',
    confusable: { word: 'code', meaning: 'cipher' },
    sentence: 'The quiet final scene served as a fitting coda to the entire trilogy.',
  },
  {
    id: 'wk-coffer', chapter: CH, concepts: POOL, band: 4,
    word: 'coffer', pos: 'noun', charge: 'neutral',
    gloss: 'a strongbox for valuables, or (usually plural) a store of money or funds',
    answer: 'treasury',
    antonym: 'deficit',
    related: 'ledger',
    decoy: 'meadow',
    confusable: { word: 'coffee', meaning: 'beverage' },
    sentence: "The kingdom's coffers were nearly empty after years of costly war.",
  },
  {
    id: 'wk-collude', chapter: CH, concepts: POOL, band: 4,
    word: 'collude', pos: 'verb', charge: 'neg',
    gloss: 'to cooperate secretly or illegally in order to deceive others',
    answer: 'conspire',
    antonym: 'compete',
    related: 'cooperate',
    decoy: 'whistle',
    confusable: { word: 'collide', meaning: 'crash' },
    sentence: 'Investigators believed the two executives had colluded to fix prices.',
  },
  {
    id: 'wk-compelling', chapter: CH, concepts: POOL, band: 3,
    word: 'compelling', pos: 'adj', charge: 'pos',
    gloss: 'so forceful or convincing that it demands attention or belief',
    answer: 'persuasive',
    antonym: 'unconvincing',
    related: 'interesting',
    decoy: 'metallic',
    confusable: { word: 'compelled', meaning: 'forced' },
    sentence: 'The lawyer presented a compelling case that swayed even skeptical jurors.',
  },
  {
    id: 'wk-compendium', chapter: CH, concepts: POOL, band: 4,
    word: 'compendium', pos: 'noun', charge: 'neutral',
    gloss: 'a concise collection or summary of a larger body of information',
    answer: 'summary',
    antonym: 'expansion',
    related: 'encyclopedia',
    decoy: 'furnace',
    confusable: { word: 'condominium', meaning: 'housing' },
    sentence: "The professor assigned a compendium of essays covering the entire semester's readings.",
  },
  {
    id: 'wk-conciliate', chapter: CH, concepts: POOL, band: 4,
    word: 'conciliate', pos: 'verb', charge: 'pos',
    gloss: 'to overcome distrust or hostility by pleasant, appeasing behavior',
    answer: 'appease',
    antonym: 'antagonize',
    related: 'negotiate',
    decoy: 'illustrate',
    confusable: { word: 'capitulate', meaning: 'surrender' },
    sentence: 'The manager tried to conciliate the angry customer by offering a refund and an apology.',
  },
  {
    id: 'wk-conflagration', chapter: CH, concepts: POOL, band: 5,
    word: 'conflagration', pos: 'noun', charge: 'neg',
    gloss: 'a large, destructive fire',
    answer: 'inferno',
    antonym: 'containment',
    related: 'arson',
    decoy: 'lagoon',
    confusable: { word: 'conjugation', meaning: 'grammar' },
    sentence: 'The conflagration spread through six city blocks before firefighters brought it under control.',
  },
  {
    id: 'wk-congenial', chapter: CH, concepts: POOL, band: 4,
    word: 'congenial', pos: 'adj', charge: 'pos',
    gloss: 'pleasant and agreeable; suited to one’s nature or tastes',
    answer: 'amiable',
    antonym: 'disagreeable',
    related: 'charming',
    decoy: 'tubular',
    confusable: { word: 'congenital', meaning: 'inborn' },
    sentence: 'The two colleagues, despite different backgrounds, found each other quite congenial.',
  },
  {
    id: 'wk-cosset', chapter: CH, concepts: POOL, band: 5,
    word: 'cosset', pos: 'verb', charge: 'neutral',
    gloss: 'to care for and protect in an indulgent way; to pamper',
    answer: 'pamper',
    antonym: 'neglect',
    related: 'protect',
    decoy: 'trumpet',
    confusable: { word: 'corset', meaning: 'constrict' },
    sentence: 'Grandparents often cosset their grandchildren far more than they ever indulged their own kids.',
  },
  {
    id: 'wk-coterie', chapter: CH, concepts: POOL, band: 5,
    word: 'coterie', pos: 'noun', charge: 'neutral',
    gloss: 'a small, exclusive group of people with shared interests',
    answer: 'clique',
    antonym: 'public',
    related: 'faction',
    decoy: 'ladder',
    confusable: { word: 'cotillion', meaning: 'dance' },
    sentence: "She was welcomed into the artist's coterie after her gallery show received such praise.",
  },
  {
    id: 'wk-countenance', chapter: CH, concepts: POOL, band: 3,
    word: 'countenance', pos: 'verb', charge: 'neutral',
    gloss: 'to admit as acceptable or possible; to tolerate or give approval to',
    answer: 'sanction',
    antonym: 'forbid',
    related: 'witness',
    decoy: 'garnish',
    confusable: { word: 'countervail', meaning: 'offset' },
    sentence: 'The captain refused to countenance any further delay in the mission timeline.',
  },
  {
    id: 'wk-crestfallen', chapter: CH, concepts: POOL, band: 4,
    word: 'crestfallen', pos: 'adj', charge: 'neg',
    gloss: 'feeling sad and disappointed, especially after a failure or setback; dejected',
    answer: 'dejected',
    antonym: 'elated',
    related: 'ashamed',
    decoy: 'granular',
    confusable: { word: 'cresting', meaning: 'peaking' },
    sentence: 'The team was crestfallen after missing the championship by a single point.',
  },
  {
    id: 'wk-daunting', chapter: CH, concepts: POOL, band: 3,
    word: 'daunting', pos: 'adj', charge: 'neg',
    gloss: 'seeming difficult to deal with in prospect; intimidating',
    answer: 'intimidating',
    antonym: 'manageable',
    related: 'challenging',
    decoy: 'porous',
    confusable: { word: 'taunting', meaning: 'mocking' },
    sentence: 'Climbing the sheer rock face looked daunting even to the most experienced mountaineers.',
  },
  {
    id: 'wk-decry', chapter: CH, concepts: POOL, band: 4,
    word: 'decry', pos: 'verb', charge: 'neg',
    gloss: 'to publicly denounce or criticize something as wrong or bad',
    answer: 'denounce',
    antonym: 'praise',
    related: 'bemoan',
    decoy: 'juggle',
    confusable: { word: 'decree', meaning: 'order' },
    sentence: "Environmental groups continued to decry the company's handling of the chemical spill.",
  },
  {
    id: 'wk-deflect', chapter: CH, concepts: POOL, band: 3,
    word: 'deflect', pos: 'verb', charge: 'neutral',
    gloss: 'to turn something aside from its original course, especially to avoid criticism',
    answer: 'divert',
    antonym: 'absorb',
    related: 'ignore',
    decoy: 'polish',
    confusable: { word: 'defect', meaning: 'abandon' },
    sentence: 'The spokesperson tried to deflect questions about the scandal by changing the subject.',
  },
  {
    id: 'wk-deft', chapter: CH, concepts: POOL, band: 3,
    word: 'deft', pos: 'adj', charge: 'pos',
    gloss: 'showing skill and cleverness, especially with the hands',
    answer: 'dexterous',
    antonym: 'inept',
    related: 'quick',
    decoy: 'lunar',
    confusable: { word: 'deaf', meaning: 'unhearing' },
    sentence: 'Her deft repair of the engine impressed even the veteran mechanics.',
  },
  {
    id: 'wk-deify', chapter: CH, concepts: POOL, band: 4,
    word: 'deify', pos: 'verb', charge: 'neutral',
    gloss: 'to worship or regard as a god; to treat as infallibly great',
    answer: 'idolize',
    antonym: 'demonize',
    related: 'admire',
    decoy: 'whistle',
    confusable: { word: 'defy', meaning: 'resist' },
    sentence: 'Ancient civilizations often deified their rulers, treating them as living gods.',
  },
  {
    id: 'wk-deterrent', chapter: CH, concepts: POOL, band: 4,
    word: 'deterrent', pos: 'noun', charge: 'neutral',
    gloss: 'a thing that discourages or is intended to discourage someone from an action',
    answer: 'disincentive',
    antonym: 'incentive',
    related: 'punishment',
    decoy: 'carnival',
    confusable: { word: 'determinant', meaning: 'factor' },
    sentence: 'The threat of a heavy fine acts as a deterrent against illegal dumping.',
  },
  {
    id: 'wk-diaphanous', chapter: CH, concepts: POOL, band: 5,
    word: 'diaphanous', pos: 'adj', charge: 'neutral',
    gloss: 'light, fine, and translucent, especially of fabric',
    answer: 'sheer',
    antonym: 'opaque',
    related: 'delicate',
    decoy: 'tabular',
    confusable: { word: 'cacophonous', meaning: 'noisy' },
    sentence: 'The dancer wore a diaphanous scarf that fluttered like mist in the breeze.',
  },
  {
    id: 'wk-diminutive', chapter: CH, concepts: POOL, band: 3,
    word: 'diminutive', pos: 'adj', charge: 'neutral',
    gloss: 'extremely or unusually small',
    answer: 'tiny',
    antonym: 'immense',
    related: 'youthful',
    decoy: 'porous',
    confusable: { word: 'diminished', meaning: 'reduced' },
    sentence: 'Despite his diminutive stature, the boxer packed a surprisingly powerful punch.',
  },
  {
    id: 'wk-discerning', chapter: CH, concepts: POOL, band: 4,
    word: 'discerning', pos: 'adj', charge: 'pos',
    gloss: 'having or showing good judgment, especially about taste or quality; perceptive',
    answer: 'perceptive',
    antonym: 'indiscriminate',
    related: 'informed',
    decoy: 'floral',
    confusable: { word: 'discursive', meaning: 'rambling' },
    sentence: 'A discerning collector, she could immediately tell the forgery from the genuine painting.',
  },
  {
    id: 'wk-discredit', chapter: CH, concepts: POOL, band: 4,
    word: 'discredit', pos: 'verb', charge: 'neg',
    gloss: "to harm someone's reputation, or to cause doubt about the truth of a claim",
    answer: 'defame',
    antonym: 'vindicate',
    related: 'contradict',
    decoy: 'yodel',
    confusable: { word: 'discreet', meaning: 'conceal' },
    sentence: "New evidence emerged that seemed to discredit the witness's entire testimony.",
  },
  {
    id: 'wk-disdain', chapter: CH, concepts: POOL, band: 3,
    word: 'disdain', pos: 'noun', charge: 'neg',
    gloss: 'a feeling of contempt for someone or something regarded as unworthy',
    answer: 'contempt',
    antonym: 'admiration',
    related: 'indifference',
    decoy: 'volcano',
    confusable: { word: 'abstain', meaning: 'abstention' },
    sentence: "He regarded the committee's decision with open disdain.",
  },
]);
