// Word pool, batch 05 - 32 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// Source tier: `data/wordCandidates.csv` at hardListHits >= 2. Alphabetical run "ineluctable"
// through "misnomer". Conventions: see pool-03.js.
//
// ✂️ `malingerer` is in the candidate list and is deliberately NOT authored. It is the agent
// noun of `malinger`, which IS here - two rows differing only by "-er" produce two flashcards
// that teach one word, and the drill would serve them as independent items. Author the base
// form; the derived form comes free.
//
// `imprecation` (batch 04) and `malediction` (here) both answer "curse" and that is correct
// rather than a collision - they are true synonyms and the test treats them as one idea. Their
// slates share no other string, and `malediction` carries the mal-/bene- antonym pair
// (benediction) which is the fastest way to hold on to both.
//
// Six rows are ordinary words carrying the tested second sense and are banded 3-4 for it:
// `inform` (to pervade and shape, not to tell), `inter` (to bury), `lull`, `lax`, `mar`,
// and `graft`'s neighbour `husband` back in batch 04.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-ineluctable', chapter: CH, concepts: POOL, band: 5,
    word: 'ineluctable', pos: 'adj', charge: 'neutral',
    gloss: 'impossible to avoid or escape',
    answer: 'unavoidable',
    antonym: 'preventable',
    related: 'fated',
    decoy: 'washable',
    confusable: { word: 'inelegant', meaning: 'clumsy' },
    sentence: 'The conclusion was ineluctable once the second report arrived.',
  },
  {
    id: 'wk-inexorable', chapter: CH, concepts: POOL, band: 4,
    word: 'inexorable', pos: 'adj', charge: 'neutral',
    gloss: 'impossible to stop, slow down or persuade',
    answer: 'relentless',
    antonym: 'yielding',
    related: 'steady',
    decoy: 'wearable',
    confusable: { word: 'inexplicable', meaning: 'baffling' },
    sentence: 'The inexorable rise in costs finally closed the factory.',
  },
  {
    id: 'wk-inform', chapter: CH, concepts: POOL, band: 4,
    word: 'inform', pos: 'verb', charge: 'neutral',
    gloss: 'to give something its essential character, running all the way through it',
    answer: 'pervade',
    antonym: 'obscure',
    related: 'lecture',
    decoy: 'ventilate',
    confusable: { word: 'conform', meaning: 'obey' },
    sentence: 'A deep respect for evidence informs everything she writes.',
  },
  {
    id: 'wk-ingrate', chapter: CH, concepts: POOL, band: 4,
    word: 'ingrate', pos: 'noun', charge: 'neg',
    gloss: 'a person who shows no gratitude for what has been done for them',
    answer: 'ungrateful person',
    antonym: 'loyal supporter',
    related: 'selfish heir',
    decoy: 'skilled artisan',
    confusable: { word: 'ingratiate', meaning: 'flattering sort' },
    sentence: 'After all the help he was given, the ingrate never sent a word of thanks.',
  },
  {
    id: 'wk-iniquity', chapter: CH, concepts: POOL, band: 5,
    word: 'iniquity', pos: 'noun', charge: 'neg',
    gloss: 'gross wickedness or grossly unfair treatment',
    answer: 'wickedness',
    antonym: 'virtue',
    related: 'punishment',
    decoy: 'machinery',
    confusable: { word: 'inequity', meaning: 'unfairness' },
    sentence: 'The prophet denounced the iniquity of the city in the plainest terms.',
  },
  {
    id: 'wk-inter', chapter: CH, concepts: POOL, band: 4,
    word: 'inter', pos: 'verb', charge: 'neutral',
    gloss: 'to place a dead body in a grave or tomb',
    answer: 'bury',
    antonym: 'exhume',
    related: 'mourn',
    decoy: 'sharpen',
    confusable: { word: 'enter', meaning: 'go in' },
    sentence: 'They interred him beside his wife in the village churchyard.',
  },
  {
    id: 'wk-intrinsic', chapter: CH, concepts: POOL, band: 3,
    word: 'intrinsic', pos: 'adj', charge: 'neutral',
    gloss: 'belonging to something as part of its essential nature',
    answer: 'inherent',
    antonym: 'external',
    related: 'valuable',
    decoy: 'seasonal',
    confusable: { word: 'intricate', meaning: 'complicated' },
    sentence: 'The intrinsic value of the land had nothing to do with the market.',
  },
  {
    id: 'wk-inviolate', chapter: CH, concepts: POOL, band: 5,
    word: 'inviolate', pos: 'adj', charge: 'pos',
    gloss: 'kept whole and untouched; never broken into or violated',
    answer: 'unbroken',
    antonym: 'defiled',
    related: 'ancient',
    decoy: 'adjustable',
    confusable: { word: 'involute', meaning: 'intricate' },
    sentence: 'The treaty left the old border inviolate for another century.',
  },
  {
    id: 'wk-itinerary', chapter: CH, concepts: POOL, band: 3,
    word: 'itinerary', pos: 'noun', charge: 'neutral',
    gloss: 'a planned route and schedule for a journey',
    answer: 'schedule',
    antonym: 'improvisation',
    related: 'passport',
    decoy: 'sediment',
    confusable: { word: 'itinerant', meaning: 'wanderer' },
    sentence: 'The itinerary allowed exactly one hour in each city.',
  },
  {
    id: 'wk-juxtapose', chapter: CH, concepts: POOL, band: 4,
    word: 'juxtapose', pos: 'verb', charge: 'neutral',
    gloss: 'to place two things side by side so the contrast shows',
    answer: 'contrast',
    antonym: 'separate',
    related: 'exhibit',
    decoy: 'lubricate',
    confusable: { word: 'transpose', meaning: 'swap' },
    sentence: 'The gallery juxtaposes early sketches with the finished paintings.',
  },
  {
    id: 'wk-kinetic', chapter: CH, concepts: POOL, band: 3,
    word: 'kinetic', pos: 'adj', charge: 'neutral',
    gloss: 'relating to motion, or produced by motion',
    answer: 'moving',
    antonym: 'static',
    related: 'muscular',
    decoy: 'saline',
    confusable: { word: 'genetic', meaning: 'inherited' },
    sentence: 'A falling weight converts stored energy into kinetic energy.',
  },
  {
    id: 'wk-knell', chapter: CH, concepts: POOL, band: 5,
    word: 'knell', pos: 'noun', charge: 'neg',
    gloss: 'the slow ringing of a bell for a death, or any sign that something is finished',
    answer: 'toll',
    antonym: 'fanfare',
    related: 'funeral',
    decoy: 'trellis',
    confusable: { word: 'knoll', meaning: 'hillock' },
    sentence: 'The vote sounded the knell for the whole programme.',
  },
  {
    id: 'wk-languish', chapter: CH, concepts: POOL, band: 4,
    word: 'languish', pos: 'verb', charge: 'neg',
    gloss: 'to lose strength or vitality; to be left neglected for a long time',
    answer: 'weaken',
    antonym: 'thrive',
    related: 'linger',
    decoy: 'calibrate',
    confusable: { word: 'anguish', meaning: 'agonize' },
    sentence: 'The proposal languished in committee for three years.',
  },
  {
    id: 'wk-largess', chapter: CH, concepts: POOL, band: 5,
    word: 'largess', pos: 'noun', charge: 'pos',
    gloss: 'generous giving of money or gifts, especially by someone powerful',
    answer: 'generosity',
    antonym: 'stinginess',
    related: 'inheritance',
    decoy: 'humidity',
    confusable: { word: 'largeness', meaning: 'bulk' },
    sentence: 'The library was built entirely through the largess of one family.',
  },
  {
    id: 'wk-laudable', chapter: CH, concepts: POOL, band: 4,
    word: 'laudable', pos: 'adj', charge: 'pos',
    gloss: 'deserving praise',
    answer: 'praiseworthy',
    antonym: 'shameful',
    related: 'noble',
    decoy: 'inflatable',
    confusable: { word: 'audible', meaning: 'hearable' },
    sentence: 'Her attempt to save the programme was laudable but too late.',
  },
  {
    id: 'wk-lax', chapter: CH, concepts: POOL, band: 3,
    word: 'lax', pos: 'adj', charge: 'neg',
    gloss: 'not strict or careful enough about standards',
    answer: 'slack',
    antonym: 'strict',
    related: 'casual',
    decoy: 'damp',
    confusable: { word: 'lack', meaning: 'absent' },
    sentence: 'Security had grown lax in the months before the break-in.',
  },
  {
    id: 'wk-legerdemain', chapter: CH, concepts: POOL, band: 5,
    word: 'legerdemain', pos: 'noun', charge: 'neutral',
    gloss: 'sleight of hand, or any clever trickery that hides what is really happening',
    answer: 'trickery',
    antonym: 'openness',
    related: 'dexterity',
    decoy: 'stairwell',
    confusable: { word: 'ledger', meaning: 'account book' },
    sentence: 'The budget balanced only through some creative legerdemain with the figures.',
  },
  {
    id: 'wk-licentious', chapter: CH, concepts: POOL, band: 5,
    word: 'licentious', pos: 'adj', charge: 'neg',
    gloss: 'ignoring accepted rules and restraints, especially about morals',
    answer: 'immoral',
    antonym: 'chaste',
    related: 'indulgent',
    decoy: 'tidal',
    confusable: { word: 'licensed', meaning: 'authorized' },
    sentence: 'The play was banned as licentious and stayed banned for forty years.',
  },
  {
    id: 'wk-lionize', chapter: CH, concepts: POOL, band: 4,
    word: 'lionize', pos: 'verb', charge: 'pos',
    gloss: 'to treat someone as a celebrity or hero',
    answer: 'glorify',
    antonym: 'belittle',
    related: 'admire',
    decoy: 'refrigerate',
    confusable: { word: 'ionize', meaning: 'electrify' },
    sentence: 'The press lionized her for weeks after the rescue.',
  },
  {
    id: 'wk-lissome', chapter: CH, concepts: POOL, band: 5,
    word: 'lissome', pos: 'adj', charge: 'pos',
    gloss: 'slim and moving with easy grace',
    answer: 'supple',
    antonym: 'stiff',
    related: 'youthful',
    decoy: 'briny',
    confusable: { word: 'loathsome', meaning: 'repulsive' },
    sentence: 'The lissome dancer crossed the stage in four strides.',
  },
  {
    id: 'wk-listless', chapter: CH, concepts: POOL, band: 4,
    word: 'listless', pos: 'adj', charge: 'neg',
    gloss: 'having no energy or enthusiasm for anything',
    answer: 'lethargic',
    antonym: 'energetic',
    related: 'bored',
    decoy: 'ribbed',
    confusable: { word: 'listed', meaning: 'catalogued' },
    sentence: 'He spent a listless afternoon staring out of the window.',
  },
  {
    id: 'wk-lull', chapter: CH, concepts: POOL, band: 3,
    word: 'lull', pos: 'noun', charge: 'neutral',
    gloss: 'a temporary pause in noise, activity or violence',
    answer: 'respite',
    antonym: 'surge',
    related: 'truce',
    decoy: 'ladder',
    confusable: { word: 'null', meaning: 'zero' },
    sentence: 'They slipped out during a lull in the questioning.',
  },
  {
    id: 'wk-maelstrom', chapter: CH, concepts: POOL, band: 4,
    word: 'maelstrom', pos: 'noun', charge: 'neg',
    gloss: 'a scene of violent confusion, named for a whirlpool that swallows everything',
    answer: 'turmoil',
    antonym: 'calm',
    related: 'riptide',
    decoy: 'archive',
    confusable: { word: 'malaise', meaning: 'unease' },
    sentence: 'The announcement dropped him into a maelstrom of press attention.',
  },
  {
    id: 'wk-malediction', chapter: CH, concepts: POOL, band: 5,
    word: 'malediction', pos: 'noun', charge: 'neg',
    gloss: 'a spoken curse; the calling down of evil on someone',
    answer: 'curse',
    antonym: 'benediction',
    related: 'insult',
    decoy: 'aqueduct',
    confusable: { word: 'malfunction', meaning: 'breakdown' },
    sentence: 'The old woman spat a malediction at the departing carriage.',
  },
  {
    id: 'wk-malinger', chapter: CH, concepts: POOL, band: 5,
    word: 'malinger', pos: 'verb', charge: 'neg',
    gloss: 'to pretend to be ill in order to avoid work or duty',
    answer: 'shirk',
    antonym: 'persevere',
    related: 'complain',
    decoy: 'excavate',
    confusable: { word: 'linger', meaning: 'dawdle' },
    sentence: 'Two of the crew were accused of malingering to avoid the night watch.',
  },
  {
    id: 'wk-mar', chapter: CH, concepts: POOL, band: 3,
    word: 'mar', pos: 'verb', charge: 'neg',
    gloss: 'to spoil the appearance or quality of something',
    answer: 'spoil',
    antonym: 'improve',
    related: 'scratch',
    decoy: 'summon',
    confusable: { word: 'mark', meaning: 'label' },
    sentence: 'A single careless comment marred an otherwise perfect evening.',
  },
  {
    id: 'wk-mendacity', chapter: CH, concepts: POOL, band: 5,
    word: 'mendacity', pos: 'noun', charge: 'neg',
    gloss: 'untruthfulness; the habit of lying',
    answer: 'dishonesty',
    antonym: 'truthfulness',
    related: 'exaggeration',
    decoy: 'topography',
    confusable: { word: 'mendicant', meaning: 'begging' },
    sentence: 'The committee was stunned by the sheer mendacity of his testimony.',
  },
  {
    id: 'wk-meretricious', chapter: CH, concepts: POOL, band: 5,
    word: 'meretricious', pos: 'adj', charge: 'neg',
    gloss: 'showily attractive but cheap and worthless underneath',
    answer: 'tawdry',
    antonym: 'genuine',
    related: 'flashy',
    decoy: 'thermal',
    confusable: { word: 'meritorious', meaning: 'deserving' },
    sentence: 'The jewellery looked expensive but was meretricious rubbish.',
  },
  {
    id: 'wk-mettlesome', chapter: CH, concepts: POOL, band: 5,
    word: 'mettlesome', pos: 'adj', charge: 'pos',
    gloss: 'full of spirit and courage',
    answer: 'spirited',
    antonym: 'timid',
    related: 'restless',
    decoy: 'soluble',
    confusable: { word: 'meddlesome', meaning: 'intrusive' },
    sentence: 'A mettlesome young officer volunteered for the first patrol.',
  },
  {
    id: 'wk-militate', chapter: CH, concepts: POOL, band: 5,
    word: 'militate', pos: 'verb', charge: 'neutral',
    gloss: 'to be a strong influence working against something',
    answer: 'counteract',
    antonym: 'promote',
    related: 'delay',
    decoy: 'saturate',
    confusable: { word: 'mitigate', meaning: 'soften' },
    sentence: 'His inexperience militated against any chance of an early command.',
  },
  {
    id: 'wk-mirth', chapter: CH, concepts: POOL, band: 4,
    word: 'mirth', pos: 'noun', charge: 'pos',
    gloss: 'amusement, especially as it shows in laughter',
    answer: 'merriment',
    antonym: 'gloom',
    related: 'laughter',
    decoy: 'ointment',
    confusable: { word: 'myrrh', meaning: 'resin' },
    sentence: 'The story was met with general mirth around the table.',
  },
  {
    id: 'wk-misnomer', chapter: CH, concepts: POOL, band: 4,
    word: 'misnomer', pos: 'noun', charge: 'neutral',
    gloss: 'a name that is wrong or unsuitable for the thing it is applied to',
    answer: 'wrong name',
    antonym: 'apt title',
    related: 'nickname',
    decoy: 'wooden crate',
    confusable: { word: 'misdemeanor', meaning: 'minor offence' },
    sentence: 'Calling it a hotel is a misnomer; it has four rooms and no staff.',
  },
]);
