// Word pool, batch 08 - 26 words feeding the shared drill pool (chapter wk-20-vocab-pool).
//
// Source tier: `data/wordCandidates.csv` at hardListHits >= 2. Alphabetical run "sound" through
// "welter", and the LAST of the >= 2 tier - with this file every high-confidence candidate is
// authored. What remains in the CSV is the 733-row hardListHits == 1 tail. Conventions: see
// pool-03.js.
//
// `ubiquitous` takes `iniquitous` as its confusable on purpose: `iniquity` is a live row in
// batch 05, so the two reinforce each other instead of just colliding. That is the ideal shape
// for a confusable - a word the bank actually teaches elsewhere.
//
// `tempestuous` had to give up the obvious `tempered` / "moderated" trap for the same reason
// `overt` and `recrudesce` did: "moderated" is a fair opposite of stormy, so the opposite frame
// would have had two right answers. `temporal` / "worldly" is the shape slip without the clash.

import { registerWords } from '../../engine/words.js';

const CH = 'wk-20-vocab-pool';
const POOL = ['wk-vocab-pool'];

registerWords([
  {
    id: 'wk-sound', chapter: CH, concepts: POOL, band: 3,
    word: 'sound', pos: 'adj', charge: 'pos',
    gloss: 'free from defect or error; solid enough to be relied on',
    answer: 'valid',
    antonym: 'flawed',
    related: 'audible',
    decoy: 'purple',
    confusable: { word: 'sundry', meaning: 'assorted' },
    sentence: 'The building is structurally sound despite its age.',
  },
  {
    id: 'wk-sportive', chapter: CH, concepts: POOL, band: 5,
    word: 'sportive', pos: 'adj', charge: 'pos',
    gloss: 'playful and light-hearted',
    answer: 'playful',
    antonym: 'solemn',
    related: 'athletic',
    decoy: 'arid',
    confusable: { word: 'supportive', meaning: 'encouraging' },
    sentence: 'A sportive mood took hold of the whole crew after the news.',
  },
  {
    id: 'wk-squelch', chapter: CH, concepts: POOL, band: 4,
    word: 'squelch', pos: 'verb', charge: 'neutral',
    gloss: 'to put a stop to something completely and quickly',
    answer: 'suppress',
    antonym: 'encourage',
    related: 'splash',
    decoy: 'reheat',
    confusable: { word: 'squeal', meaning: 'shriek' },
    sentence: 'Management squelched the rumour before it reached the press.',
  },
  {
    id: 'wk-stalwart', chapter: CH, concepts: POOL, band: 4,
    word: 'stalwart', pos: 'adj', charge: 'pos',
    gloss: 'loyal and dependable over a long stretch',
    answer: 'steadfast',
    antonym: 'fickle',
    related: 'lifelong',
    decoy: 'mottled',
    confusable: { word: 'stagnant', meaning: 'motionless' },
    sentence: 'A stalwart supporter of the club for forty years, he never missed a match.',
  },
  {
    id: 'wk-stasis', chapter: CH, concepts: POOL, band: 5,
    word: 'stasis', pos: 'noun', charge: 'neutral',
    gloss: 'a state in which nothing moves or changes',
    answer: 'stagnation',
    antonym: 'motion',
    related: 'equilibrium',
    decoy: 'aviary',
    confusable: { word: 'status', meaning: 'standing' },
    sentence: 'The negotiations settled into a stasis that lasted all winter.',
  },
  {
    id: 'wk-strut', chapter: CH, concepts: POOL, band: 3,
    word: 'strut', pos: 'verb', charge: 'neg',
    gloss: 'to walk with a stiff, vain, self-important step',
    answer: 'swagger',
    antonym: 'shuffle',
    related: 'pose',
    decoy: 'simmer',
    confusable: { word: 'strive', meaning: 'struggle' },
    sentence: 'He strutted the length of the room as though he had won something.',
  },
  {
    id: 'wk-subjective', chapter: CH, concepts: POOL, band: 3,
    word: 'subjective', pos: 'adj', charge: 'neutral',
    gloss: 'based on personal feeling or opinion rather than on fact',
    answer: 'personal',
    antonym: 'objective',
    related: 'emotional',
    decoy: 'tubular',
    confusable: { word: 'subjunctive', meaning: 'hypothetical' },
    sentence: 'Grading an essay is more subjective than marking a maths paper.',
  },
  {
    id: 'wk-substantiate', chapter: CH, concepts: POOL, band: 4,
    word: 'substantiate', pos: 'verb', charge: 'neutral',
    gloss: 'to back a claim with evidence that supports it',
    answer: 'verify',
    antonym: 'refute',
    related: 'testify',
    decoy: 'upholster',
    confusable: { word: 'substitute', meaning: 'replace' },
    sentence: 'Nothing in the file substantiates the second allegation.',
  },
  {
    id: 'wk-subterfuge', chapter: CH, concepts: POOL, band: 4,
    word: 'subterfuge', pos: 'noun', charge: 'neg',
    gloss: 'a trick or dodge used to get around something openly difficult',
    answer: 'deception',
    antonym: 'frankness',
    related: 'strategy',
    decoy: 'granary',
    confusable: { word: 'subterranean', meaning: 'underground' },
    sentence: 'They got the documents out by simple subterfuge, not by force.',
  },
  {
    id: 'wk-supplicate', chapter: CH, concepts: POOL, band: 5,
    word: 'supplicate', pos: 'verb', charge: 'neutral',
    gloss: 'to ask for something humbly and earnestly',
    answer: 'beseech',
    antonym: 'demand',
    related: 'kneel',
    decoy: 'perforate',
    confusable: { word: 'supplant', meaning: 'displace' },
    sentence: 'The envoys supplicated for a week before they were granted an audience.',
  },
  {
    id: 'wk-symbiosis', chapter: CH, concepts: POOL, band: 4,
    word: 'symbiosis', pos: 'noun', charge: 'neutral',
    gloss: 'a close relationship in which each side gains from the other',
    answer: 'interdependence',
    antonym: 'rivalry',
    related: 'ecology',
    decoy: 'hedgerow',
    confusable: { word: 'symbolism', meaning: 'imagery' },
    sentence: 'The two firms exist in a kind of symbiosis neither will admit to.',
  },
  {
    id: 'wk-synoptic', chapter: CH, concepts: POOL, band: 5,
    word: 'synoptic', pos: 'adj', charge: 'neutral',
    gloss: 'giving a general overview rather than the detail',
    answer: 'summarizing',
    antonym: 'detailed',
    related: 'biblical',
    decoy: 'downy',
    confusable: { word: 'synaptic', meaning: 'neural' },
    sentence: 'The opening chapter gives a synoptic account of the whole period.',
  },
  {
    id: 'wk-tempestuous', chapter: CH, concepts: POOL, band: 4,
    word: 'tempestuous', pos: 'adj', charge: 'neg',
    gloss: 'stormy; full of violent and shifting emotion',
    answer: 'turbulent',
    antonym: 'tranquil',
    related: 'passionate',
    decoy: 'laminated',
    confusable: { word: 'temporal', meaning: 'worldly' },
    sentence: 'Their tempestuous partnership produced three albums and two lawsuits.',
  },
  {
    id: 'wk-timorous', chapter: CH, concepts: POOL, band: 5,
    word: 'timorous', pos: 'adj', charge: 'neg',
    gloss: 'lacking confidence; easily frightened',
    answer: 'fearful',
    antonym: 'bold',
    related: 'quiet',
    decoy: 'hexagonal',
    confusable: { word: 'timely', meaning: 'punctual' },
    sentence: 'A timorous knock at the door was easy to miss.',
  },
  {
    id: 'wk-toady', chapter: CH, concepts: POOL, band: 4,
    word: 'toady', pos: 'noun', charge: 'neg',
    gloss: 'a person who flatters the powerful to get something out of them',
    answer: 'sycophant',
    antonym: 'critic',
    related: 'servant',
    decoy: 'hedgerow',
    confusable: { word: 'toad', meaning: 'amphibian' },
    sentence: 'Every meeting had at least one toady agreeing with whatever the chairman said.',
  },
  {
    id: 'wk-tome', chapter: CH, concepts: POOL, band: 4,
    word: 'tome', pos: 'noun', charge: 'neutral',
    gloss: 'a large, heavy book',
    answer: 'volume',
    antonym: 'pamphlet',
    related: 'library',
    decoy: 'kettle',
    confusable: { word: 'tomb', meaning: 'crypt' },
    sentence: 'He arrived carrying a tome that must have weighed five pounds.',
  },
  {
    id: 'wk-trifling', chapter: CH, concepts: POOL, band: 3,
    word: 'trifling', pos: 'adj', charge: 'neg',
    gloss: 'so small or unimportant as not to be worth the attention',
    answer: 'insignificant',
    antonym: 'crucial',
    related: 'brief',
    decoy: 'circular',
    confusable: { word: 'stifling', meaning: 'suffocating' },
    sentence: 'They argued for an hour over a trifling difference in wording.',
  },
  {
    id: 'wk-ubiquitous', chapter: CH, concepts: POOL, band: 4,
    word: 'ubiquitous', pos: 'adj', charge: 'neutral',
    gloss: 'present everywhere at once',
    answer: 'omnipresent',
    antonym: 'scarce',
    related: 'popular',
    decoy: 'velvety',
    confusable: { word: 'iniquitous', meaning: 'wicked' },
    sentence: 'Those green scooters became ubiquitous within a single summer.',
  },
  {
    id: 'wk-underscore', chapter: CH, concepts: POOL, band: 3,
    word: 'underscore', pos: 'verb', charge: 'neutral',
    gloss: 'to give something extra emphasis so it cannot be missed',
    answer: 'emphasize',
    antonym: 'downplay',
    related: 'underline',
    decoy: 'winterize',
    confusable: { word: 'undercut', meaning: 'weaken' },
    sentence: 'The second failure underscored how fragile the whole system was.',
  },
  {
    id: 'wk-untenable', chapter: CH, concepts: POOL, band: 4,
    word: 'untenable', pos: 'adj', charge: 'neg',
    gloss: 'impossible to defend or to keep hold of',
    answer: 'indefensible',
    antonym: 'sustainable',
    related: 'weak',
    decoy: 'ridged',
    confusable: { word: 'untenanted', meaning: 'empty' },
    sentence: 'Once the memo surfaced, his position became untenable.',
  },
  {
    id: 'wk-usury', chapter: CH, concepts: POOL, band: 5,
    word: 'usury', pos: 'noun', charge: 'neg',
    gloss: 'lending money at an unreasonably high rate of interest',
    answer: 'extortion',
    antonym: 'charity',
    related: 'interest',
    decoy: 'tapestry',
    confusable: { word: 'usurpation', meaning: 'seizure' },
    sentence: 'The law against usury capped what any lender could charge.',
  },
  {
    id: 'wk-verdant', chapter: CH, concepts: POOL, band: 5,
    word: 'verdant', pos: 'adj', charge: 'pos',
    gloss: 'green with growing plants',
    answer: 'green',
    antonym: 'barren',
    related: 'rural',
    decoy: 'coarse',
    confusable: { word: 'verbose', meaning: 'wordy' },
    sentence: 'After the rains the whole valley turned verdant almost overnight.',
  },
  {
    id: 'wk-vim', chapter: CH, concepts: POOL, band: 4,
    word: 'vim', pos: 'noun', charge: 'pos',
    gloss: 'energy and enthusiasm',
    answer: 'vigor',
    antonym: 'lethargy',
    related: 'stamina',
    decoy: 'lantern',
    confusable: { word: 'whim', meaning: 'fancy' },
    sentence: 'She attacked the job with real vim for the first three weeks.',
  },
  {
    id: 'wk-virulent', chapter: CH, concepts: POOL, band: 4,
    word: 'virulent', pos: 'adj', charge: 'neg',
    gloss: 'extremely harmful, or bitterly hostile',
    answer: 'venomous',
    antonym: 'harmless',
    related: 'infectious',
    decoy: 'pleated',
    confusable: { word: 'virtuous', meaning: 'upright' },
    sentence: 'The pamphlet contained a virulent attack on the whole department.',
  },
  {
    id: 'wk-vitriol', chapter: CH, concepts: POOL, band: 4,
    word: 'vitriol', pos: 'noun', charge: 'neg',
    gloss: 'savagely bitter criticism',
    answer: 'venom',
    antonym: 'flattery',
    related: 'anger',
    decoy: 'cistern',
    confusable: { word: 'vitality', meaning: 'liveliness' },
    sentence: 'The comment section filled with vitriol within the hour.',
  },
  {
    id: 'wk-welter', chapter: CH, concepts: POOL, band: 5,
    word: 'welter', pos: 'noun', charge: 'neg',
    gloss: 'a confused, disorderly mass of things',
    answer: 'jumble',
    antonym: 'order',
    related: 'crowd',
    decoy: 'gantry',
    confusable: { word: 'swelter', meaning: 'heat' },
    sentence: 'The desk was buried under a welter of unopened envelopes.',
  },
]);
