// Multiple-choice option generation.
//
// Used in two places: the 126-item Exam Sim, and the opt-in assist toggle that
// becomes available from the hard tier onward in the open-response modes.
//
// WHY distractors are generated by re-composing against a DELIBERATELY WRONG
// GRAMMAR rather than by mutating the answer string: a randomly perturbed
// string is noise, and noise is easy to eliminate by feel without knowing any
// grammar, which would make the assist toggle a free pass. A distractor built
// by applying the wrong rule is a form the language would genuinely produce if
// one parameter were different — so eliminating it requires actually knowing
// which parameter this language has. It also makes a wrong pick diagnostic: the
// option carries the axis it got wrong, and results can name it.

import { compose } from './compose.js';
import { renderWord, renderWithStress, stressIndex } from './phonology.js';
import { pick, shuffle } from './rng.js';
import { normalizeAnswer, normalizeStressAnswer } from './grade.js';

// Only mutations whose morphemes already exist in this language's lexicon. A
// language with no subject particle cannot be re-composed as though it had one.
const SAFE_MUTATIONS = {
  adjPlacement: { pre: ['post'], post: ['pre'] },
  plural: { suffix: ['prefix'], prefix: ['suffix'], reduplication: ['ablaut'], ablaut: ['reduplication'], numeralOnly: [] },
  caseMarking: { nomAccSuffix: ['prefix'], prefix: ['nomAccSuffix'], ergative: [], particle: [], wordOrderOnly: [] },
  tense: { suffix: ['prefix'], prefix: ['suffix'], auxiliary: [], vowelChange: [] },
  negation: { prefix: ['suffix'], suffix: ['prefix'], circumfix: [], preverbalParticle: ['finalParticle'], finalParticle: ['preverbalParticle'] },
  definiteness: { prefix: ['suffix'], suffix: ['prefix'], clitic: [], none: [] },
  question: { initialParticle: ['finalParticle'], finalParticle: ['initialParticle'], verbSuffix: [], inversion: [] },
};

const AXIS_LABEL = {
  adjPlacement: 'adjective on the wrong side of the noun',
  plural: 'plural marked the wrong way',
  caseMarking: 'object marker in the wrong position',
  tense: 'tense marker in the wrong position',
  negation: 'negation in the wrong position',
  definiteness: '"the" in the wrong position',
  question: 'question marker in the wrong place',
  wordOrder: 'wrong word order',
  possessorFirst: 'owner and owned in the wrong order',
  omission: 'a required marker left off',
};

function withGrammar(lang, patch) {
  return { ...lang, grammar: { ...lang.grammar, ...patch } };
}

function surfaceOf(spec, lang) {
  try {
    return compose(spec, lang).surface;
  } catch {
    return null;
  }
}

function grammarDistractors(item, lang) {
  const out = [];
  if (!item.spec) return out;

  for (const [axis, table] of Object.entries(SAFE_MUTATIONS)) {
    const current = lang.grammar[axis];
    for (const alt of table[current] || []) {
      const s = surfaceOf(item.spec, withGrammar(lang, { [axis]: alt }));
      if (s) out.push({ text: s, why: AXIS_LABEL[axis] });
    }
  }

  const orders = ['SOV', 'SVO', 'VSO', 'VOS', 'OSV', 'OVS'].filter((o) => o !== lang.grammar.wordOrder);
  for (const o of orders) {
    const s = surfaceOf(item.spec, withGrammar(lang, { wordOrder: o }));
    if (s) out.push({ text: s, why: AXIS_LABEL.wordOrder });
  }

  if (item.spec.np?.possessor || item.spec.object?.possessor) {
    const s = surfaceOf(item.spec, withGrammar(lang, { possessorFirst: !lang.grammar.possessorFirst }));
    if (s) out.push({ text: s, why: AXIS_LABEL.possessorFirst });
  }

  return out;
}

function omissionDistractors(item, lang) {
  const out = [];
  const spec = item.spec;
  if (!spec) return out;

  const drop = (mutate) => {
    const copy = JSON.parse(JSON.stringify(spec));
    mutate(copy);
    const s = surfaceOf(copy, lang);
    if (s) out.push({ text: s, why: AXIS_LABEL.omission });
  };

  if (spec.kind === 'np') {
    if (spec.np.plural) drop((c) => { c.np.plural = false; });
    if (spec.np.definite) drop((c) => { c.np.definite = false; });
    if (spec.np.possessor) drop((c) => { c.np.possessor = null; });
  } else {
    if (spec.negated) drop((c) => { c.negated = false; });
    if (spec.question) drop((c) => { c.question = false; });
    if ((spec.verb.tense || 'present') !== 'present') drop((c) => { c.verb.tense = 'present'; });
    if (spec.subject?.plural) drop((c) => { c.subject.plural = false; });
    if (spec.object?.definite) drop((c) => { c.object.definite = false; });
  }
  return out;
}

function lexicalDistractors(item, lang, rng) {
  const out = [];
  const bags = [lang.lex.nouns, lang.lex.verbs, lang.lex.adjectives, lang.lex.pronouns];
  const answerNorm = normalizeAnswer(item.answer);
  for (const bag of bags) {
    for (const [meaning, syl] of Object.entries(bag)) {
      const form = renderWord(syl);
      if (normalizeAnswer(form) !== answerNorm) out.push({ text: form, why: `this is the word for "${meaning}"` });
    }
  }
  return shuffle(out, rng);
}

/**
 * Recomposes the item's own spec with one content word swapped. These keep the
 * grammar correct and change only the meaning, so they stay the same shape and
 * length as the answer — a top-up that does not look obviously wrong the way a
 * bare single word would next to a five-word sentence.
 */
function lexemeSwapDistractors(item, lang, rng) {
  const spec = item.spec;
  if (!spec) return [];
  const out = [];

  const emit = (mutate, why) => {
    const copy = JSON.parse(JSON.stringify(spec));
    mutate(copy);
    const s = surfaceOf(copy, lang);
    if (s) out.push({ text: s, why });
  };

  const nouns = Object.keys(lang.lex.nouns);
  const adjs = Object.keys(lang.lex.adjectives);
  const verbs = Object.keys(lang.lex.verbs);

  if (spec.kind === 'np') {
    for (const lex of nouns) {
      if (lex !== spec.np.lex) emit((c) => { c.np.lex = lex; }, `this says "${lex}", not "${spec.np.lex}"`);
    }
    if (spec.np.adjectives?.length) {
      for (const a of adjs) {
        if (a !== spec.np.adjectives[0]) emit((c) => { c.np.adjectives = [a]; }, `this says "${a}", not "${spec.np.adjectives[0]}"`);
      }
    }
    return shuffle(out, rng);
  }

  for (const v of verbs) {
    if (v !== spec.verb.lex) emit((c) => { c.verb.lex = v; }, `this says "${v}", not "${spec.verb.lex}"`);
  }
  if (spec.subject) {
    for (const lex of nouns) {
      if (lex !== spec.subject.lex) emit((c) => { c.subject.lex = lex; }, `wrong subject — this says "${lex}"`);
    }
  }
  if (spec.object) {
    for (const lex of nouns) {
      if (lex !== spec.object.lex) emit((c) => { c.object.lex = lex; }, `wrong object — this says "${lex}"`);
    }
  }
  return shuffle(out, rng);
}

function stressDistractors(item) {
  const out = [];
  if (/^\d+$/.test(item.answer)) {
    const n = Number(item.answer);
    for (const d of [1, 2, 3, 4, 5]) {
      if (d !== n) out.push({ text: String(d), why: 'stress on the wrong syllable' });
    }
    return out;
  }
  // Capitalise each of the other syllables in turn.
  const parts = item.answer.split('-');
  for (let i = 0; i < parts.length; i++) {
    const marked = parts.map((p, j) => (j === i ? p.toUpperCase() : p.toLowerCase())).join('-');
    if (marked !== item.answer) out.push({ text: marked, why: 'stress on the wrong syllable' });
  }
  return out;
}

/**
 * @param {object} item
 * @param {import('./language.js').Language} lang
 * @param {() => number} rng
 * @param {number} [count] - total options including the correct one
 * @returns {{options: {text: string, why: string|null}[], correctIndex: number}}
 */
/**
 * The identity function for comparing two options of THIS item.
 *
 * Stress items are answered in a notation where CAPITALISATION is the whole
 * content. normalizeAnswer folds case and strips hyphens, so every stress
 * variant would collapse to one string and the option list would dedupe itself
 * down to a single entry. Exported so callers that need to compare options
 * (the selftest, the results screen) use the same rule as the builder rather
 * than reimplementing it and drifting.
 *
 * @param {object} item
 * @returns {(s: string) => string}
 */
export function distractorKey(item) {
  const stressNotation = item.type === 'stress' && !/^\d+$/.test(item.answer);
  return stressNotation ? normalizeStressAnswer : normalizeAnswer;
}

export function buildDistractors(item, lang, rng, count = 4) {
  const key = distractorKey(item);
  const answerKey = key(item.answer);

  const pool = [];

  if (item.type === 'vocabReverse') {
    // Answered in English, so the options must be English.
    const meanings = Object.keys(lang.lex.nouns).concat(Object.keys(lang.lex.verbs), Object.keys(lang.lex.adjectives));
    for (const m of shuffle(meanings, rng)) {
      if (m !== item.answer) pool.push({ text: m, why: null });
    }
  } else if (item.type === 'stress') {
    pool.push(...stressDistractors(item));
  } else if (item.type === 'vocab') {
    pool.push(...lexicalDistractors(item, lang, rng));
  } else {
    pool.push(...shuffle(grammarDistractors(item, lang), rng));
    pool.push(...shuffle(omissionDistractors(item, lang), rng));
    // A noun phrase with no marked features has no grammar left to get wrong —
    // nothing to pluralise, no adjective to misplace, no constituents to
    // reorder — so the mutation pool comes back empty. Swapping the content
    // word is the only meaningful way to be wrong about "dog", and it is what
    // the real exam's vocabulary items do too.
    pool.push(...lexemeSwapDistractors(item, lang, rng));
    pool.push(...lexicalDistractors(item, lang, rng));
  }

  const seen = new Set([answerKey]);
  const chosen = [];
  for (const cand of pool) {
    const n = key(cand.text);
    if (seen.has(n) || !cand.text.trim()) continue;
    seen.add(n);
    chosen.push(cand);
    if (chosen.length === count - 1) break;
  }

  // A language simple enough that fewer than three wrong forms exist gets a
  // shorter option list rather than padding with duplicates of the answer.
  const options = shuffle([{ text: item.answer, why: null }, ...chosen], rng);
  return {
    options,
    correctIndex: options.findIndex((o) => key(o.text) === answerKey),
  };
}

/**
 * Which grammatical axis a wrong pick got wrong, for the results screen.
 * @param {object} item
 * @param {string} picked
 * @returns {string|null}
 */
export function diagnoseChoice(item, picked) {
  if (!item.choices) return null;
  const opt = item.choices.options.find((o) => normalizeAnswer(o.text) === normalizeAnswer(picked));
  return opt ? opt.why : null;
}

export { pick, stressIndex, renderWithStress };
