export const SEED_DATA = [
  {
    id: 'seed-1',
    title: 'The Shawshank Redemption',
    type: 'movie',
    coverImage: null,
    additionalImages: [],
    notes: "A timeless story about hope and perseverance. Morgan Freeman's narration is perfect, and the ending is deeply satisfying. One of those films that sticks with you.",
    rating: 5,
    status: 'completed',
    genre: 'Drama',
    year: 1994,
    director: 'Frank Darabont',
    author: '',
    dateAdded: '2024-01-10',
    dateCompleted: '2024-01-12',
  },
  {
    id: 'seed-2',
    title: 'Dune',
    type: 'book',
    coverImage: null,
    additionalImages: [],
    notes: 'Dense but incredibly rewarding world-building. The ecological and political systems feel genuinely alien yet coherent. The second half picks up considerably.',
    rating: 4,
    status: 'completed',
    genre: 'Science Fiction',
    year: 1965,
    director: '',
    author: 'Frank Herbert',
    dateAdded: '2024-02-01',
    dateCompleted: '2024-02-28',
  },
  {
    id: 'seed-3',
    title: 'Oppenheimer',
    type: 'movie',
    coverImage: null,
    additionalImages: [],
    notes: '',
    rating: null,
    status: 'plan',
    genre: 'Biography / Drama',
    year: 2023,
    director: 'Christopher Nolan',
    author: '',
    dateAdded: '2024-03-01',
    dateCompleted: null,
  },
  {
    id: 'seed-4',
    title: 'The Name of the Wind',
    type: 'book',
    coverImage: null,
    additionalImages: [],
    notes: 'Kvothe is a compelling narrator — arrogant but self-aware about it. The prose is genuinely beautiful for a fantasy novel.',
    rating: null,
    status: 'in-progress',
    genre: 'Fantasy',
    year: 2007,
    director: '',
    author: 'Patrick Rothfuss',
    dateAdded: '2024-03-15',
    dateCompleted: null,
  },
  {
    id: 'seed-5',
    title: 'Parasite',
    type: 'movie',
    coverImage: null,
    additionalImages: [],
    notes: 'Bong Joon-ho earns every award this film received. The tonal shift in the second half is stunning. A masterclass in genre subversion.',
    rating: 5,
    status: 'completed',
    genre: 'Thriller / Dark Comedy',
    year: 2019,
    director: 'Bong Joon-ho',
    author: '',
    dateAdded: '2024-01-20',
    dateCompleted: '2024-01-21',
  },
  {
    id: 'seed-6',
    title: 'Sapiens',
    type: 'book',
    coverImage: null,
    additionalImages: [],
    notes: 'Big-picture history that reframes how I think about human civilization. Some arguments are speculative but always thought-provoking.',
    rating: 4,
    status: 'completed',
    genre: 'Non-Fiction / History',
    year: 2011,
    director: '',
    author: 'Yuval Noah Harari',
    dateAdded: '2024-02-10',
    dateCompleted: '2024-02-20',
  },
];
