// Assembling a drill from the three places questions come from.
//
// Until now DrillRunner mixed generated + bank itself, and the MISS POOL - Trey's
// requirement 12, "an ever-changing ever-adjusting review-test" - was captured on every wrong
// answer and then never used. This is where it finally feeds back in.
//
// Three sources, in priority order:
//   1. MISS POOL   ~10% of slots (his number). Material you got wrong, resurfaced gently.
//   2. GENERATED   unlimited, non-repeating, but only where a template exists.
//   3. BANK        official OATTS items and migrated ASVAB copies; covers subtests whose
//                  template phase has not been built yet.
//
// The rate is deliberately gentle. A heavy injection turns every session into a punishment
// loop and kills adoption, which is the failure mode that ended the ASVAB deck.

import { buildDrill, generateInstance, getTemplate, composeSeed } from './generator.js';
import { composeDrill } from './bank.js';
import { MISS_INJECTION_RATE } from './afoqtSpec.js';

/**
 * Two flavours of resurfacing, and both are offered on purpose:
 *
 *   'exact'   - the identical question, regenerated byte-for-byte from (templateId, seed).
 *               Good for "what actually went wrong here".
 *   'sibling' - a fresh instance of the same template. Tests the CONCEPT rather than memory
 *               of one item, and is the more valuable of the two.
 *
 * Weighted toward siblings for that reason, but exact replays stay in the mix so a miss can
 * be re-read as it was.
 */
const SIBLING_SHARE = 0.65;

/**
 * @param {object} progress   afoqtStorage progress blob
 * @param {string} subtest
 * @param {number} slots      how many miss-pool questions to produce
 * @param {() => number} rng
 * @returns {object[]} instances, possibly fewer than `slots` if the pool is thin
 */
export function drawFromMissPool(progress, subtest, slots, rng, sheet = null) {
  const pool = Object.entries(progress?.missPool ?? {})
    .filter(([templateId]) => getTemplate(templateId)?.subtest === subtest);
  if (pool.length === 0 || slots <= 0) return [];

  const out = [];
  for (let i = 0; i < slots; i++) {
    const [templateId, entry] = pool[Math.floor(rng() * pool.length)];
    const t = getTemplate(templateId);
    // A template that shares a figure across a run is ALWAYS resurfaced as a sibling on the
    // run's own figure, never as an exact replay. Two reasons, and they point the same way:
    // an exact replay would drop a second table into the middle of a drill built on one, and
    // on Table Reading the exact item is worthless anyway - remembering that (+3, -7) held 084
    // on some grid last Tuesday is not the skill. The concept is the lookup, so the sibling is
    // the only meaningful thing to bring back.
    const sheeted = t?.sheet && sheet != null;
    const wantSibling = sheeted || rng() < SIBLING_SHARE || !entry.seeds?.length;
    const seed = sheeted
      ? composeSeed(sheet, Math.floor(rng() * 0xfff))
      : wantSibling
        ? Math.floor(rng() * 0xffffffff) >>> 0
        : entry.seeds[Math.floor(rng() * entry.seeds.length)];
    const inst = generateInstance(templateId, seed);
    if (inst) out.push({ ...inst, fromMissPool: true, missFlavour: wantSibling ? 'sibling' : 'exact' });
  }
  return out;
}

/**
 * Build a full drill queue.
 *
 * `ignoreMissPool` exists for exam mode: a full simulator run has to be an UNBIASED sample or
 * the score means nothing. That is also the automatic half of Trey's "clean slate" - an honest
 * baseline is always available without him having to reset anything by hand.
 *
 * `concepts` scopes a drill to one chapter's material, which is what the curriculum's
 * test-out gate and mastery check run on.
 */
export function assembleDrill({
  subtest,
  count,
  rng,
  progress = null,
  bands = null,
  concepts = null,
  includeStretch = false,
  bankRatio = 0.5,
  ignoreMissPool = false,
  exam = false,
  missRate = MISS_INJECTION_RATE,
}) {
  // An exam run is a MEASUREMENT, so it gets neither of the two things that make a practice
  // drill useful: no miss-pool weighting (which would bias the sample toward material already
  // known to be weak) and no training-aid templates. This is the automatic half of Trey's
  // clean slate - an honest baseline is always available without resetting anything by hand.
  const honest = exam || ignoreMissPool;
  // One figure for the whole run, allocated here so the miss-pool draw and the fresh questions
  // land on the same one. Subtests without a shared figure ignore it entirely.
  const runSheet = Math.floor(rng() * 0x100000);

  const missSlots = honest || !progress
    ? 0
    : Math.min(Math.floor(count * missRate), Math.max(0, count - 1));
  const misses = drawFromMissPool(progress, subtest, missSlots, rng, runSheet);

  const remaining = count - misses.length;
  const generated = buildDrill({
    subtest,
    count: remaining,
    rng,
    includeStretch,
    distinct: true,
    sheet: runSheet,
    exam,
    filter: (t) => matchesScope(t, bands, concepts),
  });

  // A chapter-scoped drill must not pull in bank items - they carry no concept tags, so they
  // cannot be confirmed to belong to this chapter, and an untraceable question inside a
  // mastery check is exactly what Doctrine rule 2 forbids.
  const body = concepts
    ? generated.slice(0, remaining)
    : composeDrill({ subtest, count: remaining, rng, generated, bankRatio });

  return groupByFigure(shuffleInPlace([...misses, ...body], rng));
}

/**
 * Keep questions that share a printed figure next to each other.
 *
 * The shuffle above exists to mix miss-pool items in among fresh ones, and for a subtest with
 * one figure per run it costs nothing. But Block Counting rotates piles every six questions,
 * and shuffling scattered them - the queue jumped to a different pile almost every question,
 * so a candidate re-orients to a new drawing 30 times instead of 5. That is both unlike the
 * real test and harder than it.
 *
 * Figure order and the order within a figure both stay shuffled; only the grouping is imposed.
 * A no-op for every subtest that does not rotate.
 */
function groupByFigure(questions) {
  const groups = new Map();
  for (const q of questions) {
    const key = q.render?.sheetSeed ?? '_';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(q);
  }
  return [...groups.values()].flat();
}

function matchesScope(t, bands, concepts) {
  if (bands && !bands.includes(t.band)) return false;
  if (concepts && !(t.concepts ?? []).some((c) => concepts.includes(c))) return false;
  return true;
}

function shuffleInPlace(arr, rng) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
