export const SCHEMA_TEXT = [
  { table: 'users',    columns: 'id, name, email, age, city'               },
  { table: 'orders',   columns: 'id, user_id, amount, created_at'          },
  { table: 'products', columns: 'id, name, category, price'                },
];

export const SQL_KEYWORDS = [
  'SELECT … FROM …',
  'WHERE condition',
  'ORDER BY col [ASC|DESC]',
  'LIMIT n',
  'GROUP BY col',
  'HAVING condition',
  '[INNER|LEFT] JOIN … ON …',
  'COUNT(*), SUM(col), AVG(col)',
  'INSERT INTO … VALUES …',
  'UPDATE … SET … WHERE …',
  'DELETE FROM … WHERE …',
];

export const challengeData = {
  beginner: [
    {
      id: 'b1', type: 'fill-blank', title: 'Select Everything',
      prompt: 'Grab every column and every row from the users table.',
      template: 'SELECT ___ FROM users;',
      blanks: ['*'],
      tip: 'The wildcard character for "all columns" is a single symbol.',
      tipReveal: '* means every column — SELECT * gets them all',
      xp: 10,
    },
    {
      id: 'b2', type: 'multiple-choice', title: 'Find the Austinites',
      prompt: "Which query finds all users who live in Austin?",
      options: [
        { text: "SELECT * FROM users WHERE city = 'Austin';",     correct: true  },
        { text: "SELECT * WHERE city = 'Austin' FROM users;",     correct: false },
        { text: "SELECT city FROM users WHERE * = 'Austin';",     correct: false },
        { text: "GET * FROM users WHERE city = 'Austin';",        correct: false },
      ],
      tip: 'SQL keywords must appear in a specific order.',
      tipReveal: 'SELECT → FROM → WHERE is the required order',
      xp: 10,
    },
    {
      id: 'b3', type: 'fill-blank', title: 'Add a Filter',
      prompt: 'You only want users from Denver. What keyword introduces the filter?',
      template: "SELECT name, email FROM users ___ city = 'Denver';",
      blanks: ['WHERE'],
      tip: 'This keyword comes after FROM and filters rows before returning them.',
      tipReveal: 'WHERE filters rows based on a condition',
      xp: 10,
    },
    {
      id: 'b4', type: 'fill-blank', title: 'Oldest First',
      prompt: 'Sort users by age, oldest at the top.',
      template: 'SELECT * FROM users ORDER BY age ___;',
      blanks: ['DESC'],
      tip: 'Ascending = smallest first. You want the opposite direction.',
      tipReveal: 'DESC = descending = largest/oldest first',
      xp: 10,
    },
    {
      id: 'b5', type: 'multiple-choice', title: 'Just Give Me Five',
      prompt: 'Which query returns only the first 5 products?',
      options: [
        { text: 'SELECT * FROM products LIMIT 5;',            correct: true  },
        { text: 'SELECT 5 FROM products;',                    correct: false },
        { text: 'SELECT * FROM products WHERE count = 5;',    correct: false },
        { text: 'SELECT * FROM products MAX 5;',              correct: false },
      ],
      tip: 'There is one keyword that means "stop after N rows."',
      tipReveal: 'LIMIT N caps the result at N rows',
      xp: 10,
    },
    {
      id: 'b6', type: 'fix-bug', title: 'Spot the Typos',
      prompt: 'Two keywords are misspelled. Fix them.',
      brokenQuery: 'SELEC * FORM users;',
      accepted: ['SELECT * FROM users;', 'SELECT * FROM users'],
      tip: 'Look carefully at the first word and the third word.',
      tipReveal: 'SELEC → SELECT and FORM → FROM',
      xp: 15,
    },
    {
      id: 'b7', type: 'what-returns', title: 'What Comes Back?',
      prompt: 'What does this query return?',
      queryDisplay: 'SELECT COUNT(*) FROM users;',
      options: [
        { text: 'All users in the table',                            correct: false },
        { text: 'A single number: how many users exist',             correct: true  },
        { text: 'The users table with an extra count column',        correct: false },
        { text: 'An error — you cannot SELECT COUNT',                correct: false },
      ],
      tip: 'COUNT(*) is an aggregate function that counts something.',
      tipReveal: 'COUNT(*) returns exactly one number: the total row count',
      xp: 10,
    },
    {
      id: 'b8', type: 'write-query', title: 'Write It Yourself',
      prompt: 'Get the name and age of every user, sorted A to Z by name.',
      accepted: [
        'SELECT name, age FROM users ORDER BY name',
        'SELECT name, age FROM users ORDER BY name ASC',
        'select name, age from users order by name',
        'select name, age from users order by name asc',
      ],
      tip: 'You need SELECT, FROM, and ORDER BY. A–Z is which direction?',
      tipReveal: 'ASC = ascending = A to Z (it\'s also the default if you omit it)',
      xp: 20,
    },
  ],

  intermediate: [
    {
      id: 'i1', type: 'fill-blank', title: 'Count by City',
      prompt: 'Count how many users live in each city.',
      template: 'SELECT city, COUNT(*) AS total FROM users ___ BY city;',
      blanks: ['GROUP'],
      tip: 'This clause collapses rows that share a value into one group.',
      tipReveal: 'GROUP BY organizes rows so each unique value = one result row',
      xp: 15,
    },
    {
      id: 'i2', type: 'write-query', title: 'Double Filter',
      prompt: 'Return the name and email of users older than 30 who live in Chicago.',
      accepted: [
        "SELECT name, email FROM users WHERE age > 30 AND city = 'Chicago'",
        "select name, email from users where age > 30 and city = 'chicago'",
        "SELECT name, email FROM users WHERE city = 'Chicago' AND age > 30",
        "select name, email from users where city = 'chicago' and age > 30",
      ],
      tip: 'You need two WHERE conditions. Chain them with a keyword meaning "both must be true."',
      tipReveal: 'Use AND between conditions: WHERE age > 30 AND city = \'Chicago\'',
      xp: 20,
    },
    {
      id: 'i3', type: 'fill-blank', title: 'Total Spending',
      prompt: "Add up each user's total amount spent across all of their orders.",
      template: 'SELECT user_id, ___(amount) AS total FROM orders GROUP BY user_id;',
      blanks: ['SUM'],
      tip: 'You need an aggregate function that adds numbers together.',
      tipReveal: 'SUM(col) adds up all values in a column within each group',
      xp: 15,
    },
    {
      id: 'i4', type: 'multiple-choice', title: 'HAVING vs WHERE',
      prompt: 'Which query correctly finds cities that have more than 5 users?',
      options: [
        { text: 'SELECT city, COUNT(*) FROM users WHERE COUNT(*) > 5 GROUP BY city;', correct: false },
        { text: 'SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) > 5;', correct: true  },
        { text: 'SELECT city, COUNT(*) FROM users HAVING COUNT(*) > 5;',               correct: false },
        { text: 'SELECT city, COUNT(*) FROM users GROUP BY city WHERE COUNT(*) > 5;',  correct: false },
      ],
      tip: 'WHERE runs before grouping. You need something that runs after the groups are formed.',
      tipReveal: 'HAVING filters groups — it can use aggregate functions; WHERE cannot',
      xp: 15,
    },
    {
      id: 'i5', type: 'fill-blank', title: 'Left or Inner?',
      prompt: 'Get every user and their orders. Include users who have no orders at all.',
      template: 'SELECT users.name, orders.amount FROM users ___ JOIN orders ON users.id = orders.user_id;',
      blanks: ['LEFT'],
      tip: 'INNER JOIN drops non-matching rows. You want ALL users, even empty-handed ones.',
      tipReveal: 'LEFT JOIN keeps every row from the left table, regardless of matches',
      xp: 20,
    },
    {
      id: 'i6', type: 'write-query', title: 'Update a Record',
      prompt: "Change user id 12's city to 'Seattle'.",
      accepted: [
        "UPDATE users SET city = 'Seattle' WHERE id = 12",
        "update users set city = 'Seattle' where id = 12",
        "UPDATE users SET city = 'seattle' WHERE id = 12",
        "update users set city = 'seattle' where id = 12",
        "UPDATE users SET city = 'Seattle' WHERE id = 12;",
      ],
      tip: 'You need UPDATE, SET, and WHERE. Leave off WHERE and you change every single user.',
      tipReveal: 'UPDATE tablename SET column = value WHERE condition',
      xp: 20,
    },
    {
      id: 'i7', type: 'fix-bug', title: 'Fix the JOIN',
      prompt: 'This JOIN links the wrong columns. Fix it.',
      brokenQuery: 'SELECT users.name, orders.amount FROM orders INNER JOIN users ON orders.id = users.id;',
      accepted: [
        'SELECT users.name, orders.amount FROM orders INNER JOIN users ON orders.user_id = users.id;',
        'SELECT users.name, orders.amount FROM orders INNER JOIN users ON users.id = orders.user_id;',
        'select users.name, orders.amount from orders inner join users on orders.user_id = users.id;',
        'select users.name, orders.amount from orders inner join users on orders.user_id = users.id',
        'select users.name, orders.amount from orders inner join users on users.id = orders.user_id',
      ],
      tip: 'orders has a column that links back to users. It is not orders.id.',
      tipReveal: 'orders.user_id is the foreign key that connects to users.id',
      xp: 25,
    },
    {
      id: 'i8', type: 'write-query', title: 'Clean Up',
      prompt: 'Delete all orders where the amount is 0.',
      accepted: [
        'DELETE FROM orders WHERE amount = 0',
        'delete from orders where amount = 0',
        'DELETE FROM orders WHERE amount = 0;',
      ],
      tip: 'Always include WHERE when deleting, or you nuke the entire table.',
      tipReveal: 'DELETE FROM table WHERE condition',
      xp: 20,
    },
  ],

  advanced: [
    {
      id: 'a1', type: 'write-query', title: 'Power Users',
      prompt: 'Find users who have placed more than 3 orders. Return user_id and their order count labeled "order_count".',
      accepted: [
        'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id HAVING COUNT(*) > 3',
        'select user_id, count(*) as order_count from orders group by user_id having count(*) > 3',
        'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id HAVING COUNT(*) > 3;',
      ],
      tip: 'GROUP BY user_id, COUNT the rows per group, then filter the groups.',
      tipReveal: 'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id HAVING COUNT(*) > 3',
      xp: 30,
    },
    {
      id: 'a2', type: 'fill-blank', title: 'Subquery Sniper',
      prompt: 'Find names of users who have ever placed an order over $500. Use a subquery.',
      template: 'SELECT name FROM users WHERE id IN (SELECT ___ FROM orders WHERE amount > 500);',
      blanks: ['user_id'],
      tip: 'The inner query must return the column that matches users.id.',
      tipReveal: 'user_id is the foreign key connecting orders back to users',
      xp: 30,
    },
    {
      id: 'a3', type: 'write-query', title: 'Revenue by City',
      prompt: "Join users and orders to get the average order amount per city. Label the average 'avg_order'.",
      accepted: [
        'SELECT users.city, AVG(orders.amount) AS avg_order FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city',
        'SELECT users.city, AVG(orders.amount) AS avg_order FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.city',
        'select users.city, avg(orders.amount) as avg_order from orders inner join users on orders.user_id = users.id group by users.city',
        'select users.city, avg(orders.amount) as avg_order from users inner join orders on users.id = orders.user_id group by users.city',
        'SELECT users.city, AVG(orders.amount) AS avg_order FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.city',
        'select users.city, avg(orders.amount) as avg_order from orders join users on orders.user_id = users.id group by users.city',
      ],
      tip: 'You need JOIN to connect tables, AVG() to average amounts, GROUP BY city for grouping.',
      tipReveal: 'JOIN users ON user_id, then GROUP BY users.city, SELECT AVG(orders.amount)',
      xp: 35,
    },
    {
      id: 'a4', type: 'what-returns', title: 'Read the Room',
      prompt: 'What does this query return?',
      queryDisplay: `SELECT city, COUNT(*) AS users, AVG(age) AS avg_age
FROM users
GROUP BY city
HAVING COUNT(*) >= 3
ORDER BY avg_age DESC;`,
      options: [
        { text: 'All cities with user counts',                                                                  correct: false },
        { text: 'Cities that have 3+ users, with count and average age, sorted oldest-average first',          correct: true  },
        { text: 'The 3 oldest users per city',                                                                  correct: false },
        { text: 'An error — you cannot mix GROUP BY and ORDER BY',                                             correct: false },
      ],
      tip: 'Read each clause. HAVING filters which groups survive. ORDER BY DESC sorts the final output.',
      tipReveal: 'HAVING COUNT(*) >= 3 drops small cities. ORDER BY avg_age DESC = highest average age first',
      xp: 30,
    },
    {
      id: 'a5', type: 'fix-bug', title: 'Aggregate Error',
      prompt: 'This query should find high-revenue cities but has a logic error. Fix it.',
      brokenQuery: `SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id WHERE SUM(orders.amount) > 1000 GROUP BY users.city;`,
      accepted: [
        'SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING SUM(orders.amount) > 1000',
        'select users.city, sum(orders.amount) as revenue from orders inner join users on orders.user_id = users.id group by users.city having sum(orders.amount) > 1000',
        'SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING SUM(orders.amount) > 1000;',
      ],
      tip: 'WHERE cannot use aggregate functions like SUM(). Move the filter to after the grouping.',
      tipReveal: 'Replace WHERE SUM() with HAVING SUM() and move it after GROUP BY',
      xp: 40,
    },
    {
      id: 'a6', type: 'write-query', title: 'Top 3 Spenders',
      prompt: "Find the top 3 users by total amount spent. Return their name and total labeled 'total_spent'. Most spent first.",
      accepted: [
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.id, users.name ORDER BY total_spent DESC LIMIT 3",
        "select users.name, sum(orders.amount) as total_spent from orders inner join users on orders.user_id = users.id group by users.id, users.name order by total_spent desc limit 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
        "select users.name, sum(orders.amount) as total_spent from orders join users on orders.user_id = users.id group by users.name order by total_spent desc limit 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
        "select users.name, sum(orders.amount) as total_spent from users inner join orders on users.id = orders.user_id group by users.name order by total_spent desc limit 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.id, users.name ORDER BY total_spent DESC LIMIT 3;",
      ],
      tip: 'JOIN → GROUP BY user → SUM amount → ORDER BY that sum DESC → LIMIT 3.',
      tipReveal: 'JOIN, GROUP BY users.name, SELECT SUM(orders.amount) AS total_spent, ORDER BY total_spent DESC, LIMIT 3',
      xp: 40,
    },
  ],
};
