// SQL Quest — all game data

export const SCHEMA_TEXT = [
  { table: 'users',    columns: 'id, name, email, age, city' },
  { table: 'orders',   columns: 'id, user_id, amount, created_at' },
  { table: 'products', columns: 'id, name, category, price' },
];

export const SQL_KEYWORDS = [
  'SELECT … FROM …',
  'WHERE condition',
  'ORDER BY col [ASC|DESC]',
  'LIMIT n',
  'GROUP BY col',
  'HAVING condition',
  '[INNER|LEFT] JOIN … ON …',
  'COUNT(*), SUM(col), AVG(col)',
  'UPDATE … SET … WHERE …',
  'DELETE FROM … WHERE …',
];

// ── Tutorial ─────────────────────────────────────────────────────────────────
// 10 progressive missions. Keyword chips help beginners build queries.

export const tutorialMissions = [
  {
    id: 'tut1',
    title: 'Hello, Database',
    concept: 'SELECT *',
    story: "You've awakened in the DataRealm — a digital world built entirely of tables and rows. Every action here is a SQL query. The first incantation every query-caster must master: retrieve EVERYTHING from a table. The symbol `*` means \"all columns.\"",
    challenge: {
      type: 'fill-blank',
      template: 'SELECT ___ FROM users;',
      blanks: ['*'],
      tip: 'What single character means "all columns"?',
      tipReveal: '* is the wildcard — SELECT * means select all columns',
    },
    keywords: ['SELECT', '*', 'FROM', 'users'],
    xp: 40,
    completion: "SELECT * FROM users returns every column and every row. Simple and powerful — one of the most-used commands in SQL.",
  },
  {
    id: 'tut2',
    title: 'Choose Your Columns',
    concept: 'SELECT specific columns',
    story: "Query-Master Orm appears. 'Selecting everything wastes resources. Be precise — list only the columns you need, separated by commas. You can name as many as you want.'",
    challenge: {
      type: 'write-query',
      prompt: 'Return only the name and email columns from the users table.',
      accepted: [
        'SELECT name, email FROM users',
        'select name, email from users',
        'SELECT name, email FROM users;',
        'select name, email from users;',
      ],
      tip: 'List specific column names separated by commas after SELECT.',
      tipReveal: 'SELECT name, email FROM users',
    },
    keywords: ['SELECT', 'FROM', 'name', 'email', 'users', ','],
    xp: 50,
    completion: "SELECT col1, col2 FROM table returns only those columns. The order you list them is the order they appear in the result.",
  },
  {
    id: 'tut3',
    title: 'The WHERE Spell',
    concept: 'WHERE clause',
    story: "'The DataRealm holds thousands of users,' Orm explains. 'You don't need all of them. WHERE is your filter — it checks every row and keeps only those where the condition is true. Think: SELECT everything FROM users, BUT ONLY IF...'",
    challenge: {
      type: 'fill-blank',
      template: "SELECT * FROM users ___ city = 'Austin';",
      blanks: ['WHERE'],
      tip: 'What keyword introduces a filter condition after FROM?',
      tipReveal: "WHERE filters rows — only rows where city = 'Austin' pass through",
    },
    keywords: ['WHERE', '='],
    xp: 50,
    completion: "WHERE is one of SQL's most powerful clauses. It evaluates each row and returns only rows where the condition is true.",
  },
  {
    id: 'tut4',
    title: 'Greater Than, Less Than',
    concept: 'Comparison operators',
    story: "'Not all conditions check equality,' Orm says. 'Sometimes you need a range. The operators >, <, >=, <= work just like math. Try filtering by age.'",
    challenge: {
      type: 'write-query',
      prompt: 'Find all users who are older than 30.',
      accepted: [
        'SELECT * FROM users WHERE age > 30',
        'select * from users where age > 30',
        'SELECT * FROM users WHERE age > 30;',
        'select * from users where age > 30;',
      ],
      tip: 'Use WHERE with the > operator to compare age.',
      tipReveal: 'SELECT * FROM users WHERE age > 30',
    },
    keywords: ['SELECT', '*', 'FROM', 'users', 'WHERE', 'age', '>', '30'],
    xp: 55,
    completion: "WHERE age > 30 filters out anyone 30 and under. You can also use < (less), >= (greater or equal), <= (less or equal), != (not equal).",
  },
  {
    id: 'tut5',
    title: 'Bring Order',
    concept: 'ORDER BY',
    story: "'Results come back in no guaranteed order,' Orm warns. 'ORDER BY sorts your data. ASC = ascending = smallest first. DESC = descending = largest first. Without it, the database decides — and it can change each time.'",
    challenge: {
      type: 'fill-blank',
      template: 'SELECT * FROM users ORDER BY age ___;',
      blanks: ['DESC'],
      tip: 'Oldest first = largest age number first. Which direction is that?',
      tipReveal: 'DESC (descending) puts the largest numbers at the top',
    },
    keywords: ['ORDER BY', 'ASC', 'DESC'],
    xp: 55,
    completion: "ORDER BY age DESC puts the oldest users first. ASC is the default — if you leave it off, SQL assumes ascending (smallest first).",
  },
  {
    id: 'tut6',
    title: 'Know Your Limits',
    concept: 'LIMIT',
    story: "'A query without LIMIT can return millions of rows,' Orm says grimly. 'In production, that crashes apps. LIMIT caps how many rows come back. Always use it when you only need a sample.'",
    challenge: {
      type: 'write-query',
      prompt: 'Get all columns from users, but return only the first 5 rows.',
      accepted: [
        'SELECT * FROM users LIMIT 5',
        'select * from users limit 5',
        'SELECT * FROM users LIMIT 5;',
        'select * from users limit 5;',
      ],
      tip: 'LIMIT goes at the very end of the query.',
      tipReveal: 'SELECT * FROM users LIMIT 5',
    },
    keywords: ['SELECT', '*', 'FROM', 'users', 'LIMIT', '5'],
    xp: 55,
    completion: "LIMIT 5 stops after 5 rows. Combined with ORDER BY, it's powerful: ORDER BY age DESC LIMIT 1 gets the single oldest user.",
  },
  {
    id: 'tut7',
    title: 'The Counting Arts',
    concept: 'COUNT(*)',
    story: "'COUNT() is an aggregate function,' Orm explains. 'Instead of returning rows, it returns a single summary number. COUNT(*) counts every row — including NULLs.'",
    challenge: {
      type: 'write-query',
      prompt: 'Count the total number of users in the users table.',
      accepted: [
        'SELECT COUNT(*) FROM users',
        'select count(*) from users',
        'SELECT COUNT(*) FROM users;',
        'SELECT COUNT(*) AS total FROM users',
        'select count(*) as total from users',
      ],
      tip: 'Use COUNT(*) as the thing you are selecting.',
      tipReveal: 'SELECT COUNT(*) FROM users',
    },
    keywords: ['SELECT', 'COUNT(*)', 'FROM', 'users', 'AS', 'total'],
    xp: 60,
    completion: "COUNT(*) returns one number: the total row count. AS total renames the output column. Other aggregates: SUM(col), AVG(col), MIN(col), MAX(col).",
  },
  {
    id: 'tut8',
    title: 'Group Dynamics',
    concept: 'GROUP BY',
    story: "'Users divide themselves by city,' Orm explains. 'GROUP BY collapses all rows sharing the same value into a single group. Combined with COUNT() or SUM(), it answers: how many X per Y?'",
    challenge: {
      type: 'fill-blank',
      template: 'SELECT city, COUNT(*) AS total FROM users ___ BY city;',
      blanks: ['GROUP'],
      tip: 'What clause groups rows by a shared column value?',
      tipReveal: 'GROUP BY city collapses all users in the same city into one result row',
    },
    keywords: ['GROUP', 'BY'],
    xp: 65,
    completion: "GROUP BY + COUNT(*) is one of the most common SQL patterns. It gives you aggregates per category — users per city, orders per user, revenue per product.",
  },
  {
    id: 'tut9',
    title: 'Bridging Tables',
    concept: 'INNER JOIN',
    story: "'Users and orders live in separate tables,' Orm says, 'connected by a foreign key: users.id matches orders.user_id. JOIN bridges them. INNER JOIN returns only rows that match in BOTH tables.'",
    challenge: {
      type: 'fill-blank',
      template: 'SELECT users.name, orders.amount\nFROM users ___ JOIN orders ON users.id = orders.user_id;',
      blanks: ['INNER'],
      tip: 'The most common JOIN — returns only rows with a match in both tables.',
      tipReveal: 'INNER JOIN connects rows where the ON condition is true',
    },
    keywords: ['INNER', 'JOIN', 'ON'],
    xp: 70,
    completion: "INNER JOIN links rows where the ON condition matches. users.id = orders.user_id is the 'bridge.' Without ON, you'd get every possible row combination — rarely what you want.",
  },
  {
    id: 'tut10',
    title: 'The Final Trial',
    concept: 'Full query synthesis',
    story: "Orm steps back. The keyword bank disappears. 'You have learned the fundamental spells. Now prove you can combine them without help. Find the top 3 users by total spending — names and totals, highest spender first. The Dungeon opens when you succeed.'",
    challenge: {
      type: 'write-query',
      prompt: "Find the top 3 users by total amount spent. Return name and total (labeled 'total_spent'), sorted highest to lowest.",
      accepted: [
        'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3',
        'select users.name, sum(orders.amount) as total_spent from orders inner join users on orders.user_id = users.id group by users.name order by total_spent desc limit 3',
        'SELECT users.name, SUM(orders.amount) AS total_spent FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3',
        'select users.name, sum(orders.amount) as total_spent from users inner join orders on users.id = orders.user_id group by users.name order by total_spent desc limit 3',
        'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3',
        'select users.name, sum(orders.amount) as total_spent from orders join users on orders.user_id = users.id group by users.name order by total_spent desc limit 3',
        'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.id, users.name ORDER BY total_spent DESC LIMIT 3',
        'select users.name, sum(orders.amount) as total_spent from orders inner join users on orders.user_id = users.id group by users.id, users.name order by total_spent desc limit 3',
      ],
      tip: 'You need: JOIN the tables, SUM the amounts grouped by user, ORDER by the sum, LIMIT to 3.',
      tipReveal: "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
    },
    keywords: [],
    xp: 100,
    completion: "You have mastered the core of SQL — JOIN, GROUP BY, SUM, ORDER BY, and LIMIT in one query. Tutorial complete. The Dungeon awaits.",
  },
];

// ── Dungeon Floors ───────────────────────────────────────────────────────────
// 4 floors. Each has 3 regular enemies + 1 boss.
// Wrong answers deal damage to the player. High stakes = real learning.

export const dungeonFloors = [
  {
    id: 'floor1',
    name: 'The Corrupted Cave',
    emoji: '🕳️',
    theme: 'SELECT, WHERE, ORDER BY',
    levelRequired: 1,
    intro: "Rogue data goblins have infested the entry-level server. Their queries are primitive but they block the path forward. Each wrong answer costs you HP.",
    clearText: "The cave is purged. A passage to the Aggregate Swamp opens in the distance...",
    enemies: [
      {
        id: 'f1e1',
        name: 'Cave Goblin',
        emoji: '👺',
        title: 'Basic Corruptor',
        hp: 40, attack: 10, rewardXP: 25, isBoss: false,
        dialogue: "HALT, query-caster! Retrieve ALL rows and columns from the users table — or face my club!",
        challenge: {
          type: 'fill-blank',
          template: 'SELECT ___ FROM users;',
          blanks: ['*'],
          tip: 'What single character means "all columns"?',
          tipReveal: '* — the wildcard that selects every column',
          damage: 40,
        },
      },
      {
        id: 'f1e2',
        name: 'Filter Gnome',
        emoji: '🧌',
        title: 'WHERE Corruptor',
        hp: 50, attack: 12, rewardXP: 30, isBoss: false,
        dialogue: "My kin are from Austin! Find every user in Austin or I scramble your indexes!",
        challenge: {
          type: 'write-query',
          prompt: "Get all users whose city is 'Austin'.",
          accepted: [
            "SELECT * FROM users WHERE city = 'Austin'",
            "select * from users where city = 'Austin'",
            "SELECT * FROM users WHERE city = 'austin'",
            "select * from users where city = 'austin'",
            "SELECT * FROM users WHERE city = 'Austin';",
          ],
          tip: "SELECT * FROM users, then filter by city with WHERE.",
          tipReveal: "SELECT * FROM users WHERE city = 'Austin'",
          damage: 50,
        },
      },
      {
        id: 'f1e3',
        name: 'Order Troll',
        emoji: '👹',
        title: 'Chaos Incarnate',
        hp: 60, attack: 15, rewardXP: 35, isBoss: false,
        dialogue: "I despise ORDER! But you may pass if you sort users from oldest to youngest!",
        challenge: {
          type: 'fill-blank',
          template: 'SELECT * FROM users ORDER BY age ___;',
          blanks: ['DESC'],
          tip: 'Oldest = largest age = which direction?',
          tipReveal: 'DESC (descending) puts the largest numbers first',
          damage: 60,
        },
      },
      {
        id: 'f1boss',
        name: 'Goblin King',
        emoji: '👑',
        title: '⚔ BOSS',
        hp: 120, attack: 20, rewardXP: 80, isBoss: true,
        dialogue: "Only those who can find my FIVE MOST EXPENSIVE PRODUCTS deserve to leave! Write it or suffer!",
        challenge: {
          type: 'write-query',
          prompt: 'Return all columns from products, sorted most expensive first, top 5 only.',
          accepted: [
            'SELECT * FROM products ORDER BY price DESC LIMIT 5',
            'select * from products order by price desc limit 5',
            'SELECT * FROM products ORDER BY price DESC LIMIT 5;',
          ],
          tip: 'ORDER BY price descending, then LIMIT.',
          tipReveal: 'SELECT * FROM products ORDER BY price DESC LIMIT 5',
          damage: 120,
        },
      },
    ],
  },
  {
    id: 'floor2',
    name: 'The Aggregate Swamp',
    emoji: '🌿',
    theme: 'COUNT, SUM, GROUP BY, HAVING',
    levelRequired: 3,
    intro: "The swamp creatures multiply and cluster in groups. Standard SELECT won't expose them. You need GROUP BY and aggregate functions.",
    clearText: "The swamp is drained. The JOIN Fortress looms ahead...",
    enemies: [
      {
        id: 'f2e1',
        name: 'Counting Slug',
        emoji: '🐌',
        title: 'Aggregate Pest',
        hp: 70, attack: 15, rewardXP: 40, isBoss: false,
        dialogue: "HOW MANY users exist in your precious table?! COUNT us — ALL of us!",
        challenge: {
          type: 'write-query',
          prompt: 'Count the total number of users.',
          accepted: [
            'SELECT COUNT(*) FROM users',
            'select count(*) from users',
            'SELECT COUNT(*) FROM users;',
            'SELECT COUNT(*) AS total FROM users',
            'select count(*) as total from users',
          ],
          tip: 'Use COUNT(*) as the thing you are selecting.',
          tipReveal: 'SELECT COUNT(*) FROM users',
          damage: 70,
        },
      },
      {
        id: 'f2e2',
        name: 'Swamp Witch',
        emoji: '🧙',
        title: 'Grouper of Slugs',
        hp: 80, attack: 18, rewardXP: 50, isBoss: false,
        dialogue: "SHOW ME how many users live in EACH city — or I curse your ORDER BY forever!",
        challenge: {
          type: 'fill-blank',
          template: 'SELECT city, COUNT(*) AS total FROM users ___ BY city;',
          blanks: ['GROUP'],
          tip: 'What clause collapses rows with the same value into one group?',
          tipReveal: 'GROUP BY city — one result row per unique city',
          damage: 80,
        },
      },
      {
        id: 'f2e3',
        name: 'Sum Serpent',
        emoji: '🐍',
        title: 'Aggregator of Wealth',
        hp: 90, attack: 20, rewardXP: 60, isBoss: false,
        dialogue: "I want the TOTAL AMOUNT spent by each user_id! SUM them. Group them. NOW.",
        challenge: {
          type: 'write-query',
          prompt: "Show user_id and their total amount spent (labeled 'total_spent') from the orders table.",
          accepted: [
            'SELECT user_id, SUM(amount) AS total_spent FROM orders GROUP BY user_id',
            'select user_id, sum(amount) as total_spent from orders group by user_id',
            'SELECT user_id, SUM(amount) AS total_spent FROM orders GROUP BY user_id;',
            'SELECT user_id, SUM(amount) FROM orders GROUP BY user_id',
            'select user_id, sum(amount) from orders group by user_id',
          ],
          tip: 'SUM(amount) grouped by user_id.',
          tipReveal: 'SELECT user_id, SUM(amount) AS total_spent FROM orders GROUP BY user_id',
          damage: 90,
        },
      },
      {
        id: 'f2boss',
        name: 'The Great Bog Beast',
        emoji: '🐊',
        title: '⚔ BOSS',
        hp: 160, attack: 28, rewardXP: 100, isBoss: true,
        dialogue: "ONLY powerful cities — those with 3 OR MORE USERS — may exist in MY swamp! Find them. Use HAVING. Not WHERE. HAVING!",
        challenge: {
          type: 'write-query',
          prompt: "Find cities that have 3 or more users. Show city and count (labeled 'user_count').",
          accepted: [
            'SELECT city, COUNT(*) AS user_count FROM users GROUP BY city HAVING COUNT(*) >= 3',
            'select city, count(*) as user_count from users group by city having count(*) >= 3',
            'SELECT city, COUNT(*) AS user_count FROM users GROUP BY city HAVING COUNT(*) >= 3;',
            'SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) >= 3',
            'select city, count(*) from users group by city having count(*) >= 3',
          ],
          tip: 'GROUP BY city, COUNT rows, then use HAVING (not WHERE) to filter groups.',
          tipReveal: 'SELECT city, COUNT(*) AS user_count FROM users GROUP BY city HAVING COUNT(*) >= 3',
          damage: 160,
        },
      },
    ],
  },
  {
    id: 'floor3',
    name: 'The JOIN Fortress',
    emoji: '🏰',
    theme: 'INNER JOIN, LEFT JOIN, JOIN + GROUP BY',
    levelRequired: 5,
    intro: "The fortress guards hoard data across multiple tables. Their power comes from keeping tables apart. Break through with JOIN.",
    clearText: "The fortress has fallen. Deep below, you sense an ancient presence...",
    enemies: [
      {
        id: 'f3e1',
        name: 'Sentry Golem',
        emoji: '🗿',
        title: 'Table Guardian',
        hp: 100, attack: 22, rewardXP: 65, isBoss: false,
        dialogue: "You want user names AND order amounts? Then JOIN the tables! Only users with orders count!",
        challenge: {
          type: 'write-query',
          prompt: "Show each user's name alongside their order amount. Only users who have orders.",
          accepted: [
            'SELECT users.name, orders.amount FROM users INNER JOIN orders ON users.id = orders.user_id',
            'select users.name, orders.amount from users inner join orders on users.id = orders.user_id',
            'SELECT users.name, orders.amount FROM orders INNER JOIN users ON orders.user_id = users.id',
            'select users.name, orders.amount from orders inner join users on orders.user_id = users.id',
            'SELECT users.name, orders.amount FROM users JOIN orders ON users.id = orders.user_id',
            'select users.name, orders.amount from users join orders on users.id = orders.user_id',
          ],
          tip: 'JOIN the two tables using users.id = orders.user_id.',
          tipReveal: 'SELECT users.name, orders.amount FROM users INNER JOIN orders ON users.id = orders.user_id',
          damage: 100,
        },
      },
      {
        id: 'f3e2',
        name: 'Left Hand Knight',
        emoji: '⚔️',
        title: 'Champion of NULL',
        hp: 110, attack: 25, rewardXP: 75, isBoss: false,
        dialogue: "INNER JOIN abandons users without orders! Show ALL users — NULLs are valid data! LEFT JOIN or fail!",
        challenge: {
          type: 'fill-blank',
          template: 'SELECT users.name, orders.amount FROM users ___ JOIN orders ON users.id = orders.user_id;',
          blanks: ['LEFT'],
          tip: 'Which JOIN keeps ALL rows from the left table, even without a match?',
          tipReveal: 'LEFT JOIN keeps all users even if they have no orders (those show as NULL)',
          damage: 110,
        },
      },
      {
        id: 'f3e3',
        name: 'Aggregate Archer',
        emoji: '🏹',
        title: 'Grouper of Joined Tables',
        hp: 120, attack: 28, rewardXP: 85, isBoss: false,
        dialogue: "You know JOIN. You know SUM. Combine them — each user's name and total spent. Only users with orders.",
        challenge: {
          type: 'write-query',
          prompt: "Show each user's name and total spending (labeled 'total_spent'). Only users who have orders.",
          accepted: [
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name',
            'select users.name, sum(orders.amount) as total_spent from orders inner join users on orders.user_id = users.id group by users.name',
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.name',
            'select users.name, sum(orders.amount) as total_spent from users inner join orders on users.id = orders.user_id group by users.name',
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name',
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.id, users.name',
          ],
          tip: 'INNER JOIN + GROUP BY users.name + SUM(orders.amount).',
          tipReveal: 'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name',
          damage: 120,
        },
      },
      {
        id: 'f3boss',
        name: 'The Fortress Lord',
        emoji: '🧟',
        title: '⚔ BOSS',
        hp: 220, attack: 38, rewardXP: 130, isBoss: true,
        dialogue: "POWER comes from DATA. Find cities where average order EXCEEDS 50. JOIN. GROUP. HAVING. City and average labeled 'avg_order'.",
        challenge: {
          type: 'write-query',
          prompt: "Find cities where the average order amount is above 50. Show city and the average labeled 'avg_order'.",
          accepted: [
            'SELECT users.city, AVG(orders.amount) AS avg_order FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING AVG(orders.amount) > 50',
            'select users.city, avg(orders.amount) as avg_order from orders inner join users on orders.user_id = users.id group by users.city having avg(orders.amount) > 50',
            'SELECT users.city, AVG(orders.amount) AS avg_order FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.city HAVING AVG(orders.amount) > 50',
            'select users.city, avg(orders.amount) as avg_order from users inner join orders on users.id = orders.user_id group by users.city having avg(orders.amount) > 50',
            'SELECT users.city, AVG(orders.amount) FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING AVG(orders.amount) > 50',
          ],
          tip: 'JOIN → GROUP BY city → AVG(amount) → HAVING to filter groups.',
          tipReveal: "SELECT users.city, AVG(orders.amount) AS avg_order FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING AVG(orders.amount) > 50",
          damage: 220,
        },
      },
    ],
  },
  {
    id: 'floor4',
    name: "The Dragon's Lair",
    emoji: '🐉',
    theme: 'Subqueries, complex aggregation, HAVING',
    levelRequired: 8,
    intro: "The Ancient Dragon hoards the most complex query patterns. Only a true SQL master can survive what lies ahead.",
    clearText: "THE DRAGON IS SLAIN. The DataRealm is restored. You have achieved SQL mastery.",
    enemies: [
      {
        id: 'f4e1',
        name: 'Fire Drake',
        emoji: '🔥',
        title: 'Subquery Serpent',
        hp: 140, attack: 35, rewardXP: 90, isBoss: false,
        dialogue: "PROVE YOUR WORTH! Find users who have placed at least one order — use a SUBQUERY within WHERE!",
        challenge: {
          type: 'fill-blank',
          template: 'SELECT name FROM users WHERE id IN (SELECT ___ FROM orders);',
          blanks: ['user_id'],
          tip: 'The inner query returns the column in orders that links back to users.id.',
          tipReveal: 'user_id is the foreign key in orders that references users.id',
          damage: 140,
        },
      },
      {
        id: 'f4e2',
        name: 'Ice Wyrm',
        emoji: '❄️',
        title: 'Freezer of Data',
        hp: 160, attack: 40, rewardXP: 110, isBoss: false,
        dialogue: "RICH users only! Find names of users who spent MORE than 500 total. JOIN. GROUP. HAVING.",
        challenge: {
          type: 'write-query',
          prompt: "Find names of users who have spent more than 500 total across all orders.",
          accepted: [
            'SELECT users.name FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name HAVING SUM(orders.amount) > 500',
            'select users.name from orders inner join users on orders.user_id = users.id group by users.name having sum(orders.amount) > 500',
            'SELECT users.name FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.name HAVING SUM(orders.amount) > 500',
            'select users.name from users inner join orders on users.id = orders.user_id group by users.name having sum(orders.amount) > 500',
            'SELECT users.name, SUM(orders.amount) FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name HAVING SUM(orders.amount) > 500',
            'SELECT users.name FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name HAVING SUM(orders.amount) > 500',
          ],
          tip: 'JOIN → GROUP BY users.name → HAVING SUM(orders.amount) > 500.',
          tipReveal: 'SELECT users.name FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name HAVING SUM(orders.amount) > 500',
          damage: 160,
        },
      },
      {
        id: 'f4e3',
        name: 'Shadow Drake',
        emoji: '🌑',
        title: 'Corruptor of Logic',
        hp: 180, attack: 45, rewardXP: 130, isBoss: false,
        dialogue: "This query is BROKEN. WHERE cannot use aggregate functions! Fix it or join me in darkness!",
        challenge: {
          type: 'fix-bug',
          brokenQuery: 'SELECT users.city, SUM(orders.amount) AS revenue\nFROM orders INNER JOIN users ON orders.user_id = users.id\nWHERE SUM(orders.amount) > 1000\nGROUP BY users.city;',
          accepted: [
            'SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING SUM(orders.amount) > 1000',
            'select users.city, sum(orders.amount) as revenue from orders inner join users on orders.user_id = users.id group by users.city having sum(orders.amount) > 1000',
            'SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING SUM(orders.amount) > 1000;',
          ],
          tip: 'WHERE cannot filter aggregate results. Move the filter to after GROUP BY.',
          tipReveal: 'Replace WHERE SUM(...) > 1000 with: GROUP BY users.city HAVING SUM(orders.amount) > 1000',
          damage: 180,
        },
      },
      {
        id: 'f4boss',
        name: 'The Ancient Dragon',
        emoji: '🐲',
        title: '⚔ FINAL BOSS',
        hp: 400, attack: 60, rewardXP: 250, isBoss: true,
        dialogue: "SO. A MORTAL ACTUALLY MADE IT HERE. Centuries I have waited. Prove your mastery. Top 3 spenders. Names. Totals labeled 'total_spent'. Highest first. No help exists now. You either know SQL... or you don't.",
        challenge: {
          type: 'write-query',
          prompt: "Find the top 3 users by total amount spent. Return name and total (labeled 'total_spent'), highest first.",
          accepted: [
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3',
            'select users.name, sum(orders.amount) as total_spent from orders inner join users on orders.user_id = users.id group by users.name order by total_spent desc limit 3',
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3',
            'select users.name, sum(orders.amount) as total_spent from users inner join orders on users.id = orders.user_id group by users.name order by total_spent desc limit 3',
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3',
            'select users.name, sum(orders.amount) as total_spent from orders join users on orders.user_id = users.id group by users.name order by total_spent desc limit 3',
            'SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.id, users.name ORDER BY total_spent DESC LIMIT 3',
          ],
          tip: 'JOIN → GROUP BY users.name → SUM(orders.amount) → ORDER BY total_spent DESC → LIMIT 3',
          tipReveal: "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
          damage: 400,
        },
      },
    ],
  },
];

// ── Campaign Challenges ───────────────────────────────────────────────────────

export const challengeData = {
  beginner: [
    {
      id: 'b1', type: 'fill-blank', title: 'Select Everything',
      prompt: 'Grab every column and every row from the users table.',
      template: 'SELECT ___ FROM users;',
      blanks: ['*'],
      tip: 'The wildcard character for "all columns" is a single symbol.',
      tipReveal: '* means every column — SELECT * gets them all',
      xp: 10,
    },
    {
      id: 'b2', type: 'multiple-choice', title: 'Find the Austinites',
      prompt: "Which query finds all users who live in Austin?",
      options: [
        { text: "SELECT * FROM users WHERE city = 'Austin';",     correct: true  },
        { text: "SELECT * WHERE city = 'Austin' FROM users;",     correct: false },
        { text: "SELECT city FROM users WHERE * = 'Austin';",     correct: false },
        { text: "GET * FROM users WHERE city = 'Austin';",        correct: false },
      ],
      tip: 'SQL keywords must appear in a specific order.',
      tipReveal: 'SELECT → FROM → WHERE is the required order',
      xp: 10,
    },
    {
      id: 'b3', type: 'fill-blank', title: 'Add a Filter',
      prompt: 'You only want users from Denver. What keyword introduces the filter?',
      template: "SELECT name, email FROM users ___ city = 'Denver';",
      blanks: ['WHERE'],
      tip: 'This keyword comes after FROM and filters rows before returning them.',
      tipReveal: 'WHERE filters rows based on a condition',
      xp: 10,
    },
    {
      id: 'b4', type: 'fill-blank', title: 'Oldest First',
      prompt: 'Sort users by age, oldest at the top.',
      template: 'SELECT * FROM users ORDER BY age ___;',
      blanks: ['DESC'],
      tip: 'Ascending = smallest first. You want the opposite direction.',
      tipReveal: 'DESC = descending = largest/oldest first',
      xp: 10,
    },
    {
      id: 'b5', type: 'multiple-choice', title: 'Just Give Me Five',
      prompt: 'Which query returns only the first 5 products?',
      options: [
        { text: 'SELECT * FROM products LIMIT 5;',            correct: true  },
        { text: 'SELECT 5 FROM products;',                    correct: false },
        { text: 'SELECT * FROM products WHERE count = 5;',    correct: false },
        { text: 'SELECT * FROM products MAX 5;',              correct: false },
      ],
      tip: 'There is one keyword that means "stop after N rows."',
      tipReveal: 'LIMIT N caps the result at N rows',
      xp: 10,
    },
    {
      id: 'b6', type: 'fix-bug', title: 'Spot the Typos',
      prompt: 'Two keywords are misspelled. Fix them.',
      brokenQuery: 'SELEC * FORM users;',
      accepted: ['SELECT * FROM users;', 'SELECT * FROM users'],
      tip: 'Look carefully at the first word and the third word.',
      tipReveal: 'SELEC → SELECT and FORM → FROM',
      xp: 15,
    },
    {
      id: 'b7', type: 'what-returns', title: 'What Comes Back?',
      prompt: 'What does this query return?',
      queryDisplay: 'SELECT COUNT(*) FROM users;',
      options: [
        { text: 'All users in the table',                            correct: false },
        { text: 'A single number: how many users exist',             correct: true  },
        { text: 'The users table with an extra count column',        correct: false },
        { text: 'An error — you cannot SELECT COUNT',                correct: false },
      ],
      tip: 'COUNT(*) is an aggregate function that counts something.',
      tipReveal: 'COUNT(*) returns exactly one number: the total row count',
      xp: 10,
    },
    {
      id: 'b8', type: 'write-query', title: 'Write It Yourself',
      prompt: 'Get the name and age of every user, sorted A to Z by name.',
      accepted: [
        'SELECT name, age FROM users ORDER BY name',
        'SELECT name, age FROM users ORDER BY name ASC',
        'select name, age from users order by name',
        'select name, age from users order by name asc',
      ],
      tip: 'You need SELECT, FROM, and ORDER BY. A–Z is which direction?',
      tipReveal: "ASC = ascending = A to Z (it's also the default if you omit it)",
      xp: 20,
    },
  ],

  intermediate: [
    {
      id: 'i1', type: 'fill-blank', title: 'Count by City',
      prompt: 'Count how many users live in each city.',
      template: 'SELECT city, COUNT(*) AS total FROM users ___ BY city;',
      blanks: ['GROUP'],
      tip: 'This clause collapses rows that share a value into one group.',
      tipReveal: 'GROUP BY organizes rows so each unique value = one result row',
      xp: 15,
    },
    {
      id: 'i2', type: 'write-query', title: 'Double Filter',
      prompt: 'Return the name and email of users older than 30 who live in Chicago.',
      accepted: [
        "SELECT name, email FROM users WHERE age > 30 AND city = 'Chicago'",
        "select name, email from users where age > 30 and city = 'chicago'",
        "SELECT name, email FROM users WHERE city = 'Chicago' AND age > 30",
        "select name, email from users where city = 'chicago' and age > 30",
      ],
      tip: 'You need two WHERE conditions. Chain them with a keyword meaning "both must be true."',
      tipReveal: "Use AND between conditions: WHERE age > 30 AND city = 'Chicago'",
      xp: 20,
    },
    {
      id: 'i3', type: 'fill-blank', title: 'Total Spending',
      prompt: "Add up each user's total amount spent across all of their orders.",
      template: 'SELECT user_id, ___(amount) AS total FROM orders GROUP BY user_id;',
      blanks: ['SUM'],
      tip: 'You need an aggregate function that adds numbers together.',
      tipReveal: 'SUM(col) adds up all values in a column within each group',
      xp: 15,
    },
    {
      id: 'i4', type: 'multiple-choice', title: 'HAVING vs WHERE',
      prompt: 'Which query correctly finds cities that have more than 5 users?',
      options: [
        { text: 'SELECT city, COUNT(*) FROM users WHERE COUNT(*) > 5 GROUP BY city;', correct: false },
        { text: 'SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) > 5;', correct: true  },
        { text: 'SELECT city, COUNT(*) FROM users HAVING COUNT(*) > 5;',               correct: false },
        { text: 'SELECT city, COUNT(*) FROM users GROUP BY city WHERE COUNT(*) > 5;',  correct: false },
      ],
      tip: 'WHERE runs before grouping. You need something that runs after the groups are formed.',
      tipReveal: 'HAVING filters groups — it can use aggregate functions; WHERE cannot',
      xp: 15,
    },
    {
      id: 'i5', type: 'fill-blank', title: 'Left or Inner?',
      prompt: 'Get every user and their orders. Include users who have no orders at all.',
      template: 'SELECT users.name, orders.amount FROM users ___ JOIN orders ON users.id = orders.user_id;',
      blanks: ['LEFT'],
      tip: 'INNER JOIN drops non-matching rows. You want ALL users, even empty-handed ones.',
      tipReveal: 'LEFT JOIN keeps every row from the left table, regardless of matches',
      xp: 20,
    },
    {
      id: 'i6', type: 'write-query', title: 'Update a Record',
      prompt: "Change user id 12's city to 'Seattle'.",
      accepted: [
        "UPDATE users SET city = 'Seattle' WHERE id = 12",
        "update users set city = 'Seattle' where id = 12",
        "UPDATE users SET city = 'seattle' WHERE id = 12",
        "UPDATE users SET city = 'Seattle' WHERE id = 12;",
      ],
      tip: 'You need UPDATE, SET, and WHERE. Leave off WHERE and you change every single user.',
      tipReveal: 'UPDATE tablename SET column = value WHERE condition',
      xp: 20,
    },
    {
      id: 'i7', type: 'fix-bug', title: 'Fix the JOIN',
      prompt: 'This JOIN links the wrong columns. Fix it.',
      brokenQuery: 'SELECT users.name, orders.amount FROM orders INNER JOIN users ON orders.id = users.id;',
      accepted: [
        'SELECT users.name, orders.amount FROM orders INNER JOIN users ON orders.user_id = users.id;',
        'SELECT users.name, orders.amount FROM orders INNER JOIN users ON users.id = orders.user_id;',
        'select users.name, orders.amount from orders inner join users on orders.user_id = users.id;',
        'select users.name, orders.amount from orders inner join users on orders.user_id = users.id',
        'select users.name, orders.amount from orders inner join users on users.id = orders.user_id',
      ],
      tip: 'orders has a column that links back to users. It is not orders.id.',
      tipReveal: 'orders.user_id is the foreign key that connects to users.id',
      xp: 25,
    },
    {
      id: 'i8', type: 'write-query', title: 'Clean Up',
      prompt: 'Delete all orders where the amount is 0.',
      accepted: [
        'DELETE FROM orders WHERE amount = 0',
        'delete from orders where amount = 0',
        'DELETE FROM orders WHERE amount = 0;',
      ],
      tip: 'Always include WHERE when deleting, or you nuke the entire table.',
      tipReveal: 'DELETE FROM table WHERE condition',
      xp: 20,
    },
  ],

  advanced: [
    {
      id: 'a1', type: 'write-query', title: 'Power Users',
      prompt: 'Find users who have placed more than 3 orders. Return user_id and their order count labeled "order_count".',
      accepted: [
        'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id HAVING COUNT(*) > 3',
        'select user_id, count(*) as order_count from orders group by user_id having count(*) > 3',
        'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id HAVING COUNT(*) > 3;',
      ],
      tip: 'GROUP BY user_id, COUNT the rows per group, then filter the groups.',
      tipReveal: 'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id HAVING COUNT(*) > 3',
      xp: 30,
    },
    {
      id: 'a2', type: 'fill-blank', title: 'Subquery Sniper',
      prompt: 'Find names of users who have ever placed an order over $500. Use a subquery.',
      template: 'SELECT name FROM users WHERE id IN (SELECT ___ FROM orders WHERE amount > 500);',
      blanks: ['user_id'],
      tip: 'The inner query must return the column that matches users.id.',
      tipReveal: 'user_id is the foreign key connecting orders back to users',
      xp: 30,
    },
    {
      id: 'a3', type: 'write-query', title: 'Revenue by City',
      prompt: "Join users and orders to get the average order amount per city. Label the average 'avg_order'.",
      accepted: [
        'SELECT users.city, AVG(orders.amount) AS avg_order FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city',
        'SELECT users.city, AVG(orders.amount) AS avg_order FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.city',
        'select users.city, avg(orders.amount) as avg_order from orders inner join users on orders.user_id = users.id group by users.city',
        'select users.city, avg(orders.amount) as avg_order from users inner join orders on users.id = orders.user_id group by users.city',
        'SELECT users.city, AVG(orders.amount) AS avg_order FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.city',
        'select users.city, avg(orders.amount) as avg_order from orders join users on orders.user_id = users.id group by users.city',
      ],
      tip: 'You need JOIN to connect tables, AVG() to average amounts, GROUP BY city for grouping.',
      tipReveal: 'JOIN users ON user_id, then GROUP BY users.city, SELECT AVG(orders.amount)',
      xp: 35,
    },
    {
      id: 'a4', type: 'what-returns', title: 'Read the Room',
      prompt: 'What does this query return?',
      queryDisplay: `SELECT city, COUNT(*) AS users, AVG(age) AS avg_age
FROM users
GROUP BY city
HAVING COUNT(*) >= 3
ORDER BY avg_age DESC;`,
      options: [
        { text: 'All cities with user counts',                                                                  correct: false },
        { text: 'Cities that have 3+ users, with count and average age, sorted oldest-average first',          correct: true  },
        { text: 'The 3 oldest users per city',                                                                  correct: false },
        { text: 'An error — you cannot mix GROUP BY and ORDER BY',                                             correct: false },
      ],
      tip: 'Read each clause. HAVING filters which groups survive. ORDER BY DESC sorts the final output.',
      tipReveal: 'HAVING COUNT(*) >= 3 drops small cities. ORDER BY avg_age DESC = highest average age first',
      xp: 30,
    },
    {
      id: 'a5', type: 'fix-bug', title: 'Aggregate Error',
      prompt: 'This query should find high-revenue cities but has a logic error. Fix it.',
      brokenQuery: `SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id WHERE SUM(orders.amount) > 1000 GROUP BY users.city;`,
      accepted: [
        'SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING SUM(orders.amount) > 1000',
        'select users.city, sum(orders.amount) as revenue from orders inner join users on orders.user_id = users.id group by users.city having sum(orders.amount) > 1000',
        'SELECT users.city, SUM(orders.amount) AS revenue FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.city HAVING SUM(orders.amount) > 1000;',
      ],
      tip: 'WHERE cannot use aggregate functions like SUM(). Move the filter to after the grouping.',
      tipReveal: 'Replace WHERE SUM() with HAVING SUM() and move it after GROUP BY',
      xp: 40,
    },
    {
      id: 'a6', type: 'write-query', title: 'Top 3 Spenders',
      prompt: "Find the top 3 users by total amount spent. Return their name and total labeled 'total_spent'. Most spent first.",
      accepted: [
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.id, users.name ORDER BY total_spent DESC LIMIT 3",
        "select users.name, sum(orders.amount) as total_spent from orders inner join users on orders.user_id = users.id group by users.id, users.name order by total_spent desc limit 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
        "select users.name, sum(orders.amount) as total_spent from orders join users on orders.user_id = users.id group by users.name order by total_spent desc limit 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM users INNER JOIN orders ON users.id = orders.user_id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
        "SELECT users.name, SUM(orders.amount) AS total_spent FROM orders INNER JOIN users ON orders.user_id = users.id GROUP BY users.name ORDER BY total_spent DESC LIMIT 3",
      ],
      tip: 'JOIN → GROUP BY user → SUM amount → ORDER BY that sum DESC → LIMIT 3.',
      tipReveal: 'JOIN, GROUP BY users.name, SELECT SUM(orders.amount) AS total_spent, ORDER BY total_spent DESC, LIMIT 3',
      xp: 40,
    },
  ],
};
